### ISSUE TITLE
Fix playerbookeditevent

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5458] opened 2021-04-05 02:37 UTC
### Expected behavior

the event should work, modifying e.getnewmeta should apply to the item

### Observed/Actual behavior

event is broken, e.getnewmeta doesn't apply

### Steps/models to reproduce

sign/edit book

### Plugin list

a plugin that hooks into playerbookeditevent

### Paper version

580 paper 1.16.5

### Agreements

I am running the latest version of Paper available from https://papermc.io/downloads.
I have searched for and ensured there isn't already an open issue regarding this.
My version of Minecraft is supported by Paper.

**Comment by aurorasmiles** [comment] 2021-04-05 02:57
Duplicate of #2329

**Closed as completed by aurorasmiles** 2021-04-05 02:57 UTC
