### ISSUE TITLE
bug or something

### ISSUE THREAD

**Issue by fukurocro** [PaperMC/Paper#2122] opened 2019-06-02 19:46 UTC
[19:31:25] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
--
java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-59]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-59]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:31:27] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-59]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-59]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:31:27] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-59]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-59]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:31:43] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:160) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:150) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.setGoalTarget(EntityFox.java:506) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox$a.c(EntityFox.java:1199) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.2.jar:git-Paper-59]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:658) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:155) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.movementTick(EntityFox.java:145) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.EntityFox.tick(EntityFox.java:423) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-59]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-59]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by electronicboy** [comment] 2019-06-02 19:47
Duplicate of #2069

**Closed as completed by electronicboy** 2019-06-02 19:47 UTC
Labels: resolution: duplicate, version: 1.14
