### ISSUE TITLE
ArrayIndexOutOfBoundsException: 48 & Couldn't load chunk / Couldn't load protochunk server crash due to chunk corruption.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1973] opened 2019-04-16 17:39 UTC
Paper dev 680
https://papermc.io/ci/view/all/job/Paper-1.13/
FastAsyncWorldEdit-Breaking dev 60 
http://ci.athion.net/job/FastAsyncWorldEdit-Breaking/changes
ProtocolSupport dev 377
https://build.true-games.org/job/ProtocolSupport/

Had a player run the WorldEdit operation ``//regen`` in an area and apparently it corrupted the chunks. Every time they login into the area now, the server crashes. The chunks do not regenerate per commit https://github.com/PaperMC/Paper/commit/41c86a654882e668040d5e4f24840bbf93e6dd78 @electronicboy 

Crash Log
https://paste.ubuntu.com/p/B7XswqSt6f/

```
java.lang.ArrayIndexOutOfBoundsException: 48
	at net.minecraft.server.v1_13_R2.Chunk.initLighting(Chunk.java:279)
	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:647)
	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:628)
	at net.minecraft.server.v1_13_R2.World.a(World.java:767)
	at net.minecraft.server.v1_13_R2.World.updateBrightness(World.java:2350)
	at net.minecraft.server.v1_13_R2.World.c(World.java:2244)
	at net.minecraft.server.v1_13_R2.World.r(World.java:2169)
	at net.minecraft.server.v1_13_R2.World.lambda$setTypeAndData$1(World.java:446)
	at net.minecraft.server.v1_13_R2.Chunk.runOrQueueLightUpdate(Chunk.java:1520)
	at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:446)
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:310)
	at net.minecraft.server.v1_13_R2.FluidTypeLava.a(FluidTypeLava.java:169)
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:161)
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:515)
	at net.minecraft.server.v1_13_R2.Fluid.a(SourceFile:56)
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:666)
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:85)
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:658)
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:297)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1091)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
	at java.lang.Thread.run(Thread.java:748)
```

Error when logging in.
https://paste.ubuntu.com/p/jfN7Vdm7bq/

```
[12:12:53] [PaperChunkLoader-4/ERROR]: Couldn't load chunk (world:185,-456)
java.lang.ArrayIndexOutOfBoundsException: 16
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:971) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:750) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:305) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:260) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.loadChunk(PaperAsyncChunkProvider.java:387) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.run(PaperAsyncChunkProvider.java:579) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.lambda$createPendingTask$1(PriorityQueuedExecutor.java:133) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:196) ~[patched_1.13.2.jar:git-Paper-620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
```
[12:12:53] [PaperChunkGen-world/ERROR]: Couldn't load protochunk
java.lang.ArrayIndexOutOfBoundsException: 16
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:971) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:750) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:305) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.b(ChunkRegionLoader.java:347) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.b(ChunkRegionLoader.java:281) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.lambda$a$3(ChunkTaskScheduler.java:76) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:93) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:13) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler.b(SourceFile:80) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:46) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_202]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_202]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SchedulerBatch.java:39) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.add(SchedulerBatch.java:34) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.generateChunk(PaperAsyncChunkProvider.java:407) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:196) ~[patched_1.13.2.jar:git-Paper-620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by mibby** [comment] 2019-04-16 18:00
Here is a download of the corrupt chunk regions for testing.
https://www.dropbox.com/s/u82cvtf2qexo8n9/ChunkRegion.zip?dl=1

Coordinate area.
> Block location: World: (3095,18,-7199), Chunk: (at 7,1,1 in 193,-450; contains blocks 3088,0,-7200 to 3103,255,-7185), Region: (6,-15; contains chunks 192,-480 to 223,-449, blocks 3072,0,-7680 to 3583,255,-7169)

> Couldn't load chunk (world:191,-453)

> (2939, 48, -7337) - (2943, 55, -7187)

**Comment by Chew** [comment] 2020-11-14 19:31
Given as this is over a year old, and we've had numerous changes to this, and it appears to have been caused by a plugin, I'll be closing this issue. If this issue for whatever reason persists on a supported version, and was not caused by a plugin, feel free to open a new issue. Thanks for the report!

**Closed as completed by Chew** 2020-11-14 19:31 UTC
Labels: type: bug, resolution: unsupported, version: 1.13
