### ISSUE TITLE
announce-player-achievements

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Paper#826] opened 2017-08-03 15:00 UTC
announce-player-achievements=false dont work in server.properties
build paperspigot latest

**Comment by electronicboy** [comment] 2017-08-03 15:03
Duplicate of #798 
Duplicate of #725 
Duplicate of #768

**Comment by kashike** [comment] 2017-08-03 15:30
Duplicate of #798 
Duplicate of #725 
Duplicate of #768

**Closed as completed by kashike** 2017-08-03 15:30 UTC
Labels: resolution: duplicate
