### ISSUE TITLE
Merged XP orbs seem to have a negative values sometimes.

### ISSUE THREAD

**Issue by Frogperson** [PaperMC/Paper#1169] opened 2018-06-22 20:22 UTC
### What behaviour is expected:
XP orbs should never be negative

### What behaviour is observed:
Some of my players are reporting XP orbs damaging their items with mending which sounds to me like they're getting negative XP

### Steps/models to reproduce:
Not sure of the exact steps (I don't play on the server much) but I assume just have a mob farm that creates a lot of XP, like a zombie pigmen farm, and then collect the merged xp while holding mending items.

### Plugin list:
Plugins (29): ColoredNames, CoreProtect, DiscordSRV, dynmap, EasySetSpawn, EnderAdditions, EntityDetection, EpicWorldGenerator, Essentials, EssentialsChat, F3NPerm, GhostBlockKiller, Java-Version-Tool, MassiveCore, MassiveLag, ModDetector, OpenInv, PermissionsEx, PetOwner, PlayerActivity, PlugMan, ProtocolLib, SimpleTicketManager, Sleep, SuperVanish, Vault, WorldEdit, WorldGuard, XrayInformer

### Paper build number:
1466

### Anything else:
We had this issue a few months ago as well but just decided to disable merging as a temporary fix. We would like to re-enable it but this bug is making it impossible for us to do so.

**Comment by BillyGalbreath** [comment] 2018-06-22 21:06
Could you test [build #1261](https://destroystokyo.com/ci/job/Paper/1261/) to see if the issue is still there? I have a hunch it's something to do with a [new mending event](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/bdb88226252f029f6b752c0a83740eb74f7a4ba8#nms-patches/EntityExperienceOrb.patch) Spigot from Nov 20. If not it might be something in my [max exp merge code](https://github.com/PaperMC/Paper/commit/072d6ec8cbd6bf49cf2d109bcca584fc129ab66c) from Nov 10. Things like this get harder to debug the farther back the issue was introduced.

**Comment by aikar** [comment] 2018-07-17 17:58
I've also now got reports of this on my server too.

@BillyGalbreath that patch def seems suspect to be the cause.

**Comment by BillyGalbreath** [comment] 2018-07-18 12:44
Alright. I'll look at it this weekend. I see @zachbr made some changes during the merge that @Brokkonaut had suggested. Not sure if that's messing with it or not (I did extensive testing before that change and never saw a negative value). Trying to read it now just co fuses the shit out of me. I'll probably just rewrite it so it's easier to read which might fix it (if that's the cause)

**Comment by aikar** [comment] 2018-07-18 17:43
@BillyGalbreath we extensively reviewed the code last night, your event seems fine.

The mending event is also not the source, as that occurs AFTER the ExperiencePickupEvent, so the EXP orb itself is somehow negative.

**Comment by aikar** [comment] 2018-08-02 16:54
We are looking for any assistance figuring this one out.

**Comment by aikar** [comment] 2018-08-02 18:09
new information from billy and chickeneer shows that orbs are over flowing, due to 2 issues:

1) its possible to overflow integer value with extremely large orbs
2) mojang saves orbs as a short instead of int, causing loss there.

This is considered a Spigot bug since spigot added XP merging, which isnt present in Vanilla, so mojangs code is fine in vanilla context.

It's merging that causes overflows.

we need to change all of this to long. i'll do it this evening.

**Comment by aikar** [comment] 2018-08-03 04:15
Fixed in 1525

**Comment by aikar** [comment] 2018-08-03 17:24
Reopened as fix made the problem worse, but fix to the new problem will be done soon as I get home.

**Closed as completed** 2018-08-04 00:59 UTC
Labels: type: bug, help wanted, status: input wanted, status: accepted, upstream: spigot
