### ISSUE TITLE
RCON utf8 support?

### ISSUE THREAD

**Issue by Nats-ji** [PaperMC/Paper#5360] opened 2021-03-14 12:24 UTC
### What behaviour is expected:
Encode the rcon payload using utf-8.

### What behaviour is observed:
The server trying to encode the received rcon payload using ascii.
This is what my rcon client: received from the server, as you can see, it tries to encode the utf-8 characters as ascii.
```
[DEBUG] Sending command "minecraft:tellraw @a [{"color": "#A790FC", "text": "<Ming> 你好"}]" to the server
[DEBUG] Received response: Invalid chat component: Unterminated string at line 1 column 41 path $[0].text...ellraw @a [{"color": "#A790FC", "text": "<Ming> d= o?=<--[HERE]
[DEBUG] Rcon closed!
```

### Steps/models to reproduce:
Send commands that include utf-8 characters to the server through a rcon client.

### Plugin list:
none

### Paper version:
`This server is running Paper version git-Paper-547 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Anything else:
This might be helpful:
https://github.com/MinecraftForge/MinecraftForge/commit/5f292895cb89d42b9a5d12922c80541874e0bf39

**Comment by zachbr** [comment] 2021-05-16 06:59
I cannot reproduce any issues with unicode support in RCON given the example you provided or my own ugly conglomerations of emoji.

If you have more information, providing it may be helpful.
* The operating system and version running the server.
* The operating system and version running the RCON client.
* A link to the RCON client or any technical details about it.
* etc.

I started my testing on Linux where, everything just worked. The entire system using UTF-8 for everything is really king in this regard. Many issues with character encoding just disappear, although I did have it working on Windows eventually as well.
![linux](https://user-images.githubusercontent.com/1254957/118388207-a928de00-b5e8-11eb-8f41-eaeaf42bc81a.png)

On the Windows side of things, I did encounter issues the first time, however they do not match yours. It appears that many of the RCON clients for Windows weren't handling unicode properly. I did not delve too far into the technical details, however many just completely cut off the RCON body when they hit any complicated characters.

I did start testing with the UTF-8 beta setting enabled in the Control Panel, Region panel. I cannot confirm whether or not this helped anything. It seemed to at first but I was also rotating through clients. I eventually settled on a [python client](https://pypi.org/project/rcon/) that just worked.
![windows-region-setting](https://user-images.githubusercontent.com/1254957/118388259-f60cb480-b5e8-11eb-8bc6-29526adb0eed.png)

Eventually, I switched it back off and continued with testing. Things kept working with the python client event after this, but I wouldn't necessarily put it past windows to not fully revert its region handling properly. Regions in Windows have always been a little odd.

In the end, even with that setting supposedly off I did get your original example to work just fine.
![windows-with-region-utf8](https://user-images.githubusercontent.com/1254957/118388316-4ab02f80-b5e9-11eb-85b1-31bc04716fd7.png)

That's Windows `20H2 19042.985`, in case it does matter later.

Throughout the testing I made sure to test a properly formatted `tellraw` example and a malformed example so that the server would have to process the input and send those same characters back to me, as part of the error message. As you can see, in both cases they render properly.

As I eluded earlier, I did come across many RCON clients, especially for Windows, that did not support unicode at all, and at least one that said it did but was sending incorrect data. I used Wireshark to verify the data being sent from the clients was correct (or not). As RCON is unencrypted it is fairly easy to double check.

I'm not sure where to go from here. I fully expected to find some problem in Windows, as is tradition, with the encodings but I cannot. If you have any more details please share but this may be something you need to investigate yourself. I am closing this ticket for the time being. Thanks.

**Closed as completed by zachbr** 2021-05-16 06:59 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.16
