### ISSUE TITLE
InventoryCloseEvent not firing.

### ISSUE THREAD

**Issue by Fi1zz** [PaperMC/Paper#3777] opened 2020-07-03 17:41 UTC
### What behaviour is expected:
This event should be triggered when the player closes the backpack

### What behaviour is observed:
This event will not be triggered if the player closes the backpack

### Steps/models to reproduce:
    @EventHandler
    public void InvenClose(InventoryCloseEvent event) {}
### Plugin list:
NULL

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of 
Starting minecraft server version 1.16.1

**Comment by Proximyst** [comment] 2020-07-03 17:43
If by backpack you mean inventory, it shouldn't fire the event. The client doesn't tell the server when the inventory is open & closed, that's why cheats like inventory walk work fine.

**Comment by Machine-Maker** [comment] 2020-07-03 17:44
> If by backpack you mean inventory, it shouldn't fire the event. The client doesn't tell the server when the inventory is open & closed, that's why cheats like inventory walk work fine.

The client does tell the server when the inventory is closed. There is a windowclosepacket. Spigot broke this kinda, and #3768 should fix it.

Pre-build 371 on 1.15.2 the event fired when the player closed their own inventory, but when aikar pulled changes from upstream, it broke it.

**Comment by Machine-Maker** [comment] 2020-07-03 17:48
This is probably a duplicate of #3733

**Comment by Machine-Maker** [comment] 2020-07-08 00:12
This can be closed, as #3733 was closed.

**Comment by Chew** [comment] 2020-08-21 04:19
As this was a duplicate of #3733, and it was closed, this will be closed as well. If this issue is still occurring on the latest version feel free to reopen it with new logs and reproduction steps. Thanks for the report, have a good day!

**Closed as completed by Chew** 2020-08-21 04:19 UTC
Labels: resolution: duplicate
