### ISSUE TITLE
Throwables don't despawn when in bubble columns + have weird behavior.

### ISSUE THREAD

**Issue by SirKillian** [PaperMC/Paper#5772] opened 2021-06-03 06:21 UTC
### Timings or Profile link

https://spark.lucko.me/e9tpPwnjLG

### Description of issue

When a throwable is thrown inside a bubble column. it will never despawn. However, after the despawn timer is over, the throwables get weird behavior. For example, they no longer collide with players but only with blocks or they have weird vanishing behavior.

[Video: How to replicate](https://youtu.be/E11uoCRD2Vo)
[Video: Weird behavior after despawn timer is over](https://youtu.be/AfXcF7OMC8E)

Does not affect all projectiles. Seems to be a throwables only. I tested with thrown exp bottles as well with ender pearls.
Arrows despawn properly.

### Plugin list

This can be replicated with 0 plugins on the server.

### Server config files

[Bukkit.yml](https://paste.gg/p/anonymous/eda5a63b57c54bd8b47e47bcba7a4a4c)
[Spigot.yml](https://paste.gg/p/anonymous/a56c1d0ae110409b9c9348d65777d122)
[Paper.yml](https://paste.gg/p/anonymous/d355df21ee094c8d99f6f3bd90246f3d)
[Server.properties](https://paste.gg/p/anonymous/67c9c86593774e94bfd1999606ce5cbc)

### Paper version

[02:17:59 INFO]: This server is running Paper version git-Paper-762 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Chew** [comment] 2021-06-03 21:00
> When a throwable is thrown inside a bubble column. it will never despawn

I believe this is vanilla behavior unless we mess with it. 

> However, after the despawn timer is over, the throwables get weird behavior. For example, they no longer collide with players but only with blocks or they have weird vanishing behavior.

This however, is an issue

**Comment by sleepylessons** [comment] 2021-06-04 17:24
@SirKillian I've had to fix this issue by limiting the number of certain throwables that can exist. I use FarmLimiter spigot plugin to accomplish this. 

There is also a setting in Paper config that allows you to change the despawn time of Arrows/Snowballs/etc. You could set those very low to force them to despawn.

**Comment by Machine-Maker** [comment] 2022-01-14 04:34
So I think [the vanilla issue](https://bugs.mojang.com/browse/MC-125757) has been marked as works as intended. If there is some reproducible behavioral difference between vanilla and paper in this regard, this can be re-opened.

**Closed as completed by Machine-Maker** 2022-01-14 04:34 UTC
Labels: type: bug, resolution: works as intended, version: 1.17
