### ISSUE TITLE
Paper 312 | Async Chunk Task Thread #6/ERROR

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#3442] opened 2020-05-24 20:16 UTC
Paper 312 

Getting these sometimes

`[16:10:29] [Paper Async Chunk Task Thread #6/ERROR]: Failed to serialize unloading chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkSaveTask, for world 'World_nether', (1111582,336906), hashcode:496723568, priority: -1, falling back to a synchronous execution
net.minecraft.server.v1_15_R1.ReportedException: Writing into PalettedContainer from multiple threads (other thread: name: Server-Worker-3, class: class net.minecraft.server.v1_15_R1.SystemUtils$1)
	at net.minecraft.server.v1_15_R1.DataPaletteBlock.a(DataPaletteBlock.java:41) ~[patched_1.15.2.jar:git-Paper-312]
	at net.minecraft.server.v1_15_R1.DataPaletteBlock.a(DataPaletteBlock.java:233) ~[patched_1.15.2.jar:git-Paper-312]
	at net.minecraft.server.v1_15_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:417) ~[patched_1.15.2.jar:git-Paper-312]
	at com.destroystokyo.paper.io.chunk.ChunkSaveTask.run(ChunkSaveTask.java:39) ~[patched_1.15.2.jar:git-Paper-312]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.15.2.jar:git-Paper-312]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.15.2.jar:git-Paper-312]
Caused by: java.lang.IllegalStateException
	at net.minecraft.server.v1_15_R1.DataPaletteBlock.a(DataPaletteBlock.java:37) ~[patched_1.15.2.jar:git-Paper-312]
	... 5 more
[16:10:29] [Server thread/INFO]: Successfully serialized chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkSaveTask, for world 'World_nether', (1111582,336906), hashcode:496723568, priority: -1 synchronously`

No crash, just some console errors.

**Comment by electronicboy** [comment] 2020-05-24 20:18
Please use the search feature... Duplicate of #3293

**Closed as completed by electronicboy** 2020-05-24 20:18 UTC
