### ISSUE TITLE
server crash error

### ISSUE THREAD

**Issue by jason920612** [PaperMC/Paper#1347] opened 2018-08-18 08:42 UTC
version git-Paper-140 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Plugin list:
AntiCrash, BossShop, ColorMOTD, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, GroupManager, GuiShopManager, iConomy, LaggRemover, LockettePro, MobHeads, MoneyDrop, Multiverse-Core, MysqlEconomyBank, OpenInv, OreReplacerPlugin, PlaceholderAPI, PlayerPoints, PlotSquared, ProtocolLib, PvPManager, QuickShop, RandomTeleportPro, React, Residence, TimeIsMoney, TitleManager, Vault, VipZero, WorldCommandBlock*, WorldEdit

[crashreport](https://pastebin.com/UPXe894W)

**Comment by zachbr** [comment] 2018-08-18 08:47
Duplicate of GH-1333

**Closed as completed by zachbr** 2018-08-18 08:47 UTC
Labels: resolution: duplicate
