### ISSUE TITLE
Glitching On Top of Boat/Minecart

### ISSUE THREAD

**Issue by Xarius86** [PaperMC/Paper#5113] opened 2021-01-25 21:42 UTC
### What behaviour is expected:
You should be able to walk over the top of a boat or minecart. 

### What behaviour is observed:
You end up partially stuck on top of the boat/minecart in what appears to be a teleportation loop.
(When EssentialsX is installed, the console is spammed looking for teleportation perms.)

### Steps/models to reproduce:
1) Download Paper 444.
2) Start a brand new world with zero plugins/extras or changes to configuration.
3) Place boat or minecart.
4) Try to walk on boat or minecart.

### Plugin list:
Zero. 

### Paper version:
I just deleted the server as it was a temporary test server. But, it's Paper 444.

**Comment by mibby** [comment] 2021-02-09 10:57
Can also reproduce with Paper. Hopefully it's a quick fix.

**Comment by Chew** [comment] 2021-10-02 06:46
Looks like this was fixed in Tuinity, which means it made its way into Paper ([where it still resides](https://github.com/PaperMC/Paper/blob/master/patches/server/0764-Highly-optimise-single-and-multi-AABB-VoxelShapes-an.patch)). See the above-linked issue.

If this still happens, let us know!

**Closed as completed by Chew** 2021-10-02 06:46 UTC
Labels: type: bug, status: accepted, upstream: vanilla, version: 1.16
