### ISSUE TITLE
[Server-Worker-5/ERROR]: Caught exception in thread Thread[Server-Worker-5,4,main]

### ISSUE THREAD

**Issue by Stixil** [PaperMC/Paper#3516] opened 2020-06-06 20:52 UTC
Full paste: https://mcpaste.io/12048e4350891d0e

### Plugin list:
https://docs.google.com/spreadsheets/d/1UBl1byhlLboCRhZtstqC_LlUjqs_iDU3NyrEvd8a-78/edit?usp=sharing

### Actions to reproduce (if known):
Unknown

### Paper build number:
Version 334

**Comment by aikar** [comment] 2020-06-06 23:56
Dupe of https://github.com/PaperMC/Paper/issues/3489
Can be fixed by using https://github.com/PaperMC/Paper/pull/3506 which will land  soon - build has been stable

**Closed as completed by aikar** 2020-06-06 23:56 UTC
