### ISSUE TITLE
Items dropped from TEs are not be captured during block placement

### ISSUE THREAD

**Issue by kforbro** [PaperMC/Paper#1970] opened 2019-04-14 14:57 UTC
https://youtu.be/CPyZkacmEX4

Can you fix this dupe, please? It is not worldguard bug. 
Paper 1.12.2. This dupe seems to be fixed on Paper 1.13

**Comment by electronicboy** [comment] 2019-04-14 20:11
Should be fixed in 1613+, I've left this issue up given that it's a long-standing CB bug caused by a vanilla issue, however, in the future, please do not report duplication issues on issue tracker and contact us on IRC/Discord

**Closed as completed by electronicboy** 2019-04-14 20:11 UTC
