### ISSUE TITLE
Beacon with Haste II effect is broken

### ISSUE THREAD

**Issue by gnat79** [PaperMC/Paper#5428] opened 2021-03-28 16:07 UTC
### Expected behavior

From what I've read, I should be able to instamine stone with a fully loaded beacon with Haste II.

### Observed/Actual behavior

Normal speed mining, no difference between having the beacon activated and not activated. I notice that the mining motion with the pickaxe (a maxed out netherite pickaxe) looks faster, so I would expect the blocks to be mined faster, but they take just as long.

### Steps/models to reproduce

Make a beacon, try to mine while in range. I've done a fair amount of research online, and I know that beacons can trip people up, but I'm confident that I'm doing everything right. Not 10000% confident, but very confident.

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-571 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-337 (MC: 1.16.4)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by aurorasmiles** [comment] 2021-03-28 17:06
Is your pickaxe enchanted with Efficiency 5? Because that's required for that afaik

**Comment by Proximyst** [comment] 2021-03-28 17:13
Works great with these on b571:
![](https://owo.whats-th.is/9fmvfNH.png)

Closing as cannot reproduce. You need Efficiency V, for the record.

**Closed as completed by Proximyst** 2021-03-28 17:13 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.16

**Comment by gnat79** [comment] 2021-03-28 18:03
Hmmm, my confidence is slowly eroding. I will go back and try to figure it out. There's nothing special about my install that would make me suspicious, so probably it's operator error. Sorry for the extraneous bug report. I should have started in the forums first I just realized there are some.

**Comment by Proximyst** [comment] 2021-03-28 18:47
A bug report too many is much more welcome than a bug report too few, especially for those things many people would be affected by 😉

**Comment by gnat79** [comment] 2021-03-28 19:37
Thanks for being kind about it :-) For the record, it definitely was operator error. It's all good.
