### ISSUE TITLE
Chunk has both internal and external streams

### ISSUE THREAD

**Issue by LoneDev6** [PaperMC/Paper#2800] opened 2019-12-27 18:03 UTC
### What behaviour is expected:
No error

### What behaviour is observed:
Error spammed:
>.... [18:59:49 ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (75,264), hashcode:511495782, priority: -1, file IO thread has dumped the relevant exception above
>.... [18:59:49 WARN]: java.io.IOException: See logs for further detail
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1059)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.readChunkData(PlayerChunkMap.java:1087)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.getChunkStatusOnDisk(PlayerChunkMap.java:1142)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.asyncSave(PlayerChunkMap.java:477)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$a$11(PlayerChunkMap.java:527)
>.... [18:59:49 WARN]: at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
>.... [18:59:49 WARN]: at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
>.... [18:59:49 WARN]: at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.b(PlayerChunkMap.java:447)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:411)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:533)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:397)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1239)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
>.... [18:59:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
>.... [18:59:49 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [19:01:28 WARN]: Chunk has both internal and external streams
>.... [19:01:28 ERROR]: External chunk path ./world/region/c.91.276.mcc is not file
>.... [19:01:28 WARN]: Chunk has both internal and external streams
>.... [19:01:28 ERROR]: External chunk path ./world/region/c.91.276.mcc is not file

### Steps/models to reproduce:
Unknown

### Plugin list:
Plugins (128): AdvancedAchievements, AdvancedBank*, AdvancedDungeons, AECommunicate, AltDetector, AntiVPN, Aqua, ArmorStandTools, asCMD*, AuthMe, AutoRestarter, AutoServerManager*, BeautyQuests, BlockLocker, BOHA*, BuycraftX, ChatControl, ChatReplay, ChestCommands, ChestSignOpen, ChestSort, Citizens, CitizensCMD, ColoredSigns*, ConsoleSpamFix, CoreProtect, CosmeticItems, Crawling, DeathMessagesPrime, DiamondAnticheat, DiscordServerStatus, DragonSlayer, dynmap, Dynmap-Essentials*, Dynmap-WorldGuard*, EasyBackup, EditableSign, Emotes, EntityDetection, EpicBackpacks, EpicReferrals, EpicRename, Essentials, Essentials_WarpGUI, EssentialsChat, EssentialsSpawn, ExtendViewDistance*, F3Name, FastLogin, Garbage_Collector*, GlowAPI*, GoldenCrates, GreatKits*, GriefPrevention, GriefPreventionStickFix, GuiBack, HeadsPlus, HolographicDisplays, HoneyPopulator, InsaneLore*, InventoryRollback, ItemBox, ItemCommands, ItemsAdder, ItemsAdder-WorldEdit, JDynmapGriefPrevention*, JupiterCore, Karma, LightAPI*, LoneUtil, Market, MarriageMaster, mcMMO, MessageAnnouncer, MultitoolPlus, Multiverse-Core, MyCommand, MyPet, NerfPhantoms, NetherRoofBackFix, NoteBlockAPI, NoteBlockMusicPlayer, NPC_Destinations, NPCDestinations_Animator, OpenInv*, PacketListenerApi*, PermissionsEx*, PexFix, PlaceholderAPI, Plan, PlayerInfo, PlayerParticles, PlayerSelector, PluginConstructorAPI, PlugMan*, PocketMobs, ProtocolLib, PvPToggle, QuickShop, RandomTeleport, RealDualWield*, RequiredPlugins, RPGBank, RPGMoney, SafeTextures, SAML, ServerBooster, ServerInfo, ServerListPlus*, Shopkeepers, SimpleSit*, SkinsRestorer, SmoothSleep, SuperElytra, TAB, TagPlayer, TradePlus, TreeFeller, Vault, VehicleDismountDisabler*, VillagerInfinityTradeFix, VillagerOptimiser, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, X-Mas, Y

### Paper build number:
[19:02:56 INFO]: This server is running Paper version git-Paper-29 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
>.... [19:02:56 INFO]: Checking version, please wait...
>.... [19:02:56 INFO]: Previous version: git-Paper-237 (MC: 1.14.4)
>.... [19:02:56 INFO]: You are 2 version(s) behind

**Comment by electronicboy** [comment] 2019-12-27 18:11
` Chunk has both internal and external streams`
is a non-issue, that's basically the "you have an oversized chunk" from a quick glance, the issue is that apparently your oversized chunk files are missing?

**Comment by LoneDev6** [comment] 2019-12-27 18:12
Exactly what does this means? I mean, wtf, too much data saved in the chunk?

**Comment by electronicboy** [comment] 2019-12-27 18:16
Basically, mojangs fix for the chunk save-state issue is to save data in an external file, actually; reading this, maybe they're saving the oversized chunks entirely in a seperate file, and it's upset that the chunk is inconsistent, failed to save properly? Did you have oversized chunks in 1.14.4? Might be worth testing upgrading a copy of your backup and seeing if that produces the same warnings in those chunks

**Comment by LoneDev6** [comment] 2019-12-27 18:35
Might be the issue, i didn't run --forceUpgrade because when I tried to run it it just failed.
I recently restored my server from a backup made with ServerRestorer plugin and seems this plugin saved chunk files in backup zip in a corrupted way or idk...
I would run RegionFixer but as I read in their Github it will delete corrupted chunk instead of repairing them

**Comment by aikar** [comment] 2020-12-03 03:48
Closing as this was ultimately a corrupt state paper can't do much about, it expected an external file and could not find it.

**Closed as completed by aikar** 2020-12-03 03:48 UTC
Labels: version: 1.15
