### ISSUE TITLE
Latest versions of paper causing major issues for Streamline Hosting Machines

### ISSUE THREAD

**Issue by trickman325** [PaperMC/Paper#4308] opened 2020-09-09 16:22 UTC
Hello,

I am running Paper version 186 1.16.2 and it is causing major issues with my machine.
I am on Streamline servers Hosting dedicated machines.
I contacted them and this was their response:

> Hi Tristan
> 
> It's quite strange that they're saying that when almost all our boxes are having the same issue with Paper itself on the latest builds.
> 
> Some of our customers had to move from Paper back to Spigot as the latter wasn't crashing while the other was.
> 
> Would recommend pursuing this issues a bit more with them as it seems to be an issue with their latest build, all our machines run directly on SSDs (Some of the newest boxes are using NVMEs) and still show this same dump errors.
> 
> Best Regards,
> Ismael M.
> Customer Support Representative

This is the crash dump spam in my console
https://pastebin.com/HNVDQUFh
This is caused when I try to join my server and it crashes my server.
Deleting playerdata completely seems to fix the join crash but after a restart the join crash will occur again.

From very limited testing this seems to be an issue in the range of versions 176 to 186, as i have one server still running 175 and that seems to work just fine.

This issue is also causing a major increase in world spawn loading times. Avg is around 1 minute per world for a 8 chunk load.....
https://pastebin.com/QSYqusj5

**Comment by aikar** [comment] 2020-09-09 17:05
Your issue seems to be that you are on a single core CPU.

though this shouldn't be any severe hold up, it just seems like your cpu is getting really slow.

This isn't anything to do with disk here, this is all about CPU.

Please ask your host to give you 4 cores.

**Comment by aikar** [comment] 2020-09-12 18:11
Ok so something is funky but this would be a duplicate of #4288 so please subscribe to that issue for resolution.

**Closed as completed by aikar** 2020-09-12 18:11 UTC
