### ISSUE TITLE
Time passing at incomprehensible rate.

### ISSUE THREAD

**Issue by Weasel-Beans** [PaperMC/Paper#2360] opened 2019-07-23 01:31 UTC
### What behaviour is expected:
I expect a Minecraft day to last 20 minutes.

### What behaviour is observed:
It went from lasting 20 minutes to lasting maybe 0.2 seconds.

### Steps/models to reproduce:
On my server 'Beanscraft.ca', allow time to pass, as of the last few hours.

### Plugin list:
https://timings.aikar.co/?id=5774b548e807476ea0ca967e5ec6f61e

### Paper build number:
137

### Anything else:
The world is now roughly 131 years old and I haven't figured out a work-around. I did set /gamerule dodaylightcycle to false though, which left it at 0 ticks.

**Comment by Weasel-Beans** [comment] 2019-07-23 03:04
Update: I waited a while and did '/gamerule DoDaylightCycle true' again, and it is now working normally. No idea what caused it, and no idea what solved it.

**Comment by kickash32** [comment] 2019-07-23 03:22
Close the issue if solved. This was most likely caused by a plugin not working properly.

**Comment by Weasel-Beans** [comment] 2019-07-24 02:39
Well the issue appeared again today, and went away after a few hours. My world is at more than 500,000 days now on my public server. I don't think this is a plugin issue, and it's not solved in that sense.

**Closed as completed** 2019-07-24 21:44 UTC
Labels: status: needs testing

**Comment by mikroskeem** [comment] 2019-07-24 22:14
I wonder why did you close this and how you solved the problem. I'm asking this because maybe someone else stumbles upon similar issue and could figure out a solution easier later.

**Comment by CrystallDEV** [comment] 2019-07-24 22:24
I guess what happened here is that the server recovered the missing ticks and therefor it looked like the day only went 0.2 seconds

**Comment by HexedHero** [comment] 2019-07-24 23:22
Exactly what Crystal said above. Does this a lot with some plugins like old MoreVaultsPlus. Freezes the server for 60~ seconds on startup then when u join it speeds up time like 2x the speed to recover the missing ticks
