### ISSUE TITLE
Can't teleport to a bed where the chunks are unloaded

### ISSUE THREAD

**Issue by MCHalfAssed** [PaperMC/Paper#3505] opened 2020-06-05 03:40 UTC
### What behaviour is expected:
Using /home <username>:bed takes me to the bed that the player last set their home at using a bed.

### What behaviour is observed:

If the chunks are not loaded, using /home <username>:bed gives a "Error: Your bed is either unset, missing, or blocked."

If I manually teleport to the bed, and then use the command again, it successfully teleports me to the designated bed with no errors.

### Steps/models to reproduce:
Video of the error;

https://www.youtube.com/watch?v=kUQDnLRrl5M

### Plugin list:
 Plugins (60): AdvancedAchievements, AdvancedNMotd, ajParkour, ArmorStandTools, AsyncWorldEdit, BetterSleeping*, ChargedCreeper*, Citizens, Cloaked, CommandSigns, CoreProtect, CraftBook, DeathMessagesPrime, DiscordSRV, DMPMonitorCompat, DMPWorldGuard, DragonEggDrop, EntityTrackerFixer, Essentials, EssentialsProtect, EssentialsSpawn, GPAccruals*, GriefPrevention, HolographicDisplays, HolographicExtension*, HopperFilter, IllegalStack, ItemEdit, JoinMessagePlus*, LaggRemover, LightAPI*, NametagEdit*, NBTAPI*, OpenInv, PacketLimiter, PermissionsEx*, PlaceholderAPI, PlayerHeads, ProtocolLib, pvparena, PvPManager, PvPToggle, RandomTeleport, SAML, SimplePets, spark, StatisticEditor, StopNetherTrap, SuperTrails*, TAB, TopSurvivor, UltimateKits, VarLight, Vault, VentureChat, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
git-paper-334 (MC 1.15.2) (API R0.1-SNAPSHOT)

### Anything else:
I will also be opening a ticket with essentialsX support to ask them about this error as well

**Comment by aikar** [comment] 2020-06-05 04:08
this sounds like an essentials problem

**Comment by JRoy** [comment] 2020-06-05 04:26
You have an outdated essentials + am unable to reproduce on latest essentials and async pr (https://github.com/EssentialsX/Essentials/pull/3102#issuecomment-636377539)

**Comment by aikar** [comment] 2020-06-05 04:27
per ^ closing

**Closed as completed by aikar** 2020-06-05 04:27 UTC

**Comment by MCHalfAssed** [comment] 2020-06-05 04:39
I have updated to the latest version and I'm still running into this issue exactly the same way as before. Current version now - 

[Fri, 5. Jun 2020 04:37:51 GMT INFO] CONSOLE issued server command: /ess ver
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsX version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] PlaceholderAPI version: 2.10.6
[Fri, 5. Jun 2020 04:37:51 GMT INFO] PermissionsEx version: 1.23.4
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Vault version: 1.7.2-b107
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Citizens version: 2.0.26-SNAPSHOT (build 1979)
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsXProtect version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsXSpawn version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] You are running unsupported plugins!



Would you like me to make another video showing the latest version as proof?

**Comment by MCHalfAssed** [comment] 2020-06-05 04:40
**EDIT - Just saw the  async pr, will be trying that now. Sorry for the trouble.

**Comment by MCHalfAssed** [comment] 2020-06-05 04:55
Alright, I tried both the latest version AND test version;
[Fri, 5. Jun 2020 04:54:59 GMT INFO] CONSOLE issued server command: /ess ver
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsX version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] PlaceholderAPI version: 2.10.6
[Fri, 5. Jun 2020 04:54:59 GMT INFO] PermissionsEx version: 1.23.4
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Vault version: 1.7.2-b107
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Citizens version: 2.0.26-SNAPSHOT (build 1979)
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsXProtect version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsXSpawn version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] You are running unsupported plugins!



Still was having the same issue. Can we re-open this ticket? Or shall I make another?

**Comment by MCHalfAssed** [comment] 2020-06-05 05:00
Question - Do I need to have **both** the latest essentialsX as well as the EssentialsX-Test installed and running? I assume not.

**Comment by MCHalfAssed** [comment] 2020-06-05 05:20
I believe I just now solved it. In my test server, I wasn't having the issue.

So in the real server, I removed the bed. Placed a new one. And now the issue is gone. Not sure exactly what was happening here, but at least it's solved now. Thanks for the support.
