### ISSUE TITLE
A lot of random rollbacks (30 min rollbacks)

### ISSUE THREAD

**Issue by oxycclock** [PaperMC/Paper#1400] opened 2018-09-02 10:15 UTC
**Plugin list:**

[https://image.noelshack.com/fichiers/2018/35/7/1535882319-2018-09-02-11-57-28.png](https://image.noelshack.com/fichiers/2018/35/7/1535882319-2018-09-02-11-57-28.png)
+
[https://www.spigotmc.org/resources/tps-based-render-distance.44485/](https://www.spigotmc.org/resources/tps-based-render-distance.44485/)
Maybe it's this plugin ?

**Actions to reproduce :**

Just play.

**Paper build number:**

paperclip-206.jar

**Description :**

Sometimes, the server does 30-minute rollbacks, and kick players with the "Timeout" error.

it also happens during the reboot

EDIT : THIS BUG IS FROM THE RENDER DISTANCE PLUGIN

**Comment by lululombard** [comment] 2018-09-04 09:29
Guess that can be closed with the `EDIT : THIS BUG IS FROM THE RENDER DISTANCE PLUGIN`

**Comment by Brokkonaut** [comment] 2018-09-04 21:17
That plugin does just player.setViewDistance() and not much more, so i don't think that should be the cause of the bug. maybe the render distance api is broken and causes some chunks not to be saved?

**Comment by aikar** [comment] 2018-09-22 15:46
Since nothing indicates a paper problem and you indicate its related to plugin, closing.

**Closed as completed by aikar** 2018-09-22 15:46 UTC
Labels: resolution: invalid, resolution: incomplete, plugin
