### ISSUE TITLE
Exception loading structure piece with id minecraft:jigsaw (not a map: null)

### ISSUE THREAD

**Issue by mrfloris** [PaperMC/Paper#6004] opened 2021-06-26 08:31 UTC
### Stack trace

```
[21:53:53 ERROR]: Not a map: null
[21:53:53 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-46]
```

### Plugin list

will share when possibly relevant

### Actions to reproduce (if known)

No idea, sorry, I woke up and checked console, saw some people playing and this error. They weren't entering commands, as far as I know they were in the overworld exploring their existing builds.

### Paper version

```
> ver
[10:30:17 INFO]: Checking version, please wait...
[10:30:17 INFO]: This server is running Paper version git-Paper-47 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a23eb53)
You are running the latest version
Previous version: git-Paper-46 (MC: 1.17)
```
I've upgraded 20 minutes ago, it was on "46" not 47 when this happened.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I do not understand the error, it mentions paper, i dont see it reference a plugin. If this wasn't the place to report it then my apologies.

**Comment by Prof-Bloodstone** [comment] 2021-06-26 08:36
Please put minimal effort to check if issue wasn't reported before.
Duplicate of #5988 #5873 #5887 #5972 and probably more. 
Vanilla bug: https://bugs.mojang.com/browse/MC-227945

**Closed as completed by Prof-Bloodstone** 2021-06-26 08:36 UTC
Labels: resolution: duplicate, upstream: vanilla, version: 1.17

**Comment by mrfloris** [comment] 2021-06-26 08:43
More than minimal effort was made, sorry that I didn't find any results. Otherwise I wouldn't have bothered a courtesy report. Glad it's a known issue and sorry for wasting your time.
