### ISSUE TITLE
Villagers wakeup place is wrong

### ISSUE THREAD

**Issue by Noah0505** [PaperMC/Paper#3029] opened 2020-03-14 19:24 UTC
something wrong in paper with villagers waking up on wrong place. It works in spigiot not in paper

### What behaviour is expected:
___What you expected to see___ villager to wake up where the should stand

### What behaviour is observed:
___What you actually saw___ villagers wake up under bed on glass

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___ 
something wrong in paper with villagers waking up on wrong place. It works in spigiot not in paper

### What behaviour is expected:
___What you expected to see___ villager to wake up where the should stand

### What behaviour is observed:
___What you actually saw___ villagers wake up under bed on glass

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___ 
https://youtu.be/D-IJM0JW8bY.
https://drive.google.com/drive/folders/1VQ_7x6hg9E449HhlidPkpwh9GJaHYVtO?usp=sharing

### Plugin list:
___A list of your plugins___ in video

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___ 135

### Anything else:
___Anything else you think may help us resolve the problem___    I included a video and a world download. iron farm cordinates to it is ca -1111 70 2200. the server dosent work on paper but dose on spigiot craftbukit

**Comment by electronicboy** [comment] 2020-03-14 19:25
Duplicate of #3009

**Closed as completed by electronicboy** 2020-03-14 19:25 UTC
