### ISSUE TITLE
Exception stopping the server

### ISSUE THREAD

**Issue by xKsyStudio** [PaperMC/Paper#6447] opened 2021-08-20 16:47 UTC
### Expected behavior

这是在我关闭服务器时弹出的

### Observed/Actual behavior

[23:48:28 ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669) ~[patched_1.17.1.jar:git-Paper-196]
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:755) ~[patched_1.17.1.jar:git-Paper-196]
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$FastEntryIterator.next(Long2ObjectOpenHashMap.java:751) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.h(PersistentEntitySectionManager.java:285) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.c(PersistentEntitySectionManager.java:308) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.close(PersistentEntitySectionManager.java:325) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.level.WorldServer.close(WorldServer.java:2067) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:992) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:806) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1238) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Steps/models to reproduce

偶尔出现

### Plugin list

我一个写插件的朋友说可能是paper的bug

### Paper version

paper-1.17.1-196.jar

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by NoahvdAa** [comment] 2021-08-20 16:49
Duplicate of #6438.

**Comment by electronicboy** [comment] 2021-08-20 16:50
Duplicate of #6438
Please note that this is an English community and we ask that people actually fill in the template fully rather than deciding that information is irrelevant themselves

**Closed as completed by electronicboy** 2021-08-20 16:50 UTC
