### ISSUE TITLE
paper issues when raising world height limit

### ISSUE THREAD

**Issue by ChunkyPanda03** [PaperMC/Paper#6429] opened 2021-08-18 21:09 UTC
### Expected behavior

When using a data pack to change the world height cap to 512 users should be able to build up to 511 (capping at 512) as well as logging back into the spot that they left off including the y level they left off like in spigot bukkit and vanilla

### Observed/Actual behavior

when raising the build height of the a server to 512 but join height always defaults to under y=300 if player left while over y=300 blocks they are teleported to y=256 from their current location

### Steps/models to reproduce

watch video https://youtu.be/4oshi2Ebus4 and here is the data pack for your refrence
[512data.zip](https://github.com/PaperMC/Paper/files/7010172/512data.zip)

### Plugin list

none

### Paper version

git-Paper-196 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 59d449d)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

this works fine on spigot, Bukkit, and vanilla with no problems

**Comment by electronicboy** [comment] 2021-08-18 21:09
Duplicate of #6357

**Closed as completed by electronicboy** 2021-08-18 21:09 UTC
Labels: version: 1.17
