### ISSUE TITLE
KeepAlive is disconnecting clients when downloading the server resource pack.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#921] opened 2017-10-18 13:56 UTC
Paper dev 1244
Waterfall dev 152

I have a user who continues to get kicked by the keepalive timeout. Kicked 5 times thus far - every time he tries to connect.

Not sure exactly why he keeps getting kicked but I can only take a random guess that he is being kicked if stuck downloading the server resource pack for more than 30 seconds due to a slow connection. Assuming that the client stops sending packets while it downloads the resource pack. 

Asking around recently, it seems to happen with a few other players as well. Them timing out when trying to update the server resource pack.

**Comment by electronicboy** [comment] 2017-10-18 14:01
duplicate of #895

**Closed as completed by electronicboy** 2017-10-18 14:01 UTC
