### ISSUE TITLE
Dragon egg despawnes on entering portal

### ISSUE THREAD

**Issue by spnda** [PaperMC/Paper#5153] opened 2021-02-02 18:43 UTC
### What behaviour is expected:
In vanilla minecraft and on a vanilla minecraft server, placing the dragon egg above the end portal makes it drop through and just "be there" on the other side (the end spawn).
It should be in the end like this: (screenshot from world running on internal server)
![](https://cdn.discordapp.com/attachments/442748131898032138/806232287364513852/unknown.png)

### What behaviour is observed:
On Paper (and seems to be on Spigot too), the dragon egg does not appear on the other side (the end spawn). However, sometimes if pushed into the side by piston/slime block it does spawn on the other side.

### Steps/models to reproduce:
Using this build, the egg does not spawn on the other side.
![](https://cdn.discordapp.com/attachments/442748131898032138/806231733371797544/unknown.png)

### Plugin list:
Happens with no plugins on the server.
Though I noticed this first with:
BlockProt, Harbor, IPUpdater, LuckPerms, NBTAPI, ServerRestart, SpigotPing, SPlugin
(Note: IPUpdater and SPlugin are both custom plugins by me, they both shouldnt interfere with anything regarding this)

### Paper version:
git-Paper-457 (MC: 1.16.5) (API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Trigary** [comment] 2021-02-02 18:45
Is this a duplicate of https://github.com/PaperMC/Paper/issues/3344?

**Comment by spnda** [comment] 2021-02-02 19:05
Possibly. 
Though letting 10 dragon eggs and or 10 sand fall through none of them drop on my server, unlike it is described in #3344.
Items show up on the other side though.

**Comment by Trigary** [comment] 2021-02-07 01:07
I'm confident these two issues refer to the same bug. In order to avoid having to keep both issues up to date, could you please close this one and add all missing information to the other one instead?

**Comment by Chew** [comment] 2021-02-07 01:51
> Items show up on the other side though.

Do all the items show up? The main issue was a few weren't.

**Closed as completed** 2021-02-07 02:24 UTC
Labels: type: bug, version: 1.16
