### ISSUE TITLE
Endermen passive towards endermites

### ISSUE THREAD

**Issue by AaronUltima** [PaperMC/Paper#5842] opened 2021-06-15 14:05 UTC
### Expected behavior

Endermen are hostile towards endermites, they will attack them as soon as they appear within 64 blocks.

### Observed/Actual behavior

Endermen don't attack endermites,behave completely passive,none hostile. There is no difference if the endermites has been spawned in creative or survival. Or by any other player then a admin. 

### Steps/models to reproduce

Basecly we are using a enderman farm created for 1.16. But it can be reproduced by putting a endermite into a minecard but not allowing it to be killed by the endermen. Alternately spawning enterites will cause endermen to act hostile towards them. 

### Plugin list

15.06 15:53:36 [Server] INFO Plugins (25): AntiWorldFly, BanManager, BetterRTP, CoreProtect, CratesPlus, DiamondHunter*, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, LWC, MVdWPlaceholderAPI*, PlaceholderAPI, ProtocolLib, Rankup, Statz, TAB, TradeShop, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, XPFlyX*

### Paper version

15.06 15:53:10 [Server] INFO This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
15.06 15:53:10 [Server] INFO You are running the latest version
15.06 15:53:10 [Server] INFO Previous version: git-Paper-775 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment] 2021-06-15 14:12
This needs reproduction on 1.17 once ready. Master is currently frozen.

**Comment by AxlRose-RX** [comment] 2021-06-15 14:36
I had that issue on my 1.16.5 server, is just your configs files, something like nerf-spawner-mobs on spigot.yml your farms enderman have no AI, also the ender mite is different depending on how you call them. If you get them with command they are dump and they don't get attacked, if you call with with an egg spawn they do get attacked by enderman.

**Comment by Levii22** [comment] 2021-06-15 15:37
> also the ender mite is different depending on how you call them. If you get them with command they are dump and they don't get attacked, if you call with with an egg spawn they do get attacked by enderman.

That's correct, I tested it on 1.16.5. Enderman will attack endermite if it was spawned by throwing ender pearls only or if you give "PlayerSpawned:1b" tag. However, it's fixed in 1.17 as far as I remember.

**Comment by AaronUltima** [comment] 2021-06-15 17:31
I have not touched the config file in ages. It happened when I was using the farm and for some reason my game froze. When I logged back the original ender mite,that was created in 1.16 was gone. I spawned a new one with a spawn egg but it seemed not to make endermen agro. So I tried to get one using enderpearls. For 20 sec endermen became hostile and then it stopped again. Other players,that are in default rank tried to spawn ender mites the same way and the endermen would get aggravated for 20 sec and then stop again or they would be none hostile.  If it is fixed for 1.17 then it's not a major issue. Since im upgrading the server with the current map to Paper 1.17

**Comment by Brokkonaut** [comment] 2021-06-15 22:12
This is not a bug, but a mojang feature. https://minecraft.fandom.com/wiki/Endermite#Behavior

**Comment by Chew** [comment] 2021-06-15 22:31
That and it looks like 1.17 will "resolve" this anyway so there's no reason to keep this open. Thank you for the report and thank you for your patience ❤️

**Closed as completed by Chew** 2021-06-15 22:31 UTC
Labels: type: bug, status: needs testing, version: 1.16

**Comment by AxlRose-RX** [comment] 2021-07-01 04:51
This has been fixed on recent version, and the right command that works and make it invincible on Enderman farms is:

/summon minecraft:endermite ~ ~ ~ {CustomName:"\"SuperMite\"",CustomNameVisible:1,PersistenceRequired:1,ActiveEffects:[{Id:11,Amplifier:5,Duration:10000000}]}
