### ISSUE TITLE
CRASH - EntityDamageEvent (To Player) - Soul Camp Fire

### ISSUE THREAD

**Issue by ItsMeMagni** [PaperMC/Paper#6354] opened 2021-08-07 09:36 UTC
### Stack trace

-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1013)
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:942)
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1132)
	at app//net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042)
	at app//net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1013)
	at app//net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350)
	at app//net.minecraft.world.entity.player.Player.hurt(Player.java:920)
	at app//net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998)
	at app//net.minecraft.world.level.block.CampfireBlock.entityInside(CampfireBlock.java:97)
	at app//net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:904)

-- Block being collided with --
Details:
	Block: Block{minecraft:soul_campfire}[facing=south,lit=true,signal_fire=false,waterlogged=false]
	Block location: World: (-1445,64,13358), Section: (at 11,0,14 in -91,4,834; chunk contains blocks -1456,0,13344 to -1441,255,13359), Region: (-3,26; contains chunks -96,832 to -65,863, blocks -1536,0,13312 to -1025,255,13823)
Stacktrace:
	at app//net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1226)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.EntityPlayer)
	Entity ID: 901
	Entity Name: DiscobikThatsMe
	Entity's Exact location: -1444.28, 64.99, 13358.66
	Entity's Block location: World: (-1445,64,13358), Section: (at 11,0,14 in -91,4,834; chunk contains blocks -1456,0,13344 to -1441,255,13359), Region: (-3,26; contains chunks -96,832 to -65,863, blocks -1536,0,13312 to -1025,255,13823)
	Entity's Momentum: 0.00, -0.01, -0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at app//net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:975)
	at app//net.minecraft.world.entity.Entity.move(Entity.java:948)
	at app//net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2778)
	at app//net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2733)
	at app//net.minecraft.world.entity.player.Player.travel(Player.java:1592)
	at app//net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3195)
	at app//net.minecraft.world.entity.player.Player.aiStep(Player.java:549)
	at app//net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2881)
	at app//net.minecraft.world.entity.player.Player.tick(Player.java:270)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.EntityPlayer)
	Entity ID: 901
	Entity Name: DiscobikThatsMe
	Entity's Exact location: -1444.28, 64.99, 13358.66
	Entity's Block location: World: (-1445,64,13358), Section: (at 11,0,14 in -91,4,834; chunk contains blocks -1456,0,13344 to -1441,255,13359), Region: (-3,26; contains chunks -96,832 to -65,863, blocks -1536,0,13312 to -1025,255,13823)
	Entity's Momentum: 0.00, -0.01, -0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at app//net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:672)
	at app//net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:609)
	at app//net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:591)
	at app//net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1875)
	at app//net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1855)
	at app//net.minecraft.network.Connection.handleDisconnection(Connection.java:564)
	at app//net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:216)
	at app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578)
	at app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)
	at app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
	at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:831)

### Plugin list

Automessage, Buycraftx, Citizens, CMILib, CommandSigns, DeathMessages, DiscordSRV, dynmap, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, Factions, FeatherBoard, floodgate, Geyser-Spigot, HackedCore, HackedServer, LuckPerms, Magnisplugin, MarriageMaster, Matrix, MobFarmManager, Multivers-Core, MVdWPlaceholderAPI, OpenInv, PlaceholderAPI, PlayerParticles, PlayerShopGUIPlus, PlayerWarps, ProtocolLib, ServerlistMOTD, ShopGUIPlus, TitleManager, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags.

### Actions to reproduce (if known)

![image](https://user-images.githubusercontent.com/88578409/128595863-0294a6ee-aef7-431f-a775-75297399751a.png)
The player would walk down the flowing water and over the soul campfire and onto the slab. Somewhere in this, the player has taken damage from the fire and the server would crash instantly.

### Paper version

git-Paper-165 (MC:1.17,1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git:f261419)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment] 2021-08-07 10:08
This looks like a duplicate of #6351 which was fixed in build 164.
You claim to be using build 165 on which I'm unable to reproduce the issue.
Could you upload your WHOLE crash report to site like https://paste.gg/

**Comment by Prof-Bloodstone** [comment] 2021-08-07 10:14
Actually, your stacktrace doesn't align with with code for the version you provided, but does match version 163. Please don't lie on the issue tracker and waste our time.

**Closed as completed by Prof-Bloodstone** 2021-08-07 10:14 UTC
Labels: type: bug, resolution: duplicate, version: 1.17

**Comment by ItsMeMagni** [comment] 2021-08-07 11:53
Gee wow, wasnt trying to lie or waste anyone's time. genuinely wanted this issue fixed for obvious reasons. but aye, if the stacktrace doesn't align then fuck me aye.

**Comment by Prof-Bloodstone** [comment] 2021-08-07 12:02
Perhaps you have dum auto-updater, so the server crashed, automatically updated on restart and thus the discrepancy?
That's why we need all of the crash log.
