### ISSUE TITLE
Spawn chunks not loaded when starting server

### ISSUE THREAD

**Issue by Combustible** [PaperMC/Paper#1866] opened 2019-02-21 15:29 UTC
### What behaviour is expected:
Paper should be automatically loading the spawn chunks at world startup - but instead it is only keeping those chunks loaded once they are visited for the first time. 

I am really surprised I can't find an issue for this already. This is a fairly major problem - many servers use the spawn chunks for always-loaded command block mechanisms. There is nothing in my server startup log like there used to be for "Loading world". 

### Steps/models to reproduce:
Settings in paper.yml: 
```
keep-spawn-loaded: true
keep-spawn-loaded-range: 16
```

- Create a world and set the world spawnpoint to a known point
- Restart the paper server and do **not** log in
- From the console, run:
```
execute if block <spawn coords> air
```
This will print "That position is not loaded" 

### Paper build number:
Paper build based on latest commit as of this bug report - 825191f069

**Comment by aikar** [comment] 2019-02-21 18:17
Confirmed, they do get loaded, just code to unload unneeded chunks isnt checking if its a spawn chunk. will fix soon

**Comment by aikar** [comment] 2019-02-22 05:04
Oh... woops. Looks like the code DOES check that, but the code to generate the spiral outwards to calculate chunks to load had a flaw and was loading block coordinates for chunks, so it was loading the WRONG chunks for spawn.

Fixed in build 527+

**Closed as completed by aikar** 2019-02-22 05:03 UTC
Labels: type: bug, status: accepted

**Comment by Combustible** [comment] 2019-02-22 17:28
Thank you! 

Edit: Tested and fix works as advertised 👍
