### ISSUE TITLE
Invisible Players

### ISSUE THREAD

**Issue by Rev-Zareh** [PaperMC/Paper#4306] opened 2020-09-09 00:45 UTC
### What behaviour is expected:
You can see and interact with other players on the server.

### What behaviour is observed:
Unable to see other players, but still can see their actions, i.e. blocks breaking...

### Steps/models to reproduce:
Log into server...

### Plugin list:
Currently only Bungeecord and Paper 186

### Paper version:
Paper #186 Minecraft 1.16.2

### Anything else:
New server was just setup today. Have tried to log out and back in. Restarted Bungee and Paper server. Had other player log out and back in completely. Still not working.

**Comment by Chew** [comment] 2020-09-09 03:31
Duplicate of https://github.com/SpigotMC/BungeeCord/issues/2942

**Closed as completed by Chew** 2020-09-09 03:31 UTC

**Comment by Rev-Zareh** [comment] 2020-09-09 04:12
I believe I resolved the issue on my end. Tested with several players and it works.

Really a rookie mistake. The first thing I changed was in the bukkit.yml for each server and changed the connection-throttle from 4000 to -1

The next thing I noticed was I needed to go into the spigot.yml for each server and change bungeecord from "False" to "True".

Everything is working as it should be.

**Comment by Chew** [comment] 2020-09-09 04:26
Good suggestions, this might be the root cause, as well as ip-forwarding true in bungee config.
