### ISSUE TITLE
Crash chunk : Feature placement

### ISSUE THREAD

**Issue by Euphillya** [PaperMC/Paper#6217] opened 2021-07-17 20:41 UTC
### Stack trace

```
https://paste.gg/p/anonymous/ae7c5450e53a40ad8098b260cd57fd3f
```

### Plugin list

[22:40:18 INFO]: Plugins (51): AuctionMaster, AuctionMasterItemDisplay, AutoRestart*, BanklandsGradle, BuycraftX, Chunky, Citizens, CitizensCMD, CMI, CMIEInjector*, CMILib, CrateReloaded, CrateReloadedNPC*, DiscordSRV, DynamicShop, EasyBackup, EasyBackupCore, HolographicDisplays, Images, Insights, Jobs, JobsPlusEvolved, Lands, LandsDiscordBot, LiteBans, LocketteX, LuckPerms, MarriageMaster, MCRealistic-2, MinewebBridge, NoFurnace, OpenInv, Oraxen, Pl3xMap, Pl3xmap-WorldGuard, PlaceholderAPI, ProtocolLib, PunishGUI*, Quests, QuestsGUI, QuickShop, Rafk, Shopkeepers, SlotMachine, spark, TAB, TradePlus, Vault, ViewDistanceTweaks, WorldEdit, WorldGuard

### Actions to reproduce (if known)

Generate World with chunky and new map

### Paper version

[22:40:41 INFO]: Checking version, please wait...
>.... [22:40:41 INFO]: This server is running Paper version git-Paper-111 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8f94951)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I use Datapack : 
There are 5 data packs enabled: [vanilla (built-in)], [file/CavesAndCliffsPreview.zip (world)], [file/Incendium_v3.3.1-PAPER.zip (world)], [file/Terralith_Alpha_v0.2.4a.zip (world)], [file/bukkit (world)]
>.... [22:41:20 INFO]: There are no more data packs available

**Comment by electronicboy** [comment] 2021-07-17 20:44
Duplicate of #6028

**Closed as completed by electronicboy** 2021-07-17 20:44 UTC
