### ISSUE TITLE
Lag spikes when entering specific chunks

### ISSUE THREAD

**Issue by Andrew16900** [PaperMC/Paper#4595] opened 2020-10-01 05:19 UTC
### What behaviour is expected:
When entering any chunk, for it not to lag me to 0 fps for several seconds.

### What behaviour is observed:
When passing from z96 to z95 in any x coord and entering the chunk as seen from f3 + G it drops my frame to 0 for severals seconds. This also happens somewhere in the negative z entering a chunk from z-100 to z-99(coordinates not accurate) it also happens but for a very short time.

### Steps/models to reproduce:
Go to z1000 or more and go in a straigth line to z-1000 then back in a server and see if it lags. This didnt happen on the very first days of the server so it might be better to play for a week then test.

### Plugin list:
Standalone PaperMC

### Paper version:
git-Paper-208

### Anything else:
Getting rid of paper to see if it wasnt it fault fixed the problem. And when putting paper back the problem reappeared

**Comment by electronicboy** [comment] 2020-10-01 05:22
Known vanilla issue
Duplicate of #3468

**Closed as completed by electronicboy** 2020-10-01 05:22 UTC
Labels: resolution: duplicate
