### ISSUE TITLE
Problem in console

### ISSUE THREAD

**Issue by Platinuim** [PaperMC/Paper#1839] opened 2019-02-05 21:26 UTC
[BUG CONSOLE 050219.txt](https://github.com/PaperMC/Paper/files/2833926/BUG.CONSOLE.050219.txt)

### What behaviour is expected:
___/___

### What behaviour is observed:
___I saw nothing, it was another player who make this error in the console___

### Steps/models to reproduce:
___/___

### Plugin list:
___AUpdater, betterSleeping, bStats, DependencyDownloader, dynmap, Essentials, ExplosionDisabler, NoPlugins, Plan, TAB, WorldEdit, WorldGuard___

### Paper build number:
___This server is running Paper version git-Paper-511 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)___

### Anything else:
___/___

**Comment by MiniDigger** [comment] 2019-02-06 08:44
> EntityTippedArrow['Arrow'/2787246, uuid='4dad0f2a-77df-4a1e-b17e-07e6c7dabcb9', l='world', x=5.50, y=48.04, z=-15.64, cx=0, cz=-1, tl=2, v=false, d=false] is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1302

duplicate of #1302

**Closed as completed** 2019-02-06 15:08 UTC
Labels: resolution: duplicate
