### ISSUE TITLE
[1.16.1-1.16.2] Crash cartographer villager (trading)

### ISSUE THREAD

**Issue by WIBOR2002222** [PaperMC/Paper#4228] opened 2020-08-27 17:22 UTC
Image of console message during the crash :

https://ibb.co/KxgZct1

Xxplanation:

The carthographer villager always crashes my server. There are also other people who have the same problem. It seems to me that it comes from Mojang (for information, I use the plugin EpicWorldGenerator).

How do I crash the server?

A player must trade with a carthographer villager and he must just trade emeralds for maps. There is also the crash by trading for the map of the oceans. This can come from a bug with the maps?

**Comment by electronicboy** [comment] 2020-08-27 17:23
1) Don't screenshot logs.
2) Duplicate of #2312

**Closed as completed by electronicboy** 2020-08-27 17:23 UTC
Labels: resolution: duplicate
