### ISSUE TITLE
1.17.1 Support

### ISSUE THREAD

**Issue by KyeOnDiscord** [PaperMC/Paper#6101] opened 2021-07-07 03:36 UTC
### Is your feature request related to a problem?

Mojang recently released 1.17.1 so it would be nice to have this version on paper.
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-17-1

### Describe the solution you'd like.

It would be good to support 1.17.1

### Describe alternatives you've considered.

Using 1.17 is fine but this is a little request that would be nice

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by jpenilla** [comment] 2021-07-07 03:37
duplicate of https://github.com/PaperMC/Paper/issues/6095 (We know 1.17.1 exists, it is being worked on, there is no ETA.)

**Closed as completed by jpenilla** 2021-07-07 03:37 UTC

**Comment by Chew** [comment] 2021-07-07 03:53
We also have a PR open for this... #6097 though I suppose we only suggest you look for open "issues" so you get a slide _this time_.
