### ISSUE TITLE
Extra Health Not Shown/Saved/Updated on join.

### ISSUE THREAD

**Issue by Rodehaas** [PaperMC/Paper#5195] opened 2021-02-16 19:17 UTC
### What behaviour is expected:
Originally you have 10 hearts, i have a plugin that allows me to upgrade it to 20 hearts, so if i rejoin im expected to see 20 full hearts, not 10 empty and 10 full ones

### What behaviour is observed:
when i apply the effect I see 20 hearts, and 20 are full, when i reconnect however  only 10 are full. even with regeneration it wont go above 10 hearts unless i upgrade the skill or take damage, if i do take damage however, its instantly updated to 20 hearts.

### Steps/models to reproduce:
Get health boost (to full health), leave and rejoin the server.

### Plugin list:
PlayerskillsReloaded

### Paper version:
[20:06:40 INFO]: This server is running Paper version git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[20:06:40 INFO]: Checking version, please wait...
[20:06:40 INFO]: Previous version: git-Paper-466 (MC: 1.16.5)
[20:06:40 INFO]: You are running the latest version

### Anything else:
Its not a plugin issue, might be a minecraft issue. since the same bug occurs when i remove the plugin and apply health boost.
![image](https://user-images.githubusercontent.com/39066912/108110709-f356fd80-7093-11eb-952f-bd514f34dcae.png)
![image](https://user-images.githubusercontent.com/39066912/108110725-f81bb180-7093-11eb-86fb-8fbf06cac700.png)
![image](https://user-images.githubusercontent.com/39066912/108110742-ffdb5600-7093-11eb-9dde-94052e4ce983.png)
![image](https://user-images.githubusercontent.com/39066912/108110762-04a00a00-7094-11eb-8ac5-6a67acb39c84.png)

**Comment by Proximyst** [comment] 2021-02-16 19:23
Duplicate of #4793

**Closed as completed by Proximyst** 2021-02-16 19:23 UTC
Labels: version: 1.16

**Comment by Rodehaas** [comment] 2021-02-16 19:27
> Duplicate of #4793

Sorry, didnt notice.
