### ISSUE TITLE
paper remap has bug

### ISSUE THREAD

**Issue by Neige7** [PaperMC/Paper#11529] opened 2024-10-28 15:19 UTC
### Expected behavior

before paper remap:
![Image](https://github.com/user-attachments/assets/bd41a814-aacf-4080-8add-23fe86bbb283)

### Observed/Actual behavior

after paper remap:
![Image](https://github.com/user-attachments/assets/3bd4c6de-8625-4ee6-97fe-65b7e128b799)
![Image](https://github.com/user-attachments/assets/d67c4a2a-35e4-428e-ab1b-afd76609792f)

### Steps/models to reproduce

((CraftWorld) world).getHandle().getChunkSource().chunkMap

.chunkMap will be destroyed by paper

### Plugin and Datapack List

> plugins
[23:17:07 INFO]: Server Plugins (1):
[23:17:07 INFO]: Bukkit Plugins:
[23:17:07 INFO]:  - NeigeItems

### Paper version

1.21.1-128

**Comment by electronicboy** [comment] 2024-10-28 15:23
From my understanding this is an issue with the mappings caused by spigots names conflicting with mojangs names in a weird manner

**Comment by Neige7** [comment] 2024-10-28 15:25
> From my understanding this is an issue with the mappings caused by spigots names conflicting with mojangs names in a weird manner

obviously, but i don't know how to fix it, so i open a issue, instead of pr

**Comment by lynxplay** [comment] 2024-10-28 15:31
I am confused how you are running into this bug tho?
This is a known issue when remapping reflective calls, but your "pre remapped" jar is mojang mapped?
Specify that your plugin is mojang mapped and just skip the remapper instead.

**Comment by Neige7** [comment] 2024-10-28 16:04
> I am confused how you are running into this bug tho? This is a known issue when remapping reflective calls, but your "pre remapped" jar is mojang mapped? Specify that your plugin is mojang mapped and just skip the remapper instead.

I use paperweight

**Comment by lynxplay** [comment] 2024-10-28 16:05
See https://docs.papermc.io/paper/dev/userdev#compiling-to-mojang-mappings

**Comment by Neige7** [comment] 2024-10-28 16:13
> See https://docs.papermc.io/paper/dev/userdev#compiling-to-mojang-mappings

I already configure like that

**Comment by Neige7** [comment] 2024-10-29 02:26
> If you are, the jar would not be remapped. Seems more like you are not using paperweight correctly.

because I haven't use "dependsOn(tasks.reobfJar)"

**Comment by lynxplay** [comment] 2024-10-29 11:16
Is that repository public?
If those paperweight usages are in a submodule you need to also respect their manifest files when shading them in.
I'll close this issue as this is just a configuration issue given the remapper would not even remap your jar if you correctly marked it.
The deeper issue of our mapping logic getting tripped up when spigot and mojang mappings collide is known, but only applies to reflective access.

If you need more help with configuring your project to correctly define the mojang namespace in the manifest file, check by our discord.

**Closed as not planned by lynxplay** 2024-10-29 11:16 UTC
Labels: type: bug, resolution: awaiting response

**Comment by Neige7** [comment] 2024-10-29 11:21
> Is that repository public? If those paperweight usages are in a submodule you need to also respect their manifest files when shading them in. I'll close this issue as this is just a configuration issue given the remapper would not even remap your jar if you correctly marked it. The deeper issue of our mapping logic getting tripped up when spigot and mojang mappings collide is known, but only applies to reflective access.
> 
> If you need more help with configuring your project to correctly define the mojang namespace in the manifest file, check by our discord.

Yes, this repository is public: https://github.com/ankhorg/NeigeItems-Kotlin
The submodule ":hooker:nms:v1_21+" uses paperweight.
I resolved this issue in a somewhat unconventional way.
