### ISSUE TITLE
Datapack loading on server startup issue

### ISSUE THREAD

**Issue by H4kt** [PaperMC/Paper#3722] opened 2020-06-30 15:18 UTC
### What behaviour is expected:
Datapack should load as normal

### What behaviour is observed:
Stacktraces provided below (they differ from time to time)
```
[17:11:53 ERROR]: Failed to load function bc_rewards:biomes/theres_a_zombie_on_the_lawn
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandExecute.b(SourceFile:123) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-27]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_251]
        ... 3 more
[17:11:53 ERROR]: Failed to load function bc_rewards:animal/sticky_situation
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandTellRaw.a(SourceFile:21) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-27]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_251]
        ... 3 more
[17:11:53 ERROR]: Failed to load function bc_rewards:mining/gold_mine
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandGive.a(SourceFile:30) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-27]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_251]
        ... 3 more
[17:11:53 ERROR]: Failed to load function bc_rewards:adventure/i_am_loot
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandExecute.b(SourceFile:123) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-27]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_251]
        ... 3 more
[17:11:53 ERROR]: Failed to load function bc_rewards:challenges/zombie_apocalypse
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CommandExecute.b(SourceFile:123) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-27]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-27]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_251]
        ... 3 more
```

### Steps/models to reproduce:
Install a datapack (in my case blazeandcave advancements) [link](https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-1-12/)
Load up the server

**Note:** if you disable and re-enable the datapack using /datapack command everything will work as expected

### Plugin list:
None

### Paper build number:
git-Paper-27 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
The problem seems to appear **only** in **Linux** environment

**Comment by burturt** [comment] 2020-07-01 05:56
I have this same issue, though whether or not the error is thrown seems 100% random. One time I start up the server and it errors about one thing, the next time it doesn't error at all, then again it'll error about 3-4 different datapacks on consecutive restarts. Seems like spigot closed it as invalid https://hub.spigotmc.org/jira/browse/SPIGOT-5873. From my experience, running /minecraft:reload fixes the datapacks *most of the time* (this is also run when disabling/enabling datapacks). MacOSX 10.14.6 java 8 + 11.

**Comment by keco185** [comment] 2020-07-02 05:02
Yeah experienced the same with all my datapacks. running /minecraft:reload got them working again. A bit of a weird issue. I'm running inside oracle's JDK 11 docker container on a linux host.

**Comment by burturt** [comment] 2020-07-02 05:11
I've had a couple instances where it continued to error after one /minecraft:reload. It does appear though that once it has fixed itself with /minecraft:reload, it will not error out again until the next server restart.

**Comment by Zorean** [comment] 2020-07-06 20:38
I am also getting the same error message I have tried this on windows and Linux. The datapacks seems to be working fine using the plain Minecraft server 1.16.1.
After the server reboots I have to do /reload in order to work. I am currently using these 2 datapacks below.

https://www.planetminecraft.com/data-pack/timber-datapack/
https://www.planetminecraft.com/data-pack/ore-from-bees/

If you want I can upload the error looks.

**Comment by MissPotato** [comment] 2020-07-07 21:10
I too am getting this, while a "/minecraft:reload" does seem to solve the issue, I'm not certain what is causing it.

**Comment by Machine-Maker** [comment] 2020-07-07 23:59
@H4kt I cannot replicate that issue with the datapack you provided (BAC advancements one). I am on the latest paper build (79), I generated the world, put the datapack in the datapacks folder of `world` and the ran `datapack enable <pack>`. Didn't get any errors there, and when I stoped/started the server again, I also didn't get any errors.

**Comment by MissPotato** [comment] 2020-07-08 17:31
It seems random when a pack errors on launch, the more datapacks the more likely the error.

**Comment by iDutch** [comment] 2020-07-08 17:59
I have the same issue with the VanillaTweaks datapacks on my server. Ex. Armour Statues v2.7.1 and Wandering Trades v1.2.1. Errors are random each reboot and sometimes there are no errors at all. Now I only run the Dragon Drops and Multiplayer Sleep datapacks and that seems to be working just fine.

**Comment by H4kt** [comment] 2020-07-09 11:12
@Machine-Maker in my case it does not seems to occur on my machine (win 10), but it does every time on the one that runs Debian.

**Comment by H4kt** [comment] 2020-07-10 14:14
Tested it once again on the latest build of paper (86)
Here is the log from my machine (win 10): [latest.log](https://pastebin.com/hmf1UnCQ) **everything seems to be just fine**
And here is the one from a dedicated server (Debian): [latest.log](https://pastebin.com/Q37aJ217) **keeps erroring even on a newly created world**

**Comment by iDutch** [comment] 2020-07-10 23:39
@H4kt Yup same here, I can reproduce the same issue on a newly created world. Also running on Debian.


```[01:37:57 ERROR]: Failed to load function as:help/credits
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandTellRaw.a(SourceFile:21) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-86]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        ... 3 more
[01:37:57 ERROR]: Failed to load function as:trigger/mirror
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandData.a(SourceFile:59) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-86]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        ... 3 more
[01:37:57 ERROR]: Failed to load function as:trigger/flip
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandExecute.b(SourceFile:123) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-86]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        ... 3 more
[01:37:57 ERROR]: Failed to load function as:trigger/pointing_small
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:147) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CommandData.a(SourceFile:59) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[patched_1.16.1.jar:git-Paper-86]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunction.a(CustomFunction.java:61) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.CustomFunctionManager.a(SourceFile:84) ~[patched_1.16.1.jar:git-Paper-86]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        ... 3 more
[01:37:58 INFO]: Starting minecraft server version 1.16.1
[01:37:58 INFO]: Loading properties
[01:37:58 INFO]: This server is running Paper version git-Paper-86 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

**Comment by aikar** [comment] 2020-07-11 08:01
sorry took so long to fix this, but build 88+ will be fixed.

**Closed as completed** 2020-07-11 08:00 UTC
Labels: version: 1.16

**Comment by MissPotato** [comment] 2020-07-11 16:52
Thank you Aikar!
