### ISSUE TITLE
Slimefun cause server freeze on the newer builds

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3958] opened 2020-07-19 20:18 UTC
### What behaviour is expected:
___What you expected to see___
Slimefun no cause server freeze on the newer builds.
On the build 86 never caused this plugin server freeze.

### What behaviour is observed:
___What you actually saw___
Slimefun cause server freeze on the newer builds

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Use the Slimefun plugin on the medium server.

### Plugin list:
___A list of your plugins___
Plugins (107): AdminVedelem, antiRedstoneClock, ArmorStandEditor, BetterGUI, BungeeHelpop, BuntetesLogolo, ChatControl, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, CSGO-CratesPlus, DisablePistonFarming, Duels, DyedBackpacks, EnderContainers, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Jatekido, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaBot, PomaDrops, PotionArmors, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, Shopkeepers, SignEdit, SkinsRestorer, sleep-most*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, SpleefPlusPlus, StaffChat, StaffTime, SzulinapiKalapok, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-99 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
```
[19:29:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-99 (MC: 1.16.1) ---
[19:29:51] [Paper Watchdog Thread/ERROR]: The server has not responded for 25 seconds! Creating thread dump
[19:29:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[19:29:51] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[19:29:51] [Paper Watchdog Thread/ERROR]: 143,-125 in 'world2:
[19:29:51] [Paper Watchdog Thread/ERROR]: Load Task - none
[19:29:51] [Paper Watchdog Thread/ERROR]: Save Task - none
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[19:29:51] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[19:29:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[19:29:51] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[19:29:51] [Paper Watchdog Thread/ERROR]: 	PID: 42 | Suspended: false | Native: false | State: TIMED_WAITING
[19:29:51] [Paper Watchdog Thread/ERROR]: 	Stack:
[19:29:51] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:391)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IWorldReader.getChunkAt(IWorldReader.java:100)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:332)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.World.getType(World.java:718)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.block.CraftBlock.getType(CraftBlock.java:210)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		io.github.thebusybiscuit.slimefun4.api.network.Network.lambda$display$0(Network.java:219)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		io.github.thebusybiscuit.slimefun4.api.network.Network$$Lambda$6638/0x00000008020b3040.run(Unknown Source)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3022/0x00000008008cbc40.run(Unknown Source)
[19:29:51] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.run(Unknown Source)
[19:29:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[19:29:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[19:29:51] [Paper Watchdog Thread/ERROR]: ------------------------------
```

**Comment by electronicboy** [comment] 2020-07-19 20:27
Likely duplicate of #3957

**Closed as completed by electronicboy** 2020-07-19 20:27 UTC
Labels: version: 1.16
