### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Paper#86] opened 2016-03-17 07:56 UTC
http://pastebin.com/D8uw1H8c

**Comment by Techcable** [comment] 2016-03-17 07:57
What plugins do you have?
One of them might be doing bad things asynchronously.

**Comment by PhanaticD** [comment] 2016-03-17 08:00
a bunch. this was my hub server that crashed

CleanroomGenerator, AsyncWorldEditInjector, DuckTrails, CommandHelper, Cricket, Chairs, WorldBorder, BuycraftX, TeleportSigns, Votifier, ProtocolLib, NoCheatPlus, PhanaticHub, FilterPwned, AsyncWorldEdit, SuperTrails, PermissionsEx, BlockAlias, HideStream, FixDoubleLogins, WorldEdit, HolographicDisplays, WorldGuard, BungeePortals, TitleManager, Essentials, EssentialsChat, EssentialsSpawn, PwnFilter, CodelanxLib, Vault

**Comment by Techcable** [comment] 2016-03-17 16:18
Oh wait is this 1.8?

**Comment by Black-Hole** [comment] 2016-03-17 17:06
"v1_9_R1" :see_no_evil:

**Comment by Techcable** [comment] 2016-03-17 17:12
woopsiez

**Comment by PhanaticD** [comment] 2016-03-18 17:45
just happened again ;-;

**Comment by Techcable** [comment] 2016-03-18 18:14
Does this happen on normal spigot?

**Comment by PhanaticD** [comment] 2016-03-18 18:17
I just put in normal spigot, we will see

**Comment by Black-Hole** [comment] 2016-03-18 19:50
Might be fixed by this commit: https://github.com/PaperMC/Paper/commit/6e76be51bba67c213ffd14f5648be4b4f48870d2

Since this crash happens very rarely (2 times in 1 week on 1 of 9 Paper servers), I'll take a while to verify.

**Comment by boy0001** [comment] 2016-03-19 01:11
Had the same issue, did some debugging and found the cause. Seems to be from unloading a chunk at the wrong time (so I think if it's in the queue for the player and it's unloaded we get this crash). Easy to replicate, just unload all the chunks when they generate

``` Java
@EventHandler
public void onWorldLoad(WorldLoadEvent event) {
    event.getWorld().getPopulators().add(new BlockPopulator() {
        @Override
        public void populate(World world, Random random, Chunk chunk) {
            chunk.unload(true, false);
        }
    });
}
```

Problem occurs on normal spigot too.

**Closed as completed** 2016-03-19 04:04 UTC
