### ISSUE TITLE
Server crashing after going through nether portal - (3rd time in a week)

### ISSUE THREAD

**Issue by TechnicallyCoded** [PaperMC/Paper#5959] opened 2021-06-23 01:05 UTC
### Stack trace

[https://paste.gg/p/anonymous/2b3ec57887db41c4aef3879b6429330a](https://paste.gg/p/anonymous/2b3ec57887db41c4aef3879b6429330a)

### Plugin list

CoreProtect, Essentials, EssentialsGeoIP, GSit, InventoryRollbackPlus, LuckPerms, OpenInv, ProtocolLib, ServerUtils, SuperVanish, Vault, WorldEdit, WorldGuard, floodgate

### Actions to reproduce (if known)

**Behavior Noticed:**
What happens if the server freezes dumps a bunch of the "This is not a crash nor a bug" freeze logs. Then the server dies.

**How it's happening.. maybe?**
It's not really clear why or when this happens but it did seem to happen once after someone coming out of the nether through their nether portal. Chunks didn't load properly but entities showed. It froze the entire server, However after I joined the same area to check if the server was stable, the issue didn't happen again for a while.

Today again, someone seemed to have loaded chunks Paper didn't like. This time I assumed the server going down for a restart forcefully would reset whatever caused this to happen again. In fact, no, this happened twice in a row. The second time I went to check the chunks as I did last time and everything loads fine and the server is fine.

I am guessing this has to do with a certain player load some data the server isn't reading properly but I have no idea really.. that's just a wild guess.

### Paper version

This server is running Paper version git-Paper-"28aacb4" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"47605b8" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-06-23 01:41
Duplicate of #5910

**Closed as completed by electronicboy** 2021-06-23 01:41 UTC
Labels: resolution: duplicate, version: 1.17
