### ISSUE TITLE
Chunks parts "missing"

### ISSUE THREAD

**Issue by PapiCapi** [PaperMC/Paper#4269] opened 2020-09-01 18:40 UTC
### What behaviour is expected:
___What you expected to see___
I'd like to see the chunk how it was saved

### What behaviour is observed:
___What you actually saw___
The chunk has some parts with others blocks that the ones placed ( http://prntscr.com/u9szd7 ). In my screenshot the noteblocks are supposed to be stone bricks, jungle saplings are supposed to be glass , ...
However, when i right click or interact with the block, it comes back to the block it is supposed to be. The more, if i interact with a few blocks, unload the chunk by going far and then come back, the blocks i interacted with come back to their glitchy state ( note block, etc ).

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
No idea but in paper 141 (1.16.2) , this bug was already happening and the whole chunk was "empty". We couldn't interact at any block and couldn't pass through.

### Plugin list:
___A list of your plugins___
AntiAFK*, AntiDecoCombat*, AsyncWorldEdit, Bank, BentoBox, BlockLocker, ChatItem, ChestCommands, ChestShop, Core, CoreProtect, DeACoudre, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, Fe*, Grades, HolographicDisplays, IllegalStack, LuckPerms, MinewebBridge*, ModReq*, MoncubeCore, Multiverse-Core, OnTime*, OpenInv, PlanningsEvents, PlugMan, ProtocolLib, ProtocolSupport, PVPControl, RFChairs, Shopkeepers, SkQuery, Skript, TAB, TokenManager, UltimateStacker, Vault, VillagerOptimiser, VoidGenerator, VoteMoncube, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-168 (MC: 1.16.2)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment] 2020-09-01 18:57
please try updating.... as i believe this was a bug that was fixed a while ago in anti xray but you are not up to date.

**Comment by PapiCapi** [comment] 2020-09-01 18:59
Well, i wasn't updating because of another bug but i'll try.
However, i don't have the anti-xray enabled so this is kinda strange

**Comment by aikar** [comment] 2020-09-01 19:17
what bug is that?

But im also confused as i noticed you listed 2 paper versions in the report.

**Comment by aikar** [comment] 2020-09-01 19:18
please try without plugins too as never heard of this from anyone else.

**Comment by PapiCapi** [comment] 2020-09-01 19:25
For the paper version i'm using 168 (1.16.2) but in 141 ( 1.16.2 ), the bug wasn't the same : the whole chunk was empty. Sorry if it wasn't clear.
For the other bug i already done a report ( https://github.com/PaperMC/Paper/issues/4255 ).

Actually, this is quite hard to try without plugins because i don't even know how to reproduce this bug. I'll investigate more if i can.

One more information : this issue wasn't happening in the 1.16.1 builds.

**Comment by aikar** [comment] 2020-09-01 19:29
The source of this bug is the same as your source for #4255 

It looks like some plugin is corrupting world state.

try removing any plugin dealing with world stuff.

**Comment by aikar** [comment] 2020-09-01 19:30
going to close this as duplicate of #4255, but this feels plugin oriented until you can provide reproduce steps w/o plugins.

**Closed as completed by aikar** 2020-09-01 19:30 UTC
Labels: resolution: duplicate
