### ISSUE TITLE
Lagspikes with low memory free

### ISSUE THREAD

**Issue by DaveTheCamper** [PaperMC/Paper#3432] opened 2020-05-22 15:33 UTC
###  Timings or Profile link:
https://timings.aikar.co/?id=ff92b93e08804aadabed2609c3d3615e

### Description of issue:
On beginning of this month some issue come to my server, when the server has been online for about 5 hours and free memory is low, the server stop responding and came back after 20 seconds.

As you can see in the timings become unplayable only after 16h26, i was forced to restart the server because server freeze every 20 seconds and came back for only 5 seconds.

I already tried: change paper version, use low memory (16GB), enable aysnc-chunks paper config, checkout hardware and remove bloodmoon plugin.

In Spigot help, them recommended me ask help directly for yours, someone mentioned that my "G1 Old" is way too high and i dont know how to fix this and dont know if it is the cause of issue.

### Plugin list:
AdminFun*, AdvancedAchievements, AdvancedEnchantments*, AntiAFKPlus*, AntiWorldFly, ArmorStandTools, BlockLocker, Bloodmoon, boosCooldowns*, BossShop*, Cash, ChatControl, ChatPlugin, ChatReaction, ChestMaster*, ChestShop, Citizens, ClearAll*, ClearLag, ComandosMysql*, CombatLogX, CrazyAuctions, CS-CoreLib, CubeShopPlugin*, CustomHeads*, CustomMessages*, CustomPolls*, DeathMessagesPrime, DeluxeTags*, Deposit, EconomyControl, Elevator, EntityTrackerFixer, Essentials, EssentialsSpawn, Eventos, ExperienceBottle*, FastLogin, FirstJoinPlus*, GriefPrevention, GroupManager, HackedCore*, HackedServer*, InfoMysql*, ItemFilter, Jobs, Keys, LagAssist, LagFilter, LagMonitor*, Leilao, LuckCommands, Marriage*, MC-Cron*, mcMMO, Multiverse-Core, MyCommand, OldCombatMechanics*, PacketListenerApi*, PlaceholderAPI, ProtocolLib, Pshops, QuestsReloaded, ResetChest, RPGItensRevolutions, SafeTrade, ServerTutorialPlus*, Shopkeepers, SignEdit*, SimpleClans*, Skilltree, Slimefun, Spawners, StackItens, StackMobs, TAB, Ticket, TitleManager*, Torneio, TreysCommandBlocker*, Tutorial, UberEnchant*, Uno, Upgrade, Vault, Vender, ViaVersion*, VipZero*, Votifier*, VotingPlugin, VoxelSniper*, WorldEdit, WorldGuard, X1

### bukkit.yml, spigot.yml, paper.yml, server.properties
Paper: https://pastebin.com/RQ9Z0FAE
Bukkit: https://pastebin.com/MnbJAzLq
Spigot: https://pastebin.com/hQH4unJr
Server.properties: https://pastebin.com/D7nSGAnY

### Other helpful links
Error showed when server lag: https://pastebin.com/vt7RbR98
Startup flags: https://pastebin.com/TB9t0GFr
Video showing free mem stats (HUGE lag in 0:33 - 0:58): https://youtu.be/kx6dequgvEE
Checkout memory image: https://www.spigotmc.org/attachments/lenruql4te29aoj1fs0i6w-png.516916/

### Paper build number:
Paper-300 (MC: 1.15.2)

**Comment by astei** [comment] 2020-05-22 15:41
Your G1 old generation times are over 20 seconds. You ultimately have a GC problem, likely caused by a plugin having a memory leak of some sort. You're going to need to remove half of your plugins, test if the issue occurs again, if it continues, continue by removing half until the GC problems stop, then readd the plugins from the pile you removed until the issue recurs.

**Comment by aikar** [comment] 2020-05-22 17:10
A memory leak was fixed in build 305 that might help here. 
But you also should not be using the systems memory usage as a report either. It does not align with Java internal usage.

Please update and if you have memory issues on latest, discuss on discord on next steps.

**Comment by aikar** [comment] 2020-05-22 17:11
Also mojang themselves has a huge memory leak with village data too, I am going to try to fix that soon as I can.

**Closed as completed by aikar** 2020-05-22 17:10 UTC
