### ISSUE TITLE
Add back MC-162253 patch

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#6170] opened 2021-07-12 15:55 UTC
### Is your feature request related to a problem?

You forget how bad it is until the patch is gone, and boy is it bad. 3+ second lag spikes when crossing chunk borders.

https://github.com/PaperMC/Paper/blob/3d43c5e50077ac7fa1e68cf7a7add0ac77768a61/patches/removed/1.17/0438-Workaround-for-Client-Lag-Spikes-MC-162253.patch

### Describe the solution you'd like.

Add a config option for enabling this patch

### Describe alternatives you've considered.

Not playing minecraft anymore

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Chew** [comment] 2021-07-12 16:11
Duplicate of #5089, (also https://github.com/PaperMC/Paper/issues/5785#issuecomment-861693228)

**Closed as completed by Chew** 2021-07-12 16:11 UTC
