### ISSUE TITLE
Tremendous lag caused by "Unload Chunks"

### ISSUE THREAD

**Issue by scrayos** [PaperMC/Paper#806] opened 2017-07-26 23:14 UTC
First of all, I'd like to thank you guys for the amazing timings-enhancements made in PaperSpigot. They usually really offer an amazing way to find and track down the causes of lag. Otherwise I'd probably still be struggling to find the source of a huge lag-problem on my server. Keep up the good work!

###  Timings or Profile link:
https://timings.aikar.co/?id=528d883f1c7d42818b62a6ffbfd5c2a6

### Description of issue:
I created a world where I set "AutoSave" to false. According to the ticket I opened here https://hub.spigotmc.org/jira/browse/SPIGOT-3464 "AutoSave" causes all chunks to stay loaded/prevents them from being unloaded. This is fine, as long as at least one players stays in this world. As soon als all players are in other worlds than this world, the tremendous lag starts. It literally starved my server down to 3 TPS at worst, as you can see in the timings.

I guess the lag is connected to PaperSpigot, attempting to unload the chunks on each tick, but failing to do this because of the AutoSave-setting. I'd like to repeat, that everything's running smoothly, as long as there are players in this world. The lag only starts to "build up" (TPS gradually get worse) as soon as all players have left this world. In the timings this is shown as "Minecraft::end - doChunkMap - Unload Chunks". I tested and confirmed this with all default configs with a freshly downloaded paperclip.jar and no plugins but the TestPlugin that I attached to the ticket on spigot's jira.

### Plugin list:
Also happens with only the attached plugin from this ticket https://hub.spigotmc.org/jira/browse/SPIGOT-3464

### bukkit.yml, spigot.yml, paper.yml, server.properties
Also happens with default configs.

### Paper build number:
This server is running Paper version git-Paper-1155 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Thanks for looking into this matter, it took quite some time to research this issue/its specific cause.
Scrayos

**Comment by aikar** [comment] 2017-07-27 04:10
This is actually by design according to Vanilla, but I agree this is weird.

As you found, chunks are not expected to unload when autosave is turned off.
However, there is logic that says once a nether/end world becomes empty, it will unload all chunks. This logic does not respect the saving disabled flag, and causes all of your chunks to unload all at once, causing this.

Fixed in build 1161

**Closed as completed** 2017-07-27 04:09 UTC
