### ISSUE TITLE
Paper 304 Exception ticking world

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#3422] opened 2020-05-21 03:07 UTC
`[22:57:39] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:473) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.b(SourceFile:207) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance$a.a(ChunkMapDistance.java:397) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:101) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:620) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1081) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:490) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IWorldReader.getBiome(IWorldReader.java:26) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.GenLayerZoomVoronoi.a(SourceFile:66) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.GenLayerZoomVoronoiFixed.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.BiomeManager.a(BiomeManager.java:22) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IWorldReader.getBiome(IWorldReader.java:21) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ItemWorldMap.applySepiaFilter(ItemWorldMap.java:232) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootItemFunctionExplorationMap.a(SourceFile:71) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootItemFunctionConditional.apply(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootItemFunctionConditional.apply(SourceFile:21) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootItemFunction.a(SourceFile:16) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootItem.a(SourceFile:28) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootSelectorEntry$1.a(LootSelectorEntry.java:21) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootSelector.b(SourceFile:79) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootSelector.a(SourceFile:95) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootTable.populateLootDirect(LootTable.java:73) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootTable.populateLoot(LootTable.java:84) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootTable.populateLoot(LootTable.java:90) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootTable.fillInventory(LootTable.java:118) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LootTable.fillInventory(LootTable.java:113) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.TileEntityLootable.d(TileEntityLootable.java:62) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.TileEntityLootable.createMenu(TileEntityLootable.java:143) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.EntityPlayer.openContainer(EntityPlayer.java:1153) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.BlockChest.interact(BlockChest.java:217) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IBlockData.interact(IBlockData.java:236) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:496) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1413) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-304]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[22:57:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_15_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1333) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-304]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:473) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.b(SourceFile:207) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance$a.a(ChunkMapDistance.java:397) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:101) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:620) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:726) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1319) ~[patched_1.15.2.jar:git-Paper-304]
	... 4 more
[22:57:39] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:473) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.LightEngineGraph.b(SourceFile:207) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance$a.a(ChunkMapDistance.java:397) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:101) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:620) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:726) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1319) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-304]
	at java.lang.Thread.run(Thread.java:835) [?:?]`

crash log https://pastebin.com/TRidR5Wf

**Comment by aikar** [comment] 2020-05-21 03:08
dupe of #3410

**Closed as completed by aikar** 2020-05-21 03:08 UTC
