### ISSUE TITLE
generator-settings

### ISSUE THREAD

**Issue by madtomic** [PaperMC/Paper#2701] opened 2019-11-21 12:44 UTC
Can you please add all the structure generator settings back in the paper.yml

Including the recent additions of 1.14 structures

```java
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      mansion: true
***      other structures that was recently added. 
      flat-bedrock: false
```

I think flat-bedrock is only option now.

Thank you

**Comment by zachbr** [comment] 2019-11-21 13:15
Duplicate of GH-1228

**Closed as completed by zachbr** 2019-11-21 13:15 UTC
Labels: resolution: duplicate
