### ISSUE TITLE
[Bug]Server crashed after making a deal with a cartographer villager.

### ISSUE THREAD

**Issue by Alice-space** [PaperMC/Paper#2950] opened 2020-02-12 04:50 UTC
### What behaviour is observed:
[read the log](https://pastebin.com/XVYrfx37).start at line845.
I had reported this to plugin author[ here](https://github.com/BentoBoxWorld/BSkyBlock/issues/261).
Problem occured right after a player made a deal with a cartographer villager.
May be the chunk IO problem.
### Steps/models to reproduce:
 make a deal with a cartographer villager.

### Plugin list:

- InfiniteAnnouncements-1.5.0.jar
- BentoBox-1.11.0.jar
- Dynmap-3.0-beta-10-spigot.jar
- LuckPerms-Bukkit-5.0.72.jar      
- SkinsRestorer.jar

### Paper build number:
```
[04:36:09 INFO]: This server is running Paper version git-Paper-91 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[04:36:09 INFO]: Checking version, please wait...
[04:36:10 INFO]: Previous version: git-Paper-87 (MC: 1.15.2)
```

### Anything else:
Maybe Bskyblock chunk generator doesn`t fit paper

**Comment by electronicboy** [comment] 2020-02-12 05:44
Duplicate of #2312

**Closed as completed by electronicboy** 2020-02-12 05:44 UTC
Labels: resolution: duplicate
