### ISSUE TITLE
Nerfed Blazes don't take damage in water.

### ISSUE THREAD

**Issue by Robit** [PaperMC/Paper#2841] opened 2020-01-11 22:51 UTC
### What behaviour is expected:
Blaze should take damage as they do in vanilla.

### What behaviour is observed:
Blaze doesn't take damage.

### Steps/models to reproduce:
1. Fresh paper 1.15.1 server with no configs changed except nerfing spawned mobs in spigot.yml
2. Place down a blaze spawner and spawn a blaze (I did it in the overworld so I could place water)
3. Submerge the blaze in water.

https://media.discordapp.net/attachments/289587909051416579/665681540872667156/unknown.png

### Plugin list:
None

### Paper build number:
"This server is running Paper version git-Paper-43 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)"

### Anything else:
This may potentially be in other versions (I only tested it for the above build number but am reporting this for someone who tried some other versions).

**Comment by Trigary** [comment] 2020-01-12 05:52
Can confirm that the issue is present in latest. I don't know whether this is a "wontfix" issue or not, but since these nerfed mobs take fire damage, I believe that water should damage blazes.

**Closed as completed** 2020-02-09 04:19 UTC
