### ISSUE TITLE
Debugging block parameters updates adjacent blocks.

### ISSUE THREAD

**Issue by rafe2486** [PaperMC/Paper#4207] opened 2020-08-25 20:47 UTC
What behaviour is expected:
Using the debug stick alters parameters on only the targeted block.

What behaviour is observed:
Using the debug stick alters/updates parameters of adjacent blocks as well as targeted block. Or altering parameters on a targeted block also updates adjacent blocks.

Steps/models to reproduce:
Place glass panes around a stone brick wall pillar and attempt to use the debug stick to disconnect the panes from the wall and vice versa to leave only a flat pillar surrounded by glass.

Plugin list:
Deadchest, PlayerHeads, SilkSpawners, Vault, EntityTrackerFixer

Paper version:
git-Paper-101 (MC 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

Please let me know if this has been fixed in a later version, thanks!

**Comment by Proximyst** [comment] 2020-08-25 20:48
Duplicate of #2134.

**Closed as completed by Proximyst** 2020-08-25 20:48 UTC
Labels: resolution: duplicate, version: 1.16
