### ISSUE TITLE
Exception loading structure piece with id minecraft:jigsaw

### ISSUE THREAD

**Issue by antibitcoin** [PaperMC/Paper#5988] opened 2021-06-24 20:49 UTC
### Expected behavior

No errors showing on console

### Observed/Actual behavior

following error showing at random intervals
[22:45:27 ERROR]: Not a map: null
[22:45:27 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-46]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-46]

### Steps/models to reproduce

It just shows up randomly with more than 40 players online hard to figure out.

### Plugin list

[22:48:17 INFO]: Plugins (91): AdvancedCrates, AdvancedEnchantments, AdvancedNMotd, AltDetector, antiRedstoneClock, ArmoredElytra, ArmorStandCrashFix*, AuctionHouse, AutoBroadcast, AutoPluginLoader, BanItem, BannerText, BuycraftX, ChatEx*, ChatSentinel, Citizens, ClearLag, CMILib, CommandAlias, CommandPanels, CrazyEnvoy, CubCustomDrops, DeathMessages, DeluxeMenus, DeluxeTags*, DiscordSRV, dtlTraders, eBackup, EnchantmentNumbers, Essentials, EssentialsGeoIP, EvenMoreFish, ExecutableItems, EZColors, FarmControl, GambleBarLite*, GangsPlus, Gatekeeper*, HarmonyScoreboard, HeadDatabase, HolographicDisplays, HolographicPlaceholders, HolographicScoreboard*, Insights, InteractiveChat, ItemEditor, ItemSoulBind, Jobs, JoinEventsPro, LPX*, LuckPerms, mcMMO, Mines, OpenInv, PL-Hide-Pro, PlaceholderAPI, PlayerParticles, PlayerVaults, Playtimes*, PluginConstructorAPI, ProdigyMentionSpigot*, ProtocolLib, pvpstats, Quests, Regionerator, SaveRodOfficial*, SCore, ShopGUIPlus, Shopkeepers, SilkSpawners, SimpleGiveall, SimpleRename, SlotMachine, SpecializedCrates, StoreStats, TAB, TCPShield, Themis, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoteParty, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

[22:48:39 INFO]: This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
You are running the latest version

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Prof-Bloodstone** [comment] 2021-06-24 20:58
Vanilla bug: https://bugs.mojang.com/browse/MC-227945
Duplicate of #5873 #5887 #5972 - one is even yours...

**Closed as completed by Prof-Bloodstone** 2021-06-24 20:58 UTC
Labels: resolution: duplicate, upstream: vanilla, version: 1.17
