### ISSUE TITLE
Player Sounds(Interaction) Events

### ISSUE THREAD

**Issue by Splitrox** [PaperMC/Paper#5313] opened 2021-03-05 22:41 UTC
I would like to know what you think of a system where I can change / cancel the player's interaction sounds (Attacks, Steps, etc...). It could be from the bukkit events, because there is no way of knowing which entity the sound was created from and the only way is to do that is create a fork and I think it would be interesting to have this kind of possibility in paper!

**Comment by Proximyst** [comment] 2021-03-06 14:42
Duplicate of #5125

**Closed as completed by Proximyst** 2021-03-06 14:42 UTC
