### ISSUE TITLE
Error when using Citizens2

### ISSUE THREAD

**Issue by WhyDoWeWonder** [PaperMC/Paper#2251] opened 2019-06-27 20:26 UTC
Running Paper-115 1.14.3
Citizens Version: b1708
Plugins List: 
AdminFun*, AdvancedFood, AdvancedHelp, AngelCards*, Bondage, Citizens, CMI, CoreProtect, DiceFurniture, DiscordSRV, EnchantmentSolution, EnchantmentSolutionAdditions, Factions, FactionsBlackList*, FurnitureLib, Holograms*, IllegalStack, Item2Chat, JupiterCore, LuckPerms, Matrix, mcMMO, MMOItems, MMOItemsAnyItemUpdater*, MMOItemsMana*, MMOItemsPerWorldDrops*, Multiverse-Core, MysqlPlayerDataBridge, ProtectionLib*, ProtocolLib*, Sentinel, SurvivalMechanics, TreysCommandBlocker*, Vault*, ViaVersion*, WorldBorder, WorldEdit, WorldGuard

`[16:23:23 WARN]: Entity threw exception at Default:2939.3475351983197,78.99624034210159,-9658.938056748411
[16:23:23 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
[16:23:23 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104)
[16:23:23 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096)
[16:23:23 WARN]:        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421)
[16:23:23 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314)
[16:23:23 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.World.a(World.java:933)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
[16:23:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:23:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:23:23 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-115]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-115]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-115]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by electronicboy** [comment] 2019-06-27 20:28
Duplicate of #2248

**Closed as completed by electronicboy** 2019-06-27 20:28 UTC
Labels: resolution: duplicate, version: 1.14
