### ISSUE TITLE
PlayerPortalEvent is not called when "allow-nether" is false

### ISSUE THREAD

**Issue by Singulativ** [PaperMC/Paper#5117] opened 2021-01-26 10:18 UTC
### What behaviour is expected:
___PlayerPortalEvent is called every time a player walks through a portal (creative) or stand for a few seconds in a portal (survival/adventure)___

### What behavior is observed:
___PlayerPortal event is not called when "allow-nether" in the "server.properties" file is set to "false"___

### Steps/models to reproduce:
___Use the test plugin ([PortalTest.zip](https://github.com/PaperMC/Paper/files/5872720/PortalTest.zip)) which broadcasts "PlayerPortalEvent" every time the event is called or write you own code___

    package de.singulativ.portaltest.main;
    
    import org.bukkit.Bukkit;
    import org.bukkit.event.EventHandler;
    import org.bukkit.event.Listener;
    import org.bukkit.event.player.PlayerPortalEvent;
    import org.bukkit.plugin.java.JavaPlugin;
    
    public class PortalTest extends JavaPlugin implements Listener {
    
        @Override
        public void onEnable() {
            Bukkit.getPluginManager().registerEvents(this, this);
        }
    
        @EventHandler
        public void onPortal(PlayerPortalEvent e) {
            Bukkit.broadcastMessage("PlayerPortalEvent");
        }
    
    }
### Plugin list:
___The mentioned test plugin___

### Paper version:
___git-Paper-444 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)___

**Comment by electronicboy** [comment] 2021-01-26 10:19
Duplicate of #4632

**Closed as completed by electronicboy** 2021-01-26 10:19 UTC
Labels: resolution: duplicate
