### ISSUE TITLE
Special Unicode plays warning sound from windows console

### ISSUE THREAD

**Issue by BoomEaro** [PaperMC/Paper#2556] opened 2019-09-14 12:21 UTC
### What behaviour is expected:
No sounds from the console.

### What behaviour is observed:
If a player enters a special Unicode into the chat, the console (at least on Windows 8.1) will emit a warning sound.
Interestingly, this happens every time the console tries to display this symbol:
https://pastebin.com/Hc5yE7eM
Perhaps there are other similar unicodes.

### Steps/models to reproduce:
1. The server must be running on windows (at least on windows 8.1 it works)
2. For example, create a prefix for a player with a special Unicode.
3. Each time the player sends a message, the windows where the paper server is running plays a warning sound.

### Plugin list:
none

### Paper build number:
This server is running Paper version git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Also works on the latest version: This server is running Paper version git-Paper-177 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Anything else:
Tested on a spigot server, no sounds were made. Maybe you should someday add support for displaying Unicode in the console for OS windows if of course it is possible.

**Comment by zachbr** [comment] 2019-09-14 14:39
Cannot reproduce this on Windows 10, there is no sound or any incorrect behavior. That character looks like a normal bullet, U+2022, not anything weird. It's possible that whatever you were trying to send was altered.

I will say however, Windows as a whole has been a giant support burden over it's special snowflake console handling and poor unicode support. Windows servers make up a small percent (~12%) of our install base, yet are responsible for the majority of console support issues.

At some point, someone is going to have to take the lead on it because I'm not having a fun time investigating every single random Windows-only problem that pops up, just to find out its an edge-case I can't reproduce. :(

**Comment by BoomEaro** [comment] 2019-09-14 16:08
I forgot to say, all Unicode in the console are displayed as question marks.
However, in our case, this Unicode is not displayed at all, instead, a sound is played.

I started the server on windows 10 and in truth, there is nothing like that there and all Unicode are displayed correctly. Perhaps the point is in the windows version and it is not worth worrying about this.

**Comment by MrIvanPlays** [comment] 2019-09-15 08:10
Windows 8 and 8.1 are bullshit.

**Comment by zachbr** [comment] 2019-09-16 03:09
We aren't going to be adding version specific workarounds for old versions of Windows at this time. If it all works fine for you on Windows 10 than I'm going to consider this out of scope.

**Closed as completed by zachbr** 2019-09-16 03:09 UTC
Labels: resolution: cannot reproduce
