### ISSUE TITLE
Bukkit.getWorlds().getLoadedChunks().getEntities() is empty when the plugin loads

### ISSUE THREAD

**Issue by Diranus** [PaperMC/Paper#6227] opened 2021-07-18 19:48 UTC
### Expected behavior

The method in the title should return the entities from the chunks already loaded when the plugin is loaded.

### Observed/Actual behavior

The returned array is empty, if the onEnable() method gets called on server startup.
If I reload that plugin using PlugMan while the server is running, it behaves as expected.

### Steps/models to reproduce

`public class Blablubb extends JavaPlugin implements Listener {
	@Override
	public void onEnable() {
		Bukkit.getPluginManager().registerEvents(this, this);		
		for (World w : Bukkit.getWorlds()) {
			w.getLoadedChunks(); //<------ I'm not empty :)
			w.getEntities(); // <----- I'm empty! :(
			//loaded chunks are expected to be loaded. That includes blocks and entities I think. So I give following a try:
            for (Chunk c : w.getLoadedChunks()) {
                c.getEntities(); //<---- I'm empty too. :((
            }
		}
	}
	@EventHandler(priority = EventPriority.MONITOR)
    public void onChunkLoad(ChunkLoadEvent event) {
        event.getChunk().getEntities();	// <----- Works well, but the event isn't getting fired for the chunks already loaded when the plugin is loaded (around the spawn).
    }
}`

### Plugin list

The one containing the code above
Plugman

### Paper version

[21:43:11 INFO]: This server is running Paper version git-Paper-112 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc127ea)
You are running the latest version
Previous version: git-Paper-626 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I'm not sure if a similar report already exists. At least, I didn't find one so I started one.

It seems like the plugin is getting loaded a little bit too early. If I add a short delay (by Bukkit.getScheduler()), the same issue persists.
If I give it a few more seconds, the array becomes filled with the expected values.

**Comment by electronicboy** [comment] 2021-07-18 19:49
Duplicate of #5872

**Closed as completed by electronicboy** 2021-07-18 19:49 UTC
