### ISSUE TITLE
[1.17 Alpha] Tile entities do not restore properly after chunk unloads

### ISSUE THREAD

**Issue by TwoLeggedCat** [PaperMC/Paper#5854] opened 2021-06-16 19:40 UTC
### Expected behavior

I expect things to not disappear.

### Observed/Actual behavior

Chests turn invisible and are empty.

### Steps/models to reproduce

1. Download [this world](https://twoleggedcat.github.io/pages/files/world.zip) (created on 1.16.5) and start a new 1.17 server with it.
2. `/tp @s 460 70 -9740`
3. Stare at the chests.
4. Disconnect and wait a while.
5. Rejoin and observe invisible chests with no contents (`data` command confirms it is not a client-side quirk).

### Plugin list

None

### Paper version

`This server is running Paper version git-Paper-"3740db0" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

(I am not actually "running the latest version of Paper available from https://papermc.io/downloads.")

**Comment by TwoLeggedCat** [comment] 2021-06-16 19:45
This may or may not affect more worlds as well; the one provided is just the one I found it on.

**Comment by TwoLeggedCat** [comment] 2021-06-16 19:48
Update: the invisible thing applies to beds and shulker boxes as well, and presumably other TEs. Possibly they are two different issues. Shulker boxes appear to be completely removed (or I just forgot where I put them cuz they're invisible).

**Comment by Spottedleaf** [comment] 2021-06-16 19:52
https://gist.github.com/Spottedleaf/896f63b1d99d8b6824679d30fa71fc5b is fix

**Comment by TwoLeggedCat** [comment] 2021-06-18 02:10
This is not fixed as of `git-Paper-"770bcf3"` (second test build). It just occurred again.

**Comment by electronicboy** [comment] 2021-06-18 04:56
Cannot reproduce on latest dev
![image](https://user-images.githubusercontent.com/1228900/122508486-f807d000-cff9-11eb-8d80-956c6cb1eaf1.png)

**Comment by electro2560** [comment] 2021-06-18 07:02
Tested on dev-3 seems to have the issue still.
I placed items into a chest and left the chunks to unload before returning.

```
[02:50:05 ERROR]: Failed to save chunk [618, -666]
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
at net.minecraft.server.level.PlayerChunkMap.b(PlayerChunkMap.java:1046) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.level.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:1009) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:757) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:581) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1551) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$Values.forEach(HashMap.java:1070) ~[?:?]
at net.minecraft.world.level.chunk.Chunk.C(Chunk.java:1192) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.level.WorldServer.unloadChunk(WorldServer.java:1254) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at net.minecraft.server.level.PlayerChunkMap.lambda$scheduleUnload$29(PlayerChunkMap.java:1118) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
... 11 more
```

![Screenshot from 2021-06-18 03-06-17](https://user-images.githubusercontent.com/22134230/122520876-2aa5ce80-cfe2-11eb-931c-01147487fe04.png)

**Comment by electronicboy** [comment] 2021-06-18 07:07
Can you reproduce without plugins?

**Comment by electro2560** [comment] 2021-06-18 07:21
Yes, and it also happens with other tile entities including shulkers, barrels, hoppers, etc. Their contents are empty and chests appear invisible. I didn't see any errors in console this time.
I also tested on a newly generated world.
![Screenshot from 2021-06-18 03-15-38](https://user-images.githubusercontent.com/22134230/122522007-79a03380-cfe3-11eb-8431-ec69d821cc64.png)

![2021-06-18_03 19 10](https://user-images.githubusercontent.com/22134230/122522437-fa5f2f80-cfe3-11eb-8941-ddcfa3bfbece.png)

**Comment by tackleza** [comment] 2021-06-18 16:30
I can confirm this bug, still can reproduce on Paper-1.17-R0.1-EXPERIMENTAL-3.jar without any plugin

Download my world (Paper 1.16.5)
https://file.smilekrub.net/file/sk-blob/web/user/file/XNRqmg/uiiwwbp89qlyrenlxkt37auwbk9twhwf/Tackle-1-16-trim.zip
Then teleport to [171, 75, -145]

To make it easier to reproduce bug please change "keep-spawn-loaded: false" in paper.yml

First visit that chunk is ok. Bug after you enter Nether of leave the area, restart server, etc.... Tile block started to invisible and lost all Tile data

(All chest content are gone. No error in console)

![2021-06-18_23 20 09](https://user-images.githubusercontent.com/3255203/122591030-90e72b80-d08c-11eb-8580-8990b8b8c66d.png)
![2021-06-18_23 20 43](https://user-images.githubusercontent.com/3255203/122591021-8e84d180-d08c-11eb-9122-32d1eef12ef9.png)
![2021-06-18_23 19 29](https://user-images.githubusercontent.com/3255203/122591054-9a709380-d08c-11eb-9844-4277ab8ec6b1.png)
![2021-06-18_23 20 24](https://user-images.githubusercontent.com/3255203/122591050-98a6d000-d08c-11eb-9b1c-54b5815015f1.png)

**Comment by TwoLeggedCat** [comment] 2021-06-18 16:44
I believe this bug and the CME posted above to be unrelated, or at least not the same problem. I can reproduce this consistently without any errors in the console at all.

**Comment by TwoLeggedCat** [comment] 2021-06-18 20:24
Update: stopping the server saves the chests properly. Teleporting or disconnecting and waiting a while does not.

**Comment by Brokkonaut** [comment] 2021-06-19 01:59
I noticed this bug too, without any plugins, without any exceptions

**Comment by tackleza** [comment] 2021-06-19 04:15
Step to reproduce Video https://youtu.be/aiWUr5tPgXg
Sorry for my English 🙂

**Comment by Chew** [comment] 2021-06-19 05:03
Resolved in https://github.com/PaperMC/Paper/commit/309b99b12fb177d304b3bf44cbb0e5e6acf93e00 :3

**Closed as completed by Chew** 2021-06-19 05:03 UTC
Labels: type: bug, status: accepted, version: 1.17
