### ISSUE TITLE
EntityTeleportEvent doesn't fire when entity uses portals

### ISSUE THREAD

**Issue by YouHaveTrouble** [PaperMC/Paper#5715] opened 2021-05-23 15:48 UTC
### Expected behavior

EntityTeleportEvent firing when entity is getting teleported in/out of the nether I would expect the event to fire as PlayerTeleportEvent fires when player gets teleported via nether portal, and as for my understaning EntityTeleportEvent should be the counterpart of PlayerTeleportEvent for entities.

### Observed/Actual behavior

Event does not fire.

### Steps/models to reproduce

- Listen to EntityTeleportEvent
- build a nether portal
- push an animal into nether portal

### Plugin list

none

### Paper version

This server is running Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment] 2021-05-23 18:39
EntityPortalEvent extends EntityTeleportEvent, but they each have their own `HandlerList`s, which to my understanding, means you can't simply listen to EntityTeleportEvent and hear all EntityPortalEvents.

**Comment by electronicboy** [comment] 2021-05-23 18:41
Oh, I had a quick skim to see if there was ane vent fired and missed that it was called from the shape detector logic, an event is fired, but, as Machine said, the portal event has its own handler list meaning that Teleport listeners won't hear it; This seems like a massive flaw but fixing this would induce a hefty behavioral break here

**Comment by Machine-Maker** [comment] 2021-05-23 18:43
Yeah, I'm not sure we can simply remove the handler list from EntityPortalEvent, all of the sudden there would be a lot more EntityTeleportEvents that plugins would not be expecting. I'd suggest listening to both events, and just having a common function that handles both.

**Comment by Machine-Maker** [comment] 2022-01-14 04:15
Closing as works as intended

**Closed as completed by Machine-Maker** 2022-01-14 04:15 UTC
Labels: type: bug, resolution: works as intended, version: 1.16
