### ISSUE TITLE
Entities that cannot interact with blocks trigger interact events

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#4962] opened 2020-12-30 01:40 UTC
### What behaviour is expected:
Entities that cannot trigger blocks do not fire interact events for those blocks.

### What behaviour is observed:
Entities that cannot trigger blocks fire infinite interact events for those blocks.

### Steps/models to reproduce:
Have a bat hit a pressure plate.

### Paper version:
git-Paper-352 (1.16.4)

### Anything else:

This is much worse than it seems, as the pressure plate isn't properly triggered, hundreds of events can quickly be dispatched. If this is mixed with something like a potion toss, this can result in massive amounts of projectile spawns, which can also keep the bat positioned on the pressure plate, effectively creating an infinite loop until chunk unload.

Previously fine in git-paper-128 (MC 1.16.1)

**Comment by DarkArc** [comment] 2020-12-30 01:45
Because this is actually pretty funny (in some way), I'm sharing a video:

https://user-images.githubusercontent.com/778012/103324697-9b4a3600-4a16-11eb-907e-ee053f181e1a.mp4

This occurs from the rather innocent:
```
    public static void throwSlashPotion(Location location) {
        PotionType type = CollectionUtil.getElement(thrownTypes);

        ThrownPotion potion = SplashPotionUtil.throwMaxedSplashPotion(location, type);
        potion.setVelocity(new Vector(
                random.nextDouble() * .5 - .25,
                random.nextDouble() * .4 + .1,
                random.nextDouble() * .5 - .25
        ));
    }

    @EventHandler(ignoreCancelled = true)
    public void onEntityInteract(EntityInteractEvent event) {
        Block block = event.getBlock();
        if (block.getType() == Material.STONE_PRESSURE_PLATE) {
          ChatUtil.sendDebug("A " + event.getEntityType() + " touched me!");
          DeathUtil.throwSlashPotion(contactedLoc);
        }
    }
```

**Comment by Trigary** [comment] 2021-02-02 00:27
Can confirm.

Fun fact: bats are weird in vanilla Minecraft:
![image](https://user-images.githubusercontent.com/16213127/106533078-be727480-64f1-11eb-864d-86cca46a63f4.png)

The issue is that `BlockPressurePlateBinary` is incorrectly patched when it comes to `EntityInteractEvent`: the value of `Entity#isIgnoreBlockTrigger` is not checked prior to calling events.

I plan on PRing a fix for this issue.

**Closed as completed** 2021-03-04 17:53 UTC
Labels: type: bug, status: accepted, version: 1.16
