### ISSUE TITLE
PlayerTeleportEvent/PlayerPortalEvent no longer firing

### ISSUE THREAD

**Issue by DarkArc** [PaperMC/Paper#4960] opened 2020-12-30 00:12 UTC
### What behaviour is expected:
When entering a nether portal, a `PlayerPortalEvent` should fire.

### What behaviour is observed:
When entering a nether portal, no `PlayerPortalEvent` fires.

### Paper version:
git-Paper-275 (MC 1.16.4)

### Anything else:
Previously confirmed working on: git-paper-128 (MC 1.16.1)

**Comment by Camotoy** [comment] 2020-12-30 00:13
The latest Paper version is 352. Please try reproducing your issue there.

**Comment by electronicboy** [comment] 2020-12-30 00:16
Did you disable the nether?

**Comment by DarkArc** [comment] 2020-12-30 00:47
> The latest Paper version is 352

Confirmed happening here as well.

> Did you disable the nether?

Yes, `allow-nether=false`, and this does seem to be the problem, changing this to true on a test server fixes the problem.

We don't use the `Main_nether` world, and instead get a `Xyz_nether` through Multiverse, previously the teleport events would still trigger without `Main_nether` being present/generated.

**Comment by Proximyst** [comment] 2020-12-30 00:50
Is it possible for you to try to binary-search the faulty build(s)? A reduction by half would in itself be a great start.

**Comment by electronicboy** [comment] 2020-12-30 00:52
This is a behavioral change in spigot induced by the changes to the teleportation agent in 1.13 or something

**Comment by Proximyst** [comment] 2020-12-30 00:53
It allegedly works in b128 of 1.16.1, though.

**Comment by DarkArc** [comment] 2020-12-30 02:15
Comparing the code between these builds, there was a pretty heavy refactor in this area, likely on the mojang side; just between 1.16.1 and 1.16.4 not 1.13 and 1.16.4 :)

Looking closer to see if there's a reasonable solution that would bring back this functionality.

**Comment by ykgamma** [comment] 2020-12-30 02:19
#4632?

**Comment by electronicboy** [comment] 2020-12-30 02:21
Yes, duplicate of #4632, I guess it was fixed to some degree and re-introduced after some more changes

**Closed as completed by electronicboy** 2020-12-30 02:21 UTC
Labels: version: 1.16
