### ISSUE TITLE
fix-zero-tick-instant-grow-farms: false should be the default

### ISSUE THREAD

**Issue by nbastin** [PaperMC/Paper#2704] opened 2019-11-22 16:40 UTC
### What behaviour is expected:

Vanilla-like behaviour on upgrade

### What behaviour is observed:

Farms that work in vanilla no longer work in paper

### Steps/models to reproduce:

zero-tick farms, of course.

### Plugin list:

None

### Paper build number:
209 (from 192)

### Anything else:

It seems perfectly fine to make this a configurable option for those users that want it, but changing vanilla behaviour by default seems antithetical to what paper generally claims to be (from the docs and FAQ entries, "On a properly maintained server, your players may not even be able to tell the difference.", etc.).  Also of course the first focus in the docs is "A performant server is paramount", and it's important to point out that small zero-tick farms are often an essential component of a performant server, rather than giant tick eating farms.

**Comment by electronicboy** [comment] 2019-11-22 16:41
This is a bug which has been fixed in 1.15, and is a performance killer in specific setups. The option is given to server owners who wish to retain this bug in 1.14, however; We do not support bugs.

**Closed as completed by electronicboy** 2019-11-22 16:41 UTC

**Comment by nbastin** [comment] 2019-11-22 16:44
Changing this in paper that maps to 1.15 seems perfectly reasonable, but frankly that reasoning for pre-1.15 just doesn't hold water.  There are lots of bugs that the community relies on (tnt duping, anyone?) that I suspect paper is content to continue to support.  If nothing else it would be nice to have a page in the docs that explains a rationale for making breaking changes, so we can know what might change within a version and what might not.

**Comment by electronicboy** [comment] 2019-11-22 16:48
In 1.15, that option will no longer exist due to the bug being fixed by Mojang

The general gist is that we intend to fix vanilla bugs where viable, if you rely upon vanilla bugs/quirky behavior, we cannot make any promises that such behavior will still remain, either due to being patched unintentionally or intentionally; Where viable, paper strives to patch vanilla bugs, especially ones which have been confirmed by Mojang as a bug. This isn't really a stance which we've changed on, and for the vast majority of survival players playing by the books (which is generally our main catering point), this is a non-consequential change

**Comment by zachbr** [comment] 2019-11-22 16:48
We don’t support TNT duping or other duplication bugs. One of these issues being patched before Mojang is not new nor is it a topic we’re going to reconsider.

Just because we do not fix each and every one of them does not mean we support or endorse them.

This item is actually different than most in that we allow users to re-enable it. That is not the case for most of these types of issues nor will it be.

**Comment by nbastin** [comment] 2019-11-22 16:52
My problem here isn't really about this option, or this bug fix, it's the deployment of the change.  For new users deploying new servers, having the 1.15 behaviour seems fine, but if you're going to offer the option to re-enable it, I think it should have been enabled on upgrade so that it didn't change anything for existing servers.

I guess in this case I'm arguing actually that the option shouldn't have existed at all, but if it does it should have defaulted to previous behaviour for existing servers.

**Comment by electronicboy** [comment] 2019-11-22 17:01
We do not make any guarantees that unintended behaviors of the game will remain untouched, especially given that these unintended behaviors are often bugs/oversights in how the code works.

We patched a bug in 1.14 that was requested to be fixed by server owners/members of the community, we were nice and gave server owners the option to retain the broken behavior instead of just patching the issue outright; We *do not* support bugs, however; made the exception for this one for server owners to be able to re-enable support for this until mojang removes it themselves;

This option is covered in our documentation, and the introduction of this change is in the commit logs as with every other change, it is the server owners responsibility to review the changelogs as they update their servers for anything which may concern them
