### ISSUE TITLE
Chunks load out of control

### ISSUE THREAD

**Issue by FatherWh0** [PaperMC/Paper#2244] opened 2019-06-26 23:07 UTC
I updated one of my servers to 1.14.3. Ever since it's had an issue where one world, seemingly at random which, will start loading chunks. It keeps loading until it overloads the server and the watchdog shuts it down. 

### Link/paste of stack trace

No stack traces occur.

    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___

[16:33:48] [Server thread/INFO]: Plugins (74): Arconix*, AreaShop, ArmorStandEditor, AsyncWorldEdit, AutoMessage*, BottledExp, ChatFeelings, ChestShop, ClearChat*, ClearLag, CoreProtect, CraftBook, CurrencyDrops*, CustomVanillaVillagers, DeathMessages*, DecoHeads*, DriveBackup*, dynmap*, Dynmap-Essentials*, Dynmap-WorldGuard*, EpicRename, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, ezAuctions, FlashyTP*, FlyWorld*, icJukeBox*, ImageOnMap*, LegacyPvP*, LibsDisguises, LWC, MarriageMaster, mcMMO, Minigames, Minigames-Regions, MobArena, MoreVanillaMobs*, Multiverse-Core, Multiverse-NetherPortals, MyPet, NoChorusFruitTP*, NoSpawnerChange, PermissionsEx*, PerWorldInventory, PlaceholderAPI*, PlayerParticles, PlotSquared, PlugMan, PokeStaff*, ProtocolLib*, RandomTeleport, RedstoneClockDetector*, Shopkeepers, SnowballDamage*, Stables*, SuperbVote, SuperTrails*, UltimateTimber, Vault, ViaVersion*, VillageInfo*, VoidGenerator, Votifier*, WDLCompanion*, WhatIsIt, WorldBorder*, WorldEdit, WorldEditCUI, WorldGuard, WorldGuardExtraFlags, WorldSchematics2, XrayInformer*

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Simply letting the server run will reproduce the issue.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___

paper 1.14.3 build 114

https://pastebin.com/yWUFfxVh https://pastebin.com/wrg5DpKF https://pastebin.com/QjDu3r1V

**Comment by MiniDigger** [comment] 2019-06-27 06:03
not sure there is an paper issue here.
the first watchdog timeout seems to be cause by multiverse doing a full save of the world when you unloaded it via a command, I would guess your disk was just too slow (do you use ssds? shared hosting?)
the second and the 3rd are caused by async world edit, or well, to be more clear, by your world schematic plugin doing world edit operations on chunk load.

**Comment by FatherWh0** [comment] 2019-06-27 21:41
With the first one I was attempting to unload the world that was loading chunks out of control. As far as the others it seems to be random what plugin it reports. 
The server is on SSD drives.
I've done further testing and I can say for certain it's chunks loading endlessly that overloads the server. I've noticed it doesn't happen with the three vanilla worlds. Also it happens with a world that's been visited by a player. Leaving that world doesn't stop the chunks from continuing to load.

**Comment by BillyGalbreath** [comment] 2019-06-27 22:31
The issue looks to be the plugin WorldSchematics. From looking at your 2nd pastebin stack, this plugin is messing with BlockPopulators.

1.13 pretty much broke BlockPopulators in that trying to place a block at the edge of the chunk involved causes it's neighbor chunk to load. 1.14 compounds this behavior by going full async on chunk load/gen in vanilla.

In a nutshell, WorldSchematics is placing blocks in chunks that are loading/generating. This causes those neighbor chunks to load as well. Which since this plugin seems to be using custom generation blockpopulators has to populate those newly loaded chunks. But doing so causes those neighbors to load. Then those, too, have to be populated which causes _even more_ chunk loads. Its a viscous cycle that started back in 1.13 for a few plugins but is now hurting every single world generation plugin that uses BlockPopulators.

Ultimately, what this all boils down to is the developer of that plugin needs to find a better way to populate chunks to not trigger infinite loads on 1.14

**Comment by FatherWh0** [comment] 2019-06-30 21:45
You found it! The problem disappears when I remove WorldSchematics2.

**Comment by Chew** [comment] 2020-08-25 18:59
Looks like the problem was resolved as per the last comment! Glad to see. If for whatever reason it isn't fixed on the latest version, let us know by making a new issue. Have a good day!

**Closed as completed by Chew** 2020-08-25 18:59 UTC
