### ISSUE TITLE
Attempting to restart with ./crash.sh

### ISSUE THREAD

**Issue by Duartteno** [PaperMC/Paper#1765] opened 2018-12-23 20:19 UTC
### What behaviour is expected:
Crash.sh is not executed

`crash.sh`
```
# !/bin/bash

echo "[$(date)] Crash: test.jar" >> /home/crash.txt
pkill -9 -f test.jar
```
`spigot.yml`
```
  restart-on-crash: true
  restart-script: ./crash.sh
```

`start.sh`
```
# !/bin/bash

while true
do
  cd /home/test && java -Xms4G -Xmx4G -jar test.jar
  sleep 5
done
```
### Paper build number:
paper-1594

Everything works. But sometimes server get crash, there is high cpu usage (100-150%), there are no players on the server and last log in the console is `Attempting to restart with ./crash.sh` and nothing happens. I need to restart server manually.

**Comment by electronicboy** [comment] 2018-12-23 20:30
When creating issues, we expect that people fill in the template, or at least provide the full amount of information that we ask for.

if you're having to restart the server manually, that would imply that your script stopped running, the biggest concern would be bashs `set -e` option, which would cause the script to be killed on failure.

the moment you see `Attempting to restart with`, that means that the shutdown hook has been installed, at that point if it doesn't work, the issue is outside of our control, e.g. your script didn't execute (is it marked as executable, etc)

**Closed as completed by electronicboy** 2018-12-23 20:30 UTC
Labels: resolution: incomplete
