### ISSUE TITLE
Chunks around players not being loaded when view distance is increased

### ISSUE THREAD

**Issue by froobynooby** [PaperMC/Paper#5203] opened 2021-02-20 04:40 UTC
### What behaviour is expected:
All chunks within the newly set view distance of a player should be loaded when a world's view distance is increased through the API

### What behaviour is observed:
None / only some of the chunks are loaded when the view distance is increased

### Steps/models to reproduce:

1. Create a fresh server (view distance 10, no-tick view distance -1).
2. Install TestPlugin: [testplugin.zip](https://github.com/PaperMC/Paper/files/6013994/testplugin.zip) (source below).
2. Join the server and teleport far away from spawn chunks (since they're already loaded).
3. Run the command `/vd 20` to set the view distance to 20.

After setting the view distance to 20 you should notice that none or only some of the chunks beyond a view distance of 10 load in. Walking into the unloaded chunks seems to cause them to load - and relogging / teleporting to a different area fixes the issue entirely.

You can confirm with `/paper chunkinfo` that the chunks are actually not being loaded, not that they're just not being sent to the client.

### Plugin list:
TestPlugin, spark

### Paper version:
git-Paper-470 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
TestPlugin source:
```java
public class TestPlugin extends JavaPlugin {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("This command cannot be used from the console.");
            return true;
        }
        if (args.length == 0) {
            return false;
        }
        Player player = (Player) sender;
        int value;
        try {
            value = Integer.parseInt(args[0]);
        } catch (NumberFormatException ex) {
            return false;
        }
        if (label.equalsIgnoreCase("vd")) {
            player.getWorld().setViewDistance(value);
        } else if (label.equalsIgnoreCase("ntvd")) {
            player.getWorld().setNoTickViewDistance(value);
        }
        return true;
    }
}
```

**Comment by DoogiePC** [comment] 2021-02-20 15:13
Can confirm, also having this issue.

**Comment by froobynooby** [comment] 2021-02-21 09:39
On further testing, the problem doesn't seem to exist for the last Paper release for 1.15.2 but does exist for the first Paper release for 1.16.1

**Comment by Proximyst** [comment] 2021-02-22 19:04
Cannot reproduce. How many players are online during this? I'd assume it's just because it has to load a tonne of chunks that it's stalling.

**Comment by froobynooby** [comment] 2021-02-22 21:43
I've been testing on a server with just myself online. I've tried with the instance hosted on my local machine and also a (much faster) dedicated server and have seen the issue both times

**Comment by mindgam3s** [comment] 2021-02-25 12:25
can confirm that issue
running **paper-1.16.5-468**

I was acutally the person to find that issue and froobynooby created the issue for me

I was alone on the server.
it did not matter whether the server was just online for a few seconds  after a reboot or online for minutes.
when the view distance increased I could only see as far as before. on a rejoin the new view distance applied.

even when the view distance increased from 6 to 8 (which is not much for a single player)
wasn't a performance issue or network.

**Comment by mindgam3s** [comment] 2021-02-28 16:18
awesome! 
@froobynooby : do you get notified when the code is committed and released in a new version of paper ?

**Comment by froobynooby** [comment] 2021-03-01 10:52
> awesome!
> @froobynooby : do you get notified when the code is committed and released in a new version of paper ?

Since you have commented in here you should receive a notification through github when the issue is resolved

**Comment by mindgam3s** [comment] 2021-03-01 11:33
> > awesome!
> > @froobynooby : do you get notified when the code is committed and released in a new version of paper ?
> 
> Since you have commented in here you should receive a notification through github when the issue is resolved

good to know. thanks :)

**Closed as completed** 2021-04-15 08:51 UTC
Labels: type: bug, status: accepted, resolution: awaiting response, version: 1.16

**Comment by DoogiePC** [comment] 2021-04-16 12:10
Just a note on that, chunks seem to load but VERY slowly for a while then they suddenly just load all at once, it's really weird. In tuinity they just load fast all the time.

**Comment by DoogiePC** [comment] 2021-04-19 18:50
![image](https://user-images.githubusercontent.com/29175381/115287737-866deb80-a148-11eb-8199-1d2e44fa49b3.png)

Like that ^^^
it seems to sort of hover and not load for a minute or so and then it all loads in suddenly.

**Comment by mindgam3s** [comment] 2021-04-22 08:18
> Like that ^^^
> it seems to sort of hover and not load for a minute or so and then it all loads in suddenly.

cannot confirm this behavior on my side

did you check whether this is a Server<-->Client connection problem (bandwidth ?)
or your server cannot handle the (sudden) increase in data ?
or the client ?
