### ISSUE TITLE
[1.16.1] Server crashs.

### ISSUE THREAD

**Issue by yurinogueira** [PaperMC/Paper#4002] opened 2020-07-26 17:38 UTC
The error happens randomly and the plugin that is reported as crashed is also random.

### Logs:
[https://paste.gg/p/anonymous/aee2ef86c6f64003a882a7a5c1f3e22d](https://paste.gg/p/anonymous/aee2ef86c6f64003a882a7a5c1f3e22d)
[https://paste.gg/p/anonymous/4e790282a3504a6693bd5ee86c1cc811](https://paste.gg/p/anonymous/4e790282a3504a6693bd5ee86c1cc811)

### Plugin list:
AsyncWorldEdit, AuthMe, ChestShop, ChestTerminal, Citizens, CS-CoreLib, DiscordSRV, dtlTraders, EterniaLib, EterniaServer, ExoticGarden, FogusCore, GoldenCrates, GoldenEnchants, GriefPrevention, GriefPreventionFlags, HackedCore, HackedServer, HolographicDisplays, LiteXpansion, LuckPerms, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-Inventories, MyPet, PlaceholderAPI, ProtocolLib, SimpleClans, SkinsRestorer, Slimefun, TAB, Vault, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit

### Paper build number:
The logs are from 115, but this does not happen at 93

**Comment by electronicboy** [comment] 2020-07-26 20:18
Duplicate of #3986

**Closed as completed by electronicboy** 2020-07-26 20:18 UTC
