### ISSUE TITLE
Player get kicked out the server=timed out 

### ISSUE THREAD

**Issue by POTJATHEGOD** [PaperMC/Paper#6019] opened 2021-06-28 09:10 UTC
### Expected behavior

i expect that player don't get kicked out the server by timed out 

### Observed/Actual behavior

player will get kicked out the server console says timed out

### Steps/models to reproduce

![2021-06-28 11_08_25-Window](https://user-images.githubusercontent.com/83860262/123610837-43dc2580-d801-11eb-8473-63b1306f1a02.png)

### Plugin list

AdvancedPortals, AuctionMaster, AureliumSkills, AuthMe, ChatManager, Citizens, CitizensCMD, ClearLag, CoreProtect, DiscordSRV, DualWield*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, LuckPerms, Maintenance, ProtocolLib, PvPToggle, ServerListPlus*, Shop, SilkSpawners, SkinsRestorer, Slimefun, SuperbVote, TAB, UltimateTimber, Vault, VillagerOptimiser, Votifier, WorldEdit, WorldGuard

### Paper version

This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
You are running the latest version
Previous version: git-Paper-49 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment] 2021-06-28 09:17
Duplicate of #895.

**Closed as completed by Proximyst** 2021-06-28 09:17 UTC
Labels: version: 1.17
