### ISSUE TITLE
Villager trading (sometimes) crashes the server

### ISSUE THREAD

**Issue by emkirsh** [PaperMC/Paper#4191] opened 2020-08-24 02:44 UTC
### Link/paste of stack trace

[https://paste.gg/p/anonymous/fc6bd14c7fd348d2b951f8d99032898d](https://paste.gg/p/anonymous/fc6bd14c7fd348d2b951f8d99032898d)

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

Well, I was told to post it anyways because the main thread ends up crashing.

### Plugin list:
___A list of your plugins___
`AAC, AACPlus, BedrockPlayerManager, BlockLocker, CMI, CMIPaperLib, ConditionalCommands, CraftBook, CrateReloaded, CustomCrafting, DeathMessagesPrime, DiscordSRV, DMPEnderCrystal, DMPMonitorCompat, DMPPlaceholderAPI, EnjinMinecraftPlugin, floodgate-bukkit, FloodgatePlaceholders, Geyser-Spigot, Graves, Harbor, LuckPerms, MVdWPlaceholderAPI, MyCommand, PlaceholderAPI, PlayerVaults, PremiumVanish, ProtocolLib, Residence, SmoothTimber, Vault, ViaVersion, WolfyUtilities, WorldEdit, WorldGuard`

### Actions to reproduce (if known):

___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
[Reproducing the issue](https://youtu.be/emj2O47uCJc)
1) make a huge villager center.
2) trade with a lot of villagers really fast.
    - reproducing the bug seems to be more reliable when trading glass
3) kill the server once you get the first watchdog message or wait for it to "officially" crash.

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
`git-Paper-137`

**Comment by electronicboy** [comment] 2020-08-24 02:45
Duplicate of #2312

**Comment by emkirsh** [comment] 2020-08-24 02:46
How does this have anything to do with treasure chests?

**Closed as completed by electronicboy** 2020-08-24 02:45 UTC
Labels: resolution: duplicate

**Comment by electronicboy** [comment] 2020-08-24 02:47
It's all the exact same codepath and logic, just a different source into that logic

**Comment by emkirsh** [comment] 2020-08-24 02:47
okay.

**Comment by emkirsh** [comment] 2020-08-24 02:48
it's a very severe issue. the other issue seems to have been here for over a year.... when can I expect a fix?

**Comment by emkirsh** [comment] 2020-08-24 03:02
Shoot. It's a vanilla bug? This is never getting fixed....

**Comment by Chew** [comment] 2020-08-24 03:08
Paper fixes Minecraft Server bugs all the time, in fact from what I read it was fixed, however had to be dropped during the upgrade process from 1.15 to 1.16, so I think it's in the to-do to be re-added.

**Comment by emkirsh** [comment] 2020-08-24 03:16
ok. that's good to hear!
