### ISSUE TITLE
Server crashing when trading with Cartographer

### ISSUE THREAD

**Issue by perseus5** [PaperMC/Paper#2781] opened 2019-12-19 20:31 UTC
### Link/paste of stack trace

https://pastebin.com/Q3EWyNfg
   
### Plugin list:
BuycraftX, Citizens, CoreProtect, Holograms*, HoneyPopulator, LockettePro, mcMMO, MCore, mSurvival, ProtocolLib, spark, ViaBackwards*, ViaRewind*, ViaVersion*, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Trading with a cartographer crashes the server (happens with one cartographer every time, didn't happen with a second cartographer I tried), not sure exactly how to replicate it. Bit vague I know, was hoping there's something in that pastebin that's useful. 

### Paper build number:
[Server] INFO This server is running Paper version git-Paper-"dfd740cd" (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment] 2019-12-19 21:04
Basically a duplicate of #2312

**Closed as completed by electronicboy** 2019-12-19 21:04 UTC
