### ISSUE TITLE
Converting a world from Vanilla to PaperMC changes the location of players outside the overworld when they login

### ISSUE THREAD

**Issue by JCombee** [PaperMC/Paper#5199] opened 2021-02-17 20:34 UTC
### What behaviour is expected:
When I convert a world from Vanilla Minecraft to PaperMC I expect to spawn at the same location I logged out when I join the server. 

### What behaviour is observed:
When I join the converted world in PaperMC I spawned more then 1000 bloks away from the location I actually logged out.

### Steps/models to reproduce:
The world that I have added in the description has players in it that when they join in the PaperMC version they end up in a different spot then is observed in the NBT data.
This is only registered in players that didnt log out in the overworld.

### Plugin list:
None

### Paper version:
[21:13:36 INFO]: This server is running Paper version git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[21:13:36 INFO]: Checking version, please wait...
[21:13:37 INFO]: You are running the latest version

### Anything else:
I have a recording added to the attachments to show the case.
[2021-02-17 20-57-27.zip](https://github.com/PaperMC/Paper/files/5998358/2021-02-17.20-57-27.zip)
[world example.zip](https://github.com/PaperMC/Paper/files/5998420/world.example.zip)

**Comment by Camotoy** [comment] 2021-02-17 20:46
Looks like this is a duplicate of https://github.com/PaperMC/Paper/issues/4797.

**Comment by aurorasmiles** [comment] 2021-02-17 21:13
Duplicate of #4797

**Closed as completed by aurorasmiles** 2021-02-17 21:13 UTC
Labels: resolution: duplicate, version: 1.16
