### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by xKsyStudio** [PaperMC/Paper#6436] opened 2021-08-19 17:20 UTC
### Expected behavior

位置是中国 玩着玩着客户端就掉线了 后台无任何报错

### Observed/Actual behavior

java.net.SocketException: Connection reset

### Steps/models to reproduce

偶尔出现

### Plugin list

![QQ截图20210820011953](https://user-images.githubusercontent.com/87989105/130114529-178c4134-c39c-4d7f-b328-d2a96dc0f9c7.jpg)
![QQ截图20210820011959](https://user-images.githubusercontent.com/87989105/130114534-0395e544-df34-4e8b-b8b5-129766d6b73d.jpg)

### Paper version

paper-1.17.1-196

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment] 2021-08-19 17:20
Duplicate of #895

**Closed as completed by Proximyst** 2021-08-19 17:20 UTC
