### ISSUE TITLE
some customitem's displayname changed to italic

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PaperMC/Paper#3475] opened 2020-05-30 10:27 UTC
### What behaviour is expected:
___What you expected to see___

### What behaviour is observed:
___What you actually saw___
when a player leave game and join game,his customitem's display changed to italic
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
___A list of your plugins___
itemadder

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
#325 and #327 both cause this problem
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Proximyst** [comment] 2020-05-30 10:31
Reproduce without plugins.

**Comment by aikar** [comment] 2020-05-30 10:42
blarg. this is prob valid concern due to upstreams changes.

If you set an item name to "`<color>name`" it would not be italic, but if that color is the default color, i can see this happening as spigot is stripping the default color.

**Comment by aikar** [comment] 2020-05-31 04:01
This is now fixed in 328+

**Closed as completed by aikar** 2020-05-31 04:01 UTC
