### ISSUE TITLE
Aquatic Mob rapid spawn/despawn

### ISSUE THREAD

**Issue by DeltaKilo97** [PaperMC/Paper#3865] opened 2020-07-09 02:08 UTC
When building a taller structure over water, I noticed a bug where the aquatic mobs would rapidly spawn, be out of the radius, and despawn. I searched for a duplicate issue but could not find it. 

running latest PaperMC build on 1.16.1

**Comment by HexedHero** [comment] 2020-07-09 02:09
https://github.com/PaperMC/Paper/issues/3523

**Comment by DoubleGe** [comment] 2020-07-12 12:03
Issue is duplicated of ^

**Comment by Chew** [comment] 2020-08-21 04:16
Duplicate of #3523

This appears to be a duplicate of #3523 , so this will be closed in favor of that issue instead. Thank you for contributing to Paper!

**Closed as completed by Chew** 2020-08-21 04:16 UTC
Labels: resolution: duplicate
