### ISSUE TITLE
Server deadlock when loading some chunks

### ISSUE THREAD

**Issue by justEli** [PaperMC/Paper#2668] opened 2019-11-01 19:59 UTC
### Link/paste of stack trace
https://pastebin.com/x30xgS0d

### Plugin list:
Plugins (23): AuctionHouse, BetterChairs*, BetterConcrete, ChestShop, Coins*, CoreProtect, Discord, dynmap*, GriefPrevention, LiteBans, Oak, PermissionsEx*, PhantomSpawnControl, PlugMan, Portandum, SAML, SmoothSleep, TradePlus, Vault, VillagerOptimiser, Votifier*, Warps, WorldEdit

### Actions to reproduce (if known):
See #2647. It's the same issue, but it still appears to happen in Paper-225 as @tpsutphin mentioned as well.

### Paper build number:
225

**Comment by tpsutphin** [comment] 2019-11-01 20:11
Thanks for bringing this up.  I gave up, the response from the devs was sad at best.  Claiming they fixed the issue and people coming out of the woodwork proving its still an issue.  What do they do?  Close the ticket and move on.  NOT professional at all.

**Comment by electronicboy** [comment] 2019-11-01 20:26
Thank you for providing the information we've asked for, this is not a deadlock but a duplicate of #2312 

As a note: you'll see that the chunks currently being loaded in each dump is a seperate set of co-ords, there is no deadlock, just an insanely huge lookup radius  inducing a lot of chunk loads; There is a vanilla issue report linked on the above ticket

**Comment by Spottedleaf** [comment] 2019-11-01 20:26
We cannot use a merged PR as an issue tracker is all, there's no need to overreact to having an issue moved
You said you can confirm it's an issue, however you have failed to provide any sort of logs which only serves to delay the process of fixing this issue

First part of the log looks like https://github.com/PaperMC/Paper/issues/2312, but the second part doesn't look good

Please provide your config file, I want to know whether async chunks is enabled

**Closed as completed by electronicboy** 2019-11-01 20:26 UTC

**Comment by justEli** [comment] 2019-11-01 22:22
[paper.txt](https://github.com/PaperMC/Paper/files/3799799/paper.txt)
