### ISSUE TITLE
chunk loading cause server stop

### ISSUE THREAD

**Issue by newbie029** [PaperMC/Paper#2059] opened 2019-05-18 23:21 UTC
### Plugin list:
Plugins (24): AuthMe, BossShopPro, BungeeTabListPlus*, CoreProtect, CursedCore*, CursedVIP*, DeluxeChat, Essentials, EssentialsProtect, EssentialsSpawn, GriefPrevention, IllegalStack, LuckPerms, Multiverse-Core, MyCommand, OreReplacerPlugin, PlaceholderAPI*, ProtocolLib*, SkinsRestorer, TradePlus, UltimateTimber, Vault, WorldEdit, WorldGuard

### Paper build number:
git-Paper-20 (MC: 1.14.1)

### Anything else:
Heres the log https://pastebin.com/kWx4CqyS

**Comment by electronicboy** [comment] 2019-05-18 23:28
Duplicate of #2052, also, you're running an outdated build

**Closed as completed by electronicboy** 2019-05-18 23:28 UTC
Labels: resolution: duplicate
