### ISSUE TITLE
Player heads do not retain altered names or lore upon placement and pickup again.

### ISSUE THREAD

**Issue by DeanGrey** [PaperMC/Paper#4642] opened 2020-10-11 15:53 UTC
### What behaviour is expected:
After placing a player head you pick it up and it retains the custom name and lore text assigned to it.

### What behaviour is observed:
The player head has its name reset.

### Steps/models to reproduce:
Create a custom head with something like EpicRename. Place the head on the floor. Pickup the head. Observe it being renamed to its default.

### Plugin list:
EpicRename, HeadDatabase

### Paper version:
Paper version git-Paper-204 (MC:1.16.3) (API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Prof-Bloodstone** [comment] 2020-10-11 16:31
This is Vanilla issue - see:

- https://bugs.mojang.com/browse/MC-209
- https://bugs.mojang.com/browse/MC-174496

Given that the original bug is open for 8 years now I don't have high hopes for it getting fixed. That being said, the fact that the bug was split into second, separate ticket just for heads recently might mean that this will be fixed in one of the future releases.

Depending on how general the fix for it should be, the more potential it has to break something unexpectedly, so I understand why Spigot/Paper didn't fix it, if this was intentional.

If you wish to persist some basic data for heads, there are plugins that provide it. I personally implemented this feature into [VanillaTweaks](https://www.spigotmc.org/resources/vanillatweaks.81288/) plugin - see [source](https://github.com/Prof-Bloodstone/VanillaTweaks/blob/persist_wall_heads/src/main/java/me/machinemaker/vanillatweaks/persistentheads/PersistentHeads.java).

**Comment by kennytv** [comment] 2020-10-11 16:34
It'd honestly scream "inconsistency" to me if only block entities (or even worse *only* the skull) would keep their name and lore, but normal blocks wouldn't

**Comment by aikar** [comment] 2020-10-11 16:38
This will never be fixed unless mojang does it or you do it yourself. Vanilla does not store the itemstack used to place the block.

I have a highly complicated solution in my server using persistent metadata (which doesn't exist in Spigot API yet) to pull this off.

It's not something that can even be put in paper of how I did it. 

This is more a feature request than a bug.

**Closed as completed by aikar** 2020-10-11 16:38 UTC
Labels: type: feature, resolution: works as intended, upstream: vanilla, version: 1.16

**Comment by Prof-Bloodstone** [comment] 2020-10-11 16:55
> It'd honestly scream "inconsistency" to me if only block entities (or even worse _only_ the skull) would keep their name and lore, but normal blocks wouldn't

As far as I'm aware, no block keeps their lore, but there's plenty of BEs which do keep their names throughout - like chests, droppers etc. I wish Mojang did it for all blocks instead of implementing it for very few specific ones, but we can only wait and hope that they'll "fix" MC-209 one day.

**Comment by aikar** [comment] 2020-10-11 17:31
The fact 209 was closed as Working as Intended for the past 8 years, and then suddenly reopened this year is interesting. maybe they are considering it now.

**Comment by BillyGalbreath** [comment] 2020-10-11 23:19
I have a patch by @jmanpenilla that solves this for all tile entities.

https://github.com/pl3xgaming/Purpur/blob/ver/1.16.3/patches/server/0130-Persistent-TileEntity-Lore-and-DisplayName.patch

We beleive it was just an oversight on mojangs part, seeing as some tile entities retain their name (chests) but others don't. None (afaik) retained lore, too. The above patch resolves both.

If it looks good to core team, I or @jmanpenilla could pr it to paper.
