### ISSUE TITLE
ChunkHolder stucks the server and exhaust memory

### ISSUE THREAD

**Issue by Mirviy** [PaperMC/Paper#6224] opened 2021-07-18 09:58 UTC
### Stack trace

```
[11:43:21] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-108 (MC: 1.17.1) ---
[11:43:21] [Paper Watchdog Thread/ERROR]: The server has not responded for 270 seconds! Creating thread dump
[11:43:21] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:43:21] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[11:43:21] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:43:21] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[11:43:21] [Paper Watchdog Thread/ERROR]: 	PID: 19 | Suspended: false | Native: false | State: RUNNABLE
[11:43:21] [Paper Watchdog Thread/ERROR]: 	Stack:
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:951)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.recalcNeighborPriority(ChunkHolder.java:180)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.setNeighborPriority(ChunkHolder.java:171)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:780)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.PlayerChunk$$Lambda$4435/0x00000008018ab1a8.accept(Unknown Source)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.1/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:780)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:130)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:667)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.checkHighPriorityChunks(ChunkMap.java:616)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:674)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:316)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.network.Connection.tick(Connection.java:399)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer$$Lambda$3659/0x00000008013a6878.run(Unknown Source)
[11:43:21] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.1/java.lang.Thread.run(Thread.java:831)
```

### Plugin list

CoreProtect
AuthMe
FastLogin

### Actions to reproduce (if known)

May related to async chunk generating.
My server always crash with ChunkHolder.recalcNeighborPriority at the top of stack when players run around overworld.

also, the ChunkProvider part is taking a great part in timing and cause severe unstable lags.
https://timings.aikar.co/?id=33d83804a79c46be82259be379e50b63
these may be (or not) related.

### Paper version

git-Paper-108 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is always happening since very early 1.17 paper versions.

**Comment by TNTUP** [comment] 2021-07-18 10:48
Not sure if I have the same issue as you, I see ChunkHolder in my recent crashlogs https://paste.gg/p/anonymous/ae7ac1ff309f4d15a3b516b3577f6506

Also the watchdog terminates the main thread due to a hardcrash and doesn't auto-restart (meaning its stuck)

**Comment by kirin-3** [comment] 2021-07-18 12:06
I have the same issue.
```
[11:45:54] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-112 (MC: 1.17.1) ---
[11:45:54] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[11:45:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:45:54] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[11:45:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:45:54] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[11:45:54] [Paper Watchdog Thread/ERROR]: 	PID: 37 | Suspended: false | Native: false | State: RUNNABLE
[11:45:54] [Paper Watchdog Thread/ERROR]: 	Stack:
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.recalcNeighborPriority(ChunkHolder.java:184)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.setNeighborPriority(ChunkHolder.java:171)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.onNeighborRequest(ChunkHolder.java:133)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.getChunkRangeFuture(ChunkMap.java:806)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.scheduleChunkGeneration(ChunkMap.java:1288)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1195)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:547)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.getChunkRangeFuture(ChunkMap.java:803)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.scheduleChunkGeneration(ChunkMap.java:1288)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1195)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:547)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1185)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:547)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1185)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:547)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.schedule(ChunkMap.java:1185)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.getOrScheduleFuture(ChunkHolder.java:547)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.getChunkRangeFuture(ChunkMap.java:803)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkMap.prepareEntityTickingChunk(ChunkMap.java:848)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:742)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:130)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:667)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:749)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:555)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer$$Lambda$3651/0x00000008013a6390.run(Unknown Source)
[11:45:54] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.1/java.lang.Thread.run(Thread.java:831)
[11:45:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:45:54] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[11:45:54] [Paper Watchdog Thread/ERROR]: ------------------------------
```

**Comment by electronicboy** [comment] 2021-07-18 14:56
Duplicate of #5980

**Closed as completed by electronicboy** 2021-07-18 14:56 UTC
