### ISSUE TITLE
Nether portal crash (1.16.2)

### ISSUE THREAD

**Issue by FranckJohann** [PaperMC/Paper#4291] opened 2020-09-05 16:03 UTC
When my players enter active nether portals the server crashes.

https://pastebin.com/vLBM6GW2
https://pastebin.com/HMS9p2Cf

**Comment by electronicboy** [comment] 2020-09-05 16:05
Duplicate of #4199, please try to use the search and fill in the issue template in the future.

**Closed as completed by electronicboy** 2020-09-05 16:05 UTC
Labels: resolution: duplicate
