### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Hyronymos-Old** [PaperMC/Paper#2721] opened 2019-12-08 19:49 UTC
### Link/paste of stack trace
Server Log:  https://privatebin.net/?7d2a565ca9f1bd86#rYTVfDw1SjHxrgbmfm4XA3TgCdmPwHKTLdiEoQFVmfB

Crash Log: https://privatebin.net/?0714be903e731773#2SD8hkCRpPVfPM8UQ5yUaAQ5Deb8HYT4j4gm3vRXvYsF

### Plugin list:
Dm me for Plugin list.

### Paper build number:
latest (235)

**Comment by electronicboy** [comment] 2019-12-08 19:54
Duplicate of #2678

**Closed as completed by electronicboy** 2019-12-08 19:54 UTC
