### ISSUE TITLE
TNT duper TNT activated by itself

### ISSUE THREAD

**Issue by kirakira-pp** [PaperMC/Paper#6201] opened 2021-07-16 09:59 UTC
### Expected behavior

TNT duper's TNT should not be active while the duper is not using.

### Observed/Actual behavior

TNT duper's TNT was active by itself.

### Steps/models to reproduce

1.  According to the [guide](https://github.com/PaperMC/Paper/issues/3854), turn the `allow-piston-duplication` to `true`.

2. Build a tree farm (we follow this [tutorial](https://www.youtube.com/watch?v=CoWb8JmMLhw)). The TNT duper is same as the picture below.
![](https://user-images.githubusercontent.com/72803083/125928680-cde53054-4983-4009-a639-d425cba36a3b.png)

3.  Disconnect near the TNT duper and wait for 1 minute.

4.  Login and you can see the TNT  was active by itself.

### Plugin list

None

### Paper version

This server is running Paper version git-Paper-107 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5a9c14b)
You are running the latest version
Previous version: git-Paper-106 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by kennytv** [comment] 2021-07-16 10:12
Duplicate of https://github.com/PaperMC/Paper/issues/6168

**Closed as completed by kennytv** 2021-07-16 10:12 UTC
Labels: resolution: duplicate
