### ISSUE TITLE
Spawning limit broken?

### ISSUE THREAD

**Issue by Zzheyd** [PaperMC/Paper#4284] opened 2020-09-03 17:36 UTC
Hello here, have problem :s

Have NO monster on new nether if have many player in world...

If i'm only one player in world ... monster spawn

Have per-player-mob-spawns: true to paper.yml (paper 1.16.2-182)
In bukkit.yml, have:

spawn-limits:
  water-ambient: 5
  monsters: 40
  animals: 3
  water-animals: 4
  ambient: 1

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Plugin list:
Mythicmobs
Mmoitem
Mmolib
Mobfarmmanager
Limitepillager
Citizens
Dynmap
FAWE
Worldguard
Jobs
Multiverse

Have try without mobfarmmanager, have same issue.
Thanks you :)

**Comment by Zzheyd** [comment] 2020-09-03 18:08
Maybe per-player-mob-spawns doesnt work correctly with fortress/bastion?

**Comment by Zzheyd** [comment] 2020-09-03 18:14
For exemple, if player kill BIG magma cube, medium/small magma cube doesnt spawn

**Comment by electronicboy** [comment] 2020-09-03 18:16
We'd need to see your configs, grab a timings report or something, this sounds more configuration or "working as intended"

**Comment by Zzheyd** [comment] 2020-09-03 18:39
Spigot yml : https://pastebin.com/bXDRC0cB
Paper yml : https://pastebin.com/rY2Ve4sw
Bukkit yml : https://pastebin.com/pFXFV4Ma

For timings its complicated... i have put /timings report, bug link is broken : "Oops - Could not load Timings Report"

**Comment by Chasewhip8** [comment] 2020-09-03 18:41
I think you should test without Mobfarmmanager and maybe even Mythicmobs.

**Comment by Zzheyd** [comment] 2020-09-03 18:44
have already trying without mobfarmmanager, i can try whitout mythymobs now

**Comment by Zzheyd** [comment] 2020-09-03 19:08
Hum i see this : MythicMobs-4.10.0-SNAPSHOT.jar
1/1/70 12:00am	Forced mob spawns to obey bukkit.yml monster limits (needs testing)

Maybe mythicmobs have broken bukkit.yml monster limits and forced limite without per-player-mob-spawns ...

**Comment by krolik-exe** [comment] 2020-09-03 19:38
Try setting count-all-mobs-for-spawning to true in Paper.yml

**Comment by malonnnn** [comment] 2020-09-04 16:20
I have a similar issue, and the only related plugins me and OP have in common is mythicmobs dev versions.

That's gotta be it.

**Comment by Zzheyd** [comment] 2020-09-13 00:22
Confirm, it's mythicmobs with: Forced mob spawns to obey bukkit.yml monster limits (needs testing)
With previous version of MM, spawn work fine... with this version or newest, spawn is broken!

**Comment by Proximyst** [comment] 2020-09-27 16:45
Closing as it was confirmed a plugin issue.

**Closed as completed by Proximyst** 2020-09-27 16:45 UTC
Labels: plugin
