### ISSUE TITLE
Sometimes server will stop responding for a long time when trading with villager

### ISSUE THREAD

**Issue by sandtechnology** [PaperMC/Paper#2955] opened 2020-02-14 02:09 UTC
###  Timings or Profile link:
https://timings.aikar.co/?id=b1e72487db3d4499af872ad84ca73915

### Description of issue:
Sometimes server will stop responding for a long time when trading with villager, it look like is finding something:https://paste.ubuntu.com/p/9tf6BVHK35/

### Plugin list:
Plugins (47): AlwaysKeepInventory*, AsyncWorldEdit, AutoMessage, ChunksExplorerLimiter*, ClearLag, ColorMOTD*, CommandConfirmer*, CoreProtect, dynmap*, EntityTrackerFixer, Essentials, EssentialsSpawn, ExtendViewDistance, FastLeafDecay, GSit, HeadDropsSS, IllegalStack, LangUtils, LimitPillagers, LuckPerms, LWC, MobSpawnLimit, Multiverse-Core, NyaaCore, OpenInv, PlaceholderAPI, PlayerListGUI, PlayRewarder, ProtocolLib, QQBinder, QuickShop, Residence, SAML, SimpleNoCropTrample*, Sleep, SmoothTimber, TitleManager, TrChat, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, WorldBorder, WorldEdit, WorldeditFixer, XuanCatAPI, yasui

### bukkit.yml, spigot.yml, paper.yml, server.properties
bukkit.yml:https://paste.ubuntu.com/p/7CSsm3CsQj/
spigot.yml:https://paste.ubuntu.com/p/2r8FfnfdW2/
paper.yml:https://paste.ubuntu.com/p/Y559HKXxC8/
server.properties:https://paste.ubuntu.com/p/GcbfvwpzvZ/

### Other helpful links:
None

**Comment by electronicboy** [comment] 2020-02-14 02:12
Duplicate of #2312

**Closed as completed by electronicboy** 2020-02-14 02:12 UTC
