### ISSUE TITLE
chunks are not loading for some players 

### ISSUE THREAD

**Issue by POTJATHEGOD** [PaperMC/Paper#5979] opened 2021-06-24 09:28 UTC
### Expected behavior

i expect the that chunks are loading normally 

### Observed/Actual behavior

chunks aren't loading for some reasson 
![image](https://user-images.githubusercontent.com/83860262/123239042-47a93880-d4df-11eb-9813-ddc3ca41c263.png)

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/83860262/123239076-4f68dd00-d4df-11eb-943d-6f496149f9c0.png)

### Plugin list

AdvancedPortals, AuctionMaster, AureliumSkills, AuthMe, ChatManager, Citizens, CitizensCMD, ClearLag, CoreProtect, DiscordSRV, DualWield*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, LuckPerms, Maintenance, ProtocolLib, PvPToggle, ServerListPlus*, ShopGUIPlus, SilkSpawners, SkinsRestorer, Slimefun, SuperbVote, UltimateTimber, Vault, Votifier, WorldEdit, WorldGuard

### Paper version

This server is running Paper version git-Paper-45 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0be7cdb)
You are running the latest version
Previous version: git-Paper-"4e2f0be" (MC: 1.17)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-06-24 09:30
Update, probably a duplicate of #5910

**Closed as completed by electronicboy** 2021-06-24 09:30 UTC
Labels: version: 1.17

**Comment by POTJATHEGOD** [comment] 2021-06-24 10:33
is this a paper problem or just a 1.17 problem?

**Comment by kennytv** [comment] 2021-06-24 10:40
Try the latest build, 46. It was a Paper issue.

**Comment by POTJATHEGOD** [comment] 2021-06-24 13:55
on vanilla server and spigot server i have the same problem i'am gonna try change to paper build 46
