### ISSUE TITLE
97 and newer builds sometimes cause server freeze when load Restricted Creative plugin database

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#3951] opened 2020-07-19 12:48 UTC
### What behaviour is expected:
___What you expected to see___
97 and newer builds no cause server freeze when load Restricted Creative plugin database
With build 93 or older versions works perfectly the database load.

### What behaviour is observed:
___What you actually saw___
97 and newer builds sometimes cause server freeze when load Restricted Creative plugin database

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Start server with Restricted Creative plugin and Paper 97 or newer build.
2. Restricted Creative plugin start loading the database.
3. The server freeze, and Restricted Creative never load the database.

### Plugin list:
___A list of your plugins___
Plugins (108): AdminVedelem, antiRedstoneClock, ArmorStandEditor, BetterGUI, BungeeHelpop, BuntetesLogolo, ChatControl, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, CSGO-CratesPlus, DisablePistonFarming, Duels, DyedBackpacks, EnderContainers, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Jatekido, Kemkedes, Kezdes, LibsDisguises, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaBot, PomaDrops, PotionArmors, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SignEdit, SkinsRestorer, sleep-most*, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, SpleefPlusPlus, StaffChat, StaffTime, SzulinapiKalapok, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-99 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___
```
11:55:29] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-99 (MC: 1.16.1) ---
[11:55:29] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[11:55:29] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:55:29] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[11:55:29] [Paper Watchdog Thread/ERROR]: 107,-46 in 'plotworld:
[11:55:29] [Paper Watchdog Thread/ERROR]: Load Task - none
[11:55:29] [Paper Watchdog Thread/ERROR]: Save Task - none
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[11:55:29] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[11:55:29] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:55:29] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[11:55:29] [Paper Watchdog Thread/ERROR]: 	PID: 42 | Suspended: false | Native: false | State: TIMED_WAITING
[11:55:29] [Paper Watchdog Thread/ERROR]: 	Stack:
[11:55:29] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer.lambda$getChunkAt$9(ChunkProviderServer.java:474)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer$$Lambda$6061/0x0000000801ecfc40.get(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1001)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1048)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1029)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1105)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$8(MinecraftServer.java:1204)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$5864/0x0000000801e33c40.getAsBoolean(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:118)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3041/0x00000008008c4440.run(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.run(Unknown Source)
[11:55:29] [Paper Watchdog Thread/ERROR]: ------------------------------
[11:55:29] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[11:55:29] [Paper Watchdog Thread/ERROR]: ------------------------------

[12:22:52] [Craft Scheduler Thread - 5/WARN]: [RestrictedCreative] Plugin RestrictedCreative v2.3.8 generated an exception while executing task 445
java.util.concurrent.CompletionException: java.lang.ThreadDeath
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1001) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1048) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:635) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1145) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-99]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ThreadDeath
	at java.lang.Thread.stop(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:761) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-99]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-99]
[12:22:52] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Unknown Source) [?:?]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:761) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-99]
	at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-99]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-99]
```
With build 93 or older versions never write this error.
[crash.zip](https://github.com/PaperMC/Paper/files/4943728/crash.zip)

**Comment by MrIvanPlays** [comment] 2020-07-21 15:23
Not paper's issue.
Report to the plugin's developers

**Comment by electronicboy** [comment] 2020-07-26 20:18
Duplicate of #3986

**Closed as completed by electronicboy** 2020-07-26 20:18 UTC
Labels: version: 1.16
