### ISSUE TITLE
Diagonal rail slows down more when adjacent to wall

### ISSUE THREAD

**Issue by jacobjennings** [PaperMC/Paper#4574] opened 2020-09-25 21:48 UTC
### What behaviour is expected:
___What you expected to see___
A diagonal minecart rail with walls directly on one side should show similar behavior to a straight rail in terms of slowing down

### What behaviour is observed:
___What you actually saw___
After upgrading from vanilla to paperMC, minecarts slowed down in diagonals

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

Create a diagonal rail with a 2-block high diagonal wall along one side of the railroad

### Plugin list:
___A list of your plugins___
dynmap

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
git-Paper-204 (MC: 1.16.3)

### Anything else:
___Anything else you think may help us resolve the problem___
Thx in advance for looking into it

**Comment by Phoenix616** [comment] 2020-12-02 20:54
Pretty sure this is still happening and has been for a while, StaleBot 👀

**Comment by Phoenix616** [comment] 2021-01-31 21:55
Any chance you could provide an example world which behaves differently between Vanilla and Paper?

**Comment by Owen1212055** [comment] 2022-08-06 01:07
![image](https://user-images.githubusercontent.com/23108066/183226571-2d0199c0-c92d-4bce-a46a-8d431194b1ca.png)

I have tested this on 1.19.1 and although I am able to reproduce some kind of slow-down behavior with walls, it seems to be both the same on vanilla and paper. Because of the fact that I was unable to determine any difference between these versions, I will be closing this. If you still find differences in this behavior between paper and vanilla that may have been missed, feel free to open a new issue with things like a world download in order to help with the reproduction of the issue. 😄

**Closed as not planned by Owen1212055** 2022-08-06 01:07 UTC
Labels: type: bug, version: 1.16
