### ISSUE TITLE
block.setBiome() does nothing

### ISSUE THREAD

**Issue by skerit** [PaperMC/Paper#2791] opened 2019-12-22 21:41 UTC
### What behaviour is expected:

After performing something like `block.setBiome(Biome.PLAINS)` I expect the biome to change, but it does not.

### What behaviour is observed:

The old biome (generated by Minecraft) is still there.

### Steps/models to reproduce:

Try to adjust the biome of a block from inside a Populator class

### Paper build number:
Paper version git-Paper-26 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

This used to work in 1.14. In fact, I was developing my plugin for 1.14. But once I tried it on a 1.15 server (even after recompiling for 1.15) it didn't work anymore.

**Comment by electronicboy** [comment] 2019-12-23 00:18
Replication code? Biomes are now 3d

**Comment by Brokkonaut** [comment] 2019-12-25 21:08
The problem is, that spigot changes the biome on the wrong block, because it ignores the fact that only for every 4x4x4 blocks a biome is stored - For example when I try to set the biome of the block 0,10,0, it will be changed around 0,40,0 (class BiomeStorage)

**Comment by skerit** [comment] 2019-12-27 15:36
I did it like this:

```java
int chunk_x = 0;
int chunk_z = 0;
int center_x = 8;
int center_z = 8;
int y_floor = 70;
int radius_ceil = 10;

int x = 0;
int y = 0;
int z = 0;
int layer = 0;
int radius = 0;
int level = 0;

for (layer = radius_ceil; layer > 0; layer--) {
	level = radius_ceil - layer;
	radius = layer - level;

	for (int cz = 0 - radius; cz <= radius; cz++) {
		for (int cx = 0 - radius; cx <= radius; cx++) {
			x = chunk_x * 16 + (center_x + cx);
			z = chunk_z * 16 + (center_z + cz);

			y = y_floor - level;

			if (cx * cx + cz * cz <= radius * radius + radius) {

				block = world.getBlockAt(x, y, z);
                                block.setType(Material.DIRT);
				block.setBiome(biome);

			}
		}
	}
}
```

This would create a round island that would shrink in radius every layer.

I'll see if I get a different result when I just set the biome for every Y-level (0 - 255), too.

**Comment by Black-Hole** [comment] 2019-12-31 18:21
It seems Spigot stores the 3D biomes correctly for each 4*4*4 cube, but Minecraft is using the bottom layer only for the whole chunk:
https://www.reddit.com/r/Mojira/comments/e5at6i/a_discussion_for_the_changes_to_how_biomes_are/

**Comment by Brokkonaut** [comment] 2020-01-07 06:06
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/CraftWorld.java#927

I think it should be something like `chunk.getBiomeIndex().setBiome((x & 15) >> 2, y >> 2, (z & 15) >> 2, bb);` there

**Comment by Black-Hole** [comment] 2020-01-07 14:37
chunk.getBiomeIndex().setBiome() does the calculation for each x, y, z.

**Comment by Brokkonaut** [comment] 2020-01-07 16:09
It just clamps the values to the limits (0 to 3 for x and z, 0 to 63 for y), but does not do the required division by 4.

**Comment by Black-Hole** [comment] 2020-01-07 17:33
Oh, you're right. Minecraft ist calling those method after applying some transformation in GenLayerZoomVoronoi:
(i: seed, j: x, k: y, l: z)

```
   public BiomeBase a(long i, int j, int k, int l, BiomeManager.Provider biomemanager_provider) {
        int i1 = j - 2;
        int j1 = k - 2;
        int k1 = l - 2;
        int l1 = i1 >> 2;
        int i2 = j1 >> 2;
        int j2 = k1 >> 2;
        double d0 = (double) (i1 & 3) / 4.0D;
        double d1 = (double) (j1 & 3) / 4.0D;
        double d2 = (double) (k1 & 3) / 4.0D;
        double[] adouble = new double[8];

        int k2;
        int l2;
        int i3;

        for (k2 = 0; k2 < 8; ++k2) {
            boolean flag = (k2 & 4) == 0;
            boolean flag1 = (k2 & 2) == 0;
            boolean flag2 = (k2 & 1) == 0;

            l2 = flag ? l1 : l1 + 1;
            i3 = flag1 ? i2 : i2 + 1;
            int j3 = flag2 ? j2 : j2 + 1;
            double d3 = flag ? d0 : d0 - 1.0D;
            double d4 = flag1 ? d1 : d1 - 1.0D;
            double d5 = flag2 ? d2 : d2 - 1.0D;

            adouble[k2] = a(i, l2, i3, j3, d3, d4, d5);
        }

        k2 = 0;
        double d6 = adouble[0];

        int k3;

        for (k3 = 1; k3 < 8; ++k3) {
            if (d6 > adouble[k3]) {
                k2 = k3;
                d6 = adouble[k3];
            }
        }

        k3 = (k2 & 4) == 0 ? l1 : l1 + 1;
        l2 = (k2 & 2) == 0 ? i2 : i2 + 1;
        i3 = (k2 & 1) == 0 ? j2 : j2 + 1;
        return biomemanager_provider.getBiome(k3, l2, i3);
    }
```

**Comment by electronicboy** [comment] 2020-03-01 00:03
To my understanding, this has been fixed by upstream for a little while now

**Closed as completed by electronicboy** 2020-03-01 00:03 UTC
