### ISSUE TITLE
Server freeze while looking for datapack structures

### ISSUE THREAD

**Issue by XionioXMaster** [PaperMC/Paper#8069] opened 2022-06-28 22:35 UTC
### Stack trace

https://gist.github.com/XionioXMaster/35c509ae6e01f256cb4d55e1dc1ff9ac

### Plugin and Datapack List

Plugins are not required at all
**[01:34:51 INFO]: Plugins (8): AuthMe, CustomCrafting, FartherViewDistance, ItemsAdder, LoneLibs, LuckPerms, ProtocolLib, WolfyUtilities**

Terralith data-pack 1.19

### Actions to reproduce (if known)

/locate structures any villager or terralith structures 
In addition, I noticed this in other data packs
![Без имени](https://user-images.githubusercontent.com/86433158/176315152-7eae31a1-d991-4f56-984a-652baa1acd33.png)

I'm banned from the Paper discord so I can't contact you before

### Paper version

[01:34:24 INFO]: This server is running Paper version git-Paper-40 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 0d79b86)

**Comment by Doc94** [comment] 2022-06-28 22:44
Duplicate of #7963 (?
And the server is in offlinemode

**Comment by Chew** [comment] 2022-06-30 00:46
See above.

**Closed by Chew** 2022-06-30 00:46 UTC
Labels: status: needs triage
