### ISSUE TITLE
Locate command can hang/crash server 

### ISSUE THREAD

**Issue by pyrestriker** [PaperMC/Paper#4356] opened 2020-09-22 19:08 UTC
[latest (6).log](https://github.com/PaperMC/Paper/files/5263491/latest.6.log)

This started with a custom world generation preset (via datapacks) that has structures but generated very far apart. After a few /locate commands, the server would hang, and then kick everyone and crash afterward.

I'm not seeing the plugin we added to obtain this vanilla functionality (because world structure is different) in the chain, so I don't think it's actually the plugin that is the issue. I understand that this feature, even in Vanilla, is experimental, but still worth uploading the crash logs for a potential fix.

**Comment by electronicboy** [comment] 2020-09-22 19:46
Duplicate of #2312

**Closed as completed by electronicboy** 2020-09-22 19:46 UTC
Labels: resolution: duplicate
