### ISSUE TITLE
Server crashed for no apparent reason

### ISSUE THREAD

**Issue by gabboman** [PaperMC/Paper#3122] opened 2020-04-10 16:31 UTC
### Link/paste of stack trace

   
I don't know what happend, but was a crash. First time in my life it crashed like that, I thought I should report it here

### Plugin list:
 AntiSpam*, BloodMoon, CoreProtect, EntityTrackerFixer, Essentials, IllegalStack, KixsChatAnnouncer, LuckPerms, Matrix, MobArena, Phantom-B-Gone*, PlayerHeads, ProtocolLib, RandomSpawn*, Skript, spark, TAB, Vault, VaultChatFormatter*
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

### Paper build number:
167

**Comment by zachbr** [comment] 2020-04-10 16:43
Fall back to 165, this is a known issue. We'll get to it, everyone just at work for the moment.

We believe this is the same issue cause as GH-3119 so I'm going to close this but I appreciate your reporting it with all the info  :)

**Comment by zachbr** [comment] 2020-04-10 16:52
Just going to leave this open until we confirm root causes. Never mind.

**Closed as completed** 2020-04-10 18:16 UTC

**Comment by aikar** [comment] 2020-04-10 18:32
build 168 should have this fixed now.
