### ISSUE TITLE
Datapack on Paper-617

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#1985] opened 2019-04-20 15:02 UTC
### What behaviour is expected:
Spawn blocks by placing egg. I have to reload the datapack by /datapack disable,enable to let it work again. Sometimes when I place egg it get lag spikes and the datapack does not react. I have 7 worlds and on everyone is this datapack. 

### What behaviour is observed: WHILE PLACING EGG
[16:47:38 FATAL]: Error executing task
net.minecraft.server.v1_13_R2.ReportedException: Loading entity NBT
at net.minecraft.server.v1_13_R2.Entity.f(Entity.java:1861) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:237) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityTypes.b(EntityTypes.java:209) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityTypes.spawnCreature(EntityTypes.java:173) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:168) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:162) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.ItemMonsterEgg.a(SourceFile:81) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:191) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:532) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1347) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-617]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-617]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: net.minecraft.server.v1_13_R2.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:NONE
at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:38) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:43) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityInsentient.a(EntityInsentient.java:456) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.EntityBat.a(EntityBat.java:174) ~[patched_1.13.2.jar:git-Paper-617]
at net.minecraft.server.v1_13_R2.Entity.f(Entity.java:1770) ~[patched_1.13.2.jar:git-Paper-617]
... 20 more

### Plugin list:
 AdvancedArmorStands, AdvancedPortals, Citizens, ClearLag*, CommandNPC*, CommandSigns, EasyCarts, EpicHeads, Essentials, HolographicDisplays, InvRestore2*, KInvBackup*, MorkazSk*, Multiverse-Core, Multiverse-Inventories*, Multiverse-NetherPortals, MultiWorldMoney*, OtherDrops, PermissionsEx*, PixelPrinter, PlaceholderAPI, PlayMoreSounds*, PluginConstructorAPI, PlugMan*, RFChairs, ServerRestorer, Shopkeepers, SkQuery*, Skript, skript-mirror*, Spawners, TopLite*, TuSKe*, Vault*, WG-GUI, WolvSK*, WorldBorder, WorldChangeScreenRemover, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper build number:
This server is running Paper version git-Paper-617 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:50:41 INFO]: Previous version: git-Paper-597 (MC: 1.13.2)
[16:50:41 INFO]: You are 4 version(s) behind

### Anything else:
Datapack youtube link: https://www.youtube.com/watch?v=H4jfKsGch98

**Comment by electronicboy** [comment] 2019-04-20 16:10
`Caused by: net.minecraft.server.v1_13_R2.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:NONE`
How are you creating those eggs? The error just suggests that you're using an improper key on the eggs

**Comment by Misio12320** [comment] 2019-04-20 17:15
I'm taking the eggs from saved toolbars in creative mode (sometimes e.g 64), and from reloaded datapack. It also sends "click here to get the eggs"

**Comment by aikar** [comment] 2020-05-23 03:54
Closing due to 1.13, please reopen a new ticket if still persists on 1.15.2 latest

I believe spigot fixed this upstream

**Closed as completed by aikar** 2020-05-23 03:54 UTC
