### ISSUE TITLE
Server Crash [Portal?]

### ISSUE THREAD

**Issue by nick-wd** [PaperMC/Paper#3576] opened 2020-06-18 17:43 UTC
### Link/paste of stack trace
https://pastebin.com/QD2eKhtE
    You can also simply just use code formatting in markdown!

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
Advanced-Portals
AuctionHouse
Buycraft
ChatControl
ChatReaction
ChestShop
Citizens
CitizensCMD
CombatLogX
CoreProteect
CrateReloaded
CrazyEnchantments
DeluxeChat
DeluxeMenus
DeluxeTags
EntitiyTrackerFixer
EpicWorldGenerator
EssentialsX
EssentialsXChat
EssentialsXProtect
EssentialsXSpawn
FastChunkPregenerator
FeatherBoard
GriefPrevention
GuiRedeemMCMMO
IllegalStack
HolographicDisplays
IPWhitelist
Item2Chat
JetsMinions
KixsChatAnnouncer
LagAssist
LibsDisguises
LiteBans
Lottery
LWCX
mcMMO
MoneyPouch
Multiverse-Core
MVdWPlaceholderAPI
MyCommand
Nametagedit
NightVisoin
NoFlyZone
nuvotifier
OldCombatMechanics
PacketListenerAPI
PermissionsEx
PL-Hide-Pro
PlaceholderAPI
PlayerVaultsX
PlayerWarps
PlugMan
ProtocolLIb
quests
RandomTeleport
ServerTUtorialPlus
ShopGUIPlus
SilkSpawners
SimplePets
SimpleRename
sleep-most
spark
StopNetherTrap
SuperbVote
TCPShield
TempFly
TitleManager
TradeMe
UltimateTimber
UltraBar
Vault
Viabackwards
Viarewwind-all
ViaVersion
VillagerOptimiser
VoteParty
Vouchers
WitherAC
WorldBorder
Worldedit
Worldguard

### Actions to reproduce (if known):
No clue

### Paper build number:
353

**Comment by Chew** [comment] 2020-06-18 19:10
Related to #3572 ?

**Comment by Techcable** [comment] 2020-06-18 22:50
Out of curiosity, does this still happen with `asyncChunks` set to false in your paper config?

**Comment by aikar** [comment] 2020-06-18 23:05
async chunks = false doesn't really turn off async chunks. It's kind of a false config.

It is relating to a bug in recent work gotta look into how this might happen.

**Comment by aikar** [comment] 2020-06-19 17:53
closing as duplicate of https://github.com/PaperMC/Paper/issues/3572

**Closed as completed by aikar** 2020-06-19 17:53 UTC
Labels: resolution: duplicate
