### ISSUE TITLE
Entity pathfinding behaves differently in latest build

### ISSUE THREAD

**Issue by MatrixTunnel** [PaperMC/Paper#3349] opened 2020-05-11 20:12 UTC
### What behaviour is expected:
Video A

### What behaviour is observed:
Video B

### Steps/models to reproduce:
Video A: https://gfycat.com/pastelfatalhypacrosaurus

Video B: https://gfycat.com/plushcreepycanvasback

### Plugin list:
AutomatedCrafting, EpicWorldGenerator, Graves, MeteoritesPro, OldCombatMechanics, Plan, PublicCrafters, RedstoneProximitySensor, WorldEdit, Zenchantments

### Paper build number:
`This Server is running Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
`Previous version git-Paper-279 (MC: 1.15.2)`

**Comment by aikar** [comment] 2020-05-11 20:18
Duplicate of: https://github.com/PaperMC/Paper/issues/3346
Track that, wil be fixed this evening.

**Closed as completed by aikar** 2020-05-11 20:18 UTC
