### ISSUE TITLE
Not able to Ride a minecart trough end gateway portals. 1.16.1

### ISSUE THREAD

**Issue by twok-cloud** [PaperMC/Paper#3735] opened 2020-07-01 04:14 UTC
### What behaviour is expected:
What usually would happen is when you get into the mine cart you are able to ride to the other side going trough one gateway portal to the other one. 

### What behaviour is observed:
Got into the mine cart and it stood still inside the portal frame not going anywhere. 

### Plugin list:
Core Protect, Dynmap, bettersleeping, automatedcrafting, openinv, clans

### Paper build number:
Git-paper-26 (MC: 1.16.1) (Imlempenting API version 1.16.1-R0.1-SNAPSHOT)

**Comment by derklaro** [comment] 2020-07-01 05:41
Can you reproduce it with spigot?

**Comment by twok-cloud** [comment] 2020-07-01 06:02
No I can't with spigot it works perfectly fine. I know the exact code that caused this issue also if you want me to show that.

**Comment by aikar** [comment] 2020-07-01 06:06
Well normally the server doesn't tolerate teleporting vehicles, but looks like they do support it internally now for same world teleporting. So guess we can remove that check.

**Comment by twok-cloud** [comment] 2020-07-01 06:07
Alright then. I will be looking forward to hearing an update when you get to it.

**Comment by aikar** [comment] 2020-07-01 10:29
Fixed in latest

**Closed as completed by aikar** 2020-07-01 10:29 UTC
