### ISSUE TITLE
Modifying sign lines does not work correctly

### ISSUE THREAD

**Issue by TheCiROMG** [PaperMC/Paper#5218] opened 2021-02-22 12:11 UTC
### What behaviour is expected:
I hope to put up a poster that protects this chest

### What behaviour is observed:
I put up the poster and not only does the text not appear, it was not directly protected

### Steps/models to reproduce:
Put the Block Locker plugin, Open the server, Put a chest, put a poster on it with right click

### Plugin list:
list of plugins
![image](https://user-images.githubusercontent.com/61605643/108706597-958c4080-74ed-11eb-9d4c-f3c4460451d2.png)

### Paper version:
![image](https://user-images.githubusercontent.com/61605643/108706635-a5a42000-74ed-11eb-9ded-face91ae9361.png)

### Anything else:
Previously, in versions prior to 470 of paper mc 1.16.5, everything was fine, so I think it was that they implemented some other element wrong and that is why it fails

**Comment by chickeneer** [comment] 2021-02-22 12:16
Hey there. You should report this issue to BlockLocker. If a Paper change has caused the issue, we would need some technical details to solve it.
https://www.spigotmc.org/resources/blocklocker.3268/

**Comment by kashike** [comment] 2021-02-22 12:25
This might be caused by some recent changes - we will investigate. If anyone wants to help determine the cause of this (or help fix it), please feel free to do so.

**Comment by TheCiROMG** [comment] 2021-02-22 12:29
In 467 the plugin was working correctly, I don't know what could have been

I have reported the error to the DEV of the plugin but it always takes time to respond

**Comment by Proximyst** [comment] 2021-02-22 18:49
Fixed by 7c3499702e168133167e095a23a7fe983ea21640.

![https://uwu.whats-th.is/9BHPmew.png](https://uwu.whats-th.is/9BHPmew.png)

**Closed as completed by Proximyst** 2021-02-22 18:49 UTC
Labels: type: bug, status: accepted
