### ISSUE TITLE
Chunk generate

### ISSUE THREAD

**Issue by Misio12320** [PaperMC/Paper#1928] opened 2019-03-31 11:00 UTC
While pre-generating the world with worldborder I'm getting crash 
[2019-03-31-3.log](https://github.com/PaperMC/Paper/files/3026499/2019-03-31-3.log)
log. Version: This server is running Paper version git-Paper-597 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[12:59:37 INFO]: Previous version: git-Paper-570 (MC: 1.13.2)
[12:59:37 INFO]: Checking version, please wait...
[12:59:37 INFO]: You are running the latest version

**Comment by Misio12320** [comment] 2019-03-31 11:03
[12:41:09] [PaperChunkGen-swiat/ERROR]: Requested chunk : 97 151
--
815 | [12:41:09] [PaperChunkGen-swiat/ERROR]: Region bounds : 119 130 \| 121 132
816 | [12:41:09] [PaperChunkGen-swiat/ERROR]: Couldn't generate chunk (swiat:120,131)
817 | java.util.concurrent.CompletionException: java.lang.RuntimeException: We are asking a region for a chunk out of bound \| 97 151
818 | at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_202]
819 | at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_202]
820 | at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_202]
821 | at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_202]
822 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_202]
823 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-597]
824 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_202]
825 | at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_202]
826 | at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_202]
827 | at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_202]
828 | at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_202]
829 | at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.2.jar:git-Paper-597]
830 | at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]

**Comment by aikar** [comment] 2019-03-31 14:32
Duplicate of #1450  - please follow that bug for progress. I've copied the important details over.

**Closed as completed by aikar** 2019-03-31 14:32 UTC
