### ISSUE TITLE
Vivecraft Server Plugin/Vivecraft Client - Projectiles fall to earth immediately

### ISSUE THREAD

**Issue by xperia64** [PaperMC/Paper#4330] opened 2020-09-16 01:00 UTC
When using Vivecraft in VR connected to a Paper server, projectiles fall immediately from the user's hand when launched. These include eggs, snowballs, and arrows launched with both bows and crossbows. When playing in single player or using a regular Spigot server, this issue does not occur. I have only been able to reproduce this with the true VR Vivecraft client, not with the NonVR client or any other Vanilla client configuration

### What behaviour is expected:
Projectiles from VR users should launch with appropriate velocity normally as they do for desktop users

### What behaviour is observed:
Projectiles from VR users have no velocity and fall to earth right where they are launched from the user's hand

### Steps/models to reproduce:

1. Configure and set up a Paper server and add the Vivecraft Spigot Extensions plugin
2. Connect using the VR Vivecraft client
3. Acquire projectile
4. Attempt to throw or launch projectile

### Plugin list:
[Vivecraft Spigot Extensions 1.16.2r2](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases)

### Paper version:
` This server is running Paper version git-Paper-189 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`
(this is the final version compatible with 1.16.2, which Vivecraft at the time of writing this requires; I did not see any significant changes in subsequent Paper versions so far that would appear to affect this bug)

### Anything else:
I understand the Paper team may not have access to compatible VR hardware, but I'm hoping it may be possible to determine the cause of this by examining the Vivecraft plugin source available here: https://github.com/jrbudda/Vivecraft_116

**Comment by astei** [comment] 2020-09-16 01:31
Please reproduce without the Vivecraft plugin.

**Comment by astei** [comment] 2020-09-16 01:32
This sounds like it's a bug in the Vivecraft plugin, not in Paper. Just to be sure it is a Paper issue, can you try to reproduce this with Spigot 1.16.3?

**Comment by Techjar** [comment] 2020-09-16 02:05
It's currently only for 1.16.2, we'll have it updated fairly soon. In any case the issue does not occur on a regular Spigot server.

The code that is somehow breaking on Paper is here: https://github.com/jrbudda/Vivecraft_Spigot_Extensions/blob/1.16/src/org/vivecraft/listeners/VivecraftCombatListener.java#L39

**Comment by jrbudda** [comment] 2020-09-16 02:08
this is caused by the paper patch that sets entity velocity to 0 on teleport. we can work around this on our end by always setting velocity after using .teleport as I assume that patch exists for some good reason.

**Comment by Chew** [comment] 2020-09-16 02:15
Then this is likely a duplicate of #4292

**Comment by jrbudda** [comment] 2020-09-16 02:24
yup, i just saw the discussion related to that patch also breaking the vanilla /summon command so I assume it will be reverted or adjusted.
I will go ahead and re-order the code on my end anyway. 
You can close this issue.

**Comment by Chew** [comment] 2020-09-16 02:34
Sounds good, hope for the best!

**Closed as completed by Chew** 2020-09-16 02:34 UTC
Labels: version: 1.16
