### ISSUE TITLE
Error Failed to save chunk

### ISSUE THREAD

**Issue by LucidAPs** [PaperMC/Paper#2313] opened 2019-07-13 08:37 UTC
The server didn't crash and i am uncertain if any problems or glitches occurred to the player that triggered the error.

Plugin List:
ActionHealth3.3.1
Advanced-Portals-0.2.0-snapshot
AutomaticInventory
BetterChairs
checkdeath-0.4.0
CustomSkinsManager-2.0.5
JEssentials+V1.5.9
LuckPerms-Bukkit-4.4.1
Minepacks
MOTD
PlaceholderAPI-2.10.3
ProtocolLib
SetHome
SinglePlayerSleep-2.13.21
TAB v2.4.11
ultimatetimber-2.0.0
Vault
worldedit-bukkit-7.0.0
worldguard-bukkit-7.0.1-beta-01

[Error Log.txt](https://github.com/PaperMC/Paper/files/3388606/Error.Log.txt)

**Comment by electronicboy** [comment] 2019-07-13 08:44
Duplicate of #2104

**Closed as completed by electronicboy** 2019-07-13 08:44 UTC
