### ISSUE TITLE
Console error placing structure block

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#1395] opened 2018-08-31 20:22 UTC
### What behaviour is expected:
Don't see any error in console when placing structure block.

### What behaviour is observed:
Placing structure block triggers that error. With latest spigot version and also fresh installation don't occur.

https://pastebin.com/v7B7b5v8

### Steps/models to reproduce:
give yourself a structure block and place it.

### Plugin list:
None, fresh install and config files

### Paper build number:
Paper version git-Paper-200 (MC: 1.13.1)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by aikar** [comment] 2018-08-31 21:52
Sigh, I guess passing world to snapshots isn't going to work.

Things break if you do, and break if you don't, woot!

**Comment by aikar** [comment] 2018-09-03 16:36
fixed in 213+

**Closed as completed by aikar** 2018-09-03 16:36 UTC
Labels: type: bug, status: accepted

**Comment by BillyGalbreath** [comment] 2018-09-30 17:04
@aikar someone ran into this on build 315. https://hastebin.com/jiwisadebu.css

I am unable to reproduce. https://i.imgur.com/2rSmn6z.jpg

**Comment by aikar** [comment] 2018-09-30 17:13
@BillyGalbreath that is unrelated to this
