### ISSUE TITLE
PlayerPortalEvent Not working

### ISSUE THREAD

**Issue by Fyrinlight** [PaperMC/Paper#4961] opened 2020-12-30 00:51 UTC
### What behaviour is expected:
PlayerPortalEvent firing when player uses nether portal.

### What behaviour is observed:
PlayerPortalEvent is not firing

### Steps/models to reproduce:
```Java
	@EventHandler(priority = EventPriority.LOW)
	public void OnPlayerPortal(PlayerPortalEvent event) {
		Bukkit.getLogger().log(Level.INFO, "OnPlayerPortal fired: " + event.isCancelled());
		if(event.isCancelled()) return;
		event.setCancelled(true);
```
The above Code will not fire, the event is registered in the plugin.
### Paper version:
[00:31:49 INFO]: This server is running Paper version git-Paper-350 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[00:31:49 INFO]: Previous version: git-Paper-339 (MC: 1.16.4)

### Additional Notes:
We have the Nether and End disabled, not sure if that would impact this.

**Comment by Machine-Maker** [comment] 2020-12-30 00:51
#4960?

**Comment by Proximyst** [comment] 2020-12-30 00:52
Duplicate of #4960.

**Comment by Chew** [comment] 2020-12-30 00:52
> We have the Nether and End disabled, not sure if that would impact this.

Thanks for confirming. We're merging this into #4960, if you'd like to help us track what build broke this please feel free :)

**Closed as completed by Proximyst** 2020-12-30 00:52 UTC
Labels: resolution: duplicate, version: 1.16

**Comment by Fyrinlight** [comment] 2020-12-30 00:56
> > We have the Nether and End disabled, not sure if that would impact this.
> 
> Thanks for confirming. We're merging this into #4960, if you'd like to help us track what build broke this please feel free :)

Will do, I guess fate had us both open the same issue at the same time haha!
