### ISSUE TITLE
Extended Bundle Duplication issue

### ISSUE THREAD

**Issue by aikiboo** [PaperMC/Paper#6550] opened 2021-09-03 11:31 UTC
### Expected behavior

When we try to put an item in a full extended bundle like this one 
("/give @s bundle{Items:[{id:"minecraft:cod",Count:64b},{id:"minecraft:cod",Count:64b}]}") ,
action has to be cancelled. 

### Observed/Actual behavior

Action isn't cancelled and the item that we try to put inside is duplicated. 

### Steps/models to reproduce

1. Give to player a bundle with more than 64 items inside.
2. Give to player a random item that can be put inside a bundle.
3. Try to put the item in the bundle
4. We will duplicate it

### Plugin list

None 

### Paper version

This server is running Paper version git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)
You are running the latest version
Previous version: git-Airplane-61 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Look like the same issue and Mojang won't fix it https://bugs.mojang.com/browse/MC-225381
This could be usefull for create custom item with plugins

**Comment by lynxplay** [comment] 2021-09-03 11:54
I can reproduce this issue :+1: While a bundle like this, at least from looking at the current logic, should never exist in vanilla gameplay, I guess this is up for discussion if a fix should be implemented.

**Comment by NoahvdAa** [comment] 2021-09-03 12:03
Mojang doesn't seem interested in fixing this, even though it's a one line (even one character) fix. Fixing this would definitely benefit map/plugin creators that use "extended" bundles. Since this is also a super easy fix, I'd argue that this should be fixed in paper.

**Comment by lynxplay** [comment] 2021-09-03 12:04
Yea, I personally am inclined to believe it is a `i == 0` to `i <= 0` fix. I'll propose a PR and we can discuss it there.

**Comment by lynxplay** [comment] 2021-12-01 00:09
Closing this as 1.18 implemented a safeguard against this duplication bug (which was already only achievable through creative/command spawned in bundles).

The packet processing error still exists, if it is incredibly relevant, please open a new issue and we can PR from there on out, as a solution may fit into https://github.com/PaperMC/Paper/blob/master/patches/server/0785-Fix-Bukkit-NamespacedKey-shenanigans.patch.

**Closed as completed by lynxplay** 2021-12-01 00:09 UTC
Labels: type: bug, version: 1.17
