### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by hafarooki** [PaperMC/Paper#1345] opened 2018-08-18 02:16 UTC
### Link/paste of stack trace
https://gist.github.com/Miclebrick/bfcc146becbb73fe950fc02a7e9c6d63
### Plugin list:
Plugins (73): ActionHealth, AreaShop, AutoBroadcast, Battleship, BlocksHub, Bounty, BungeeTabListPlus, BuycraftX, CCM2, Citizens, CombatTagPlus, CommandNPC, Commerce, Contrivances, CoreProtect, CraftingStore, CustomRecipes, DiscordSRV, dynmap, Dynmap-GriefPrevention, EasyBackup, Elements, EmptyWorldGenerator, Environments, Erudition, Essentials, EssentialsSpawn, ExplosionRegen, FarmProtect, FastAsyncWorldEdit, Fe, GameBox, GemCrush, GlassDrop, GriefPrevention, Hologram, InventoryRollback, ItemTagger, KillStreaks, LagMonitor, Lift, LiteBans, LogicPuzzles, LuckPerms, MenuBuilder, Minesweeper, MP-GameBundle, Multiverse-Core, Nations, NetworkManagerBridge, OpenInv, PandaWire, ParticleLIB, PlaceholderAPI, PlugMan, Progression, ProtocolLib, RampenDrills, Rudiments, Shop, SimpleAPI, SimplePets, spark, StarLegacyWebPlugin, Starships, VanishNoPacket, Vault, Votifier, VotingPlugin, WhacAMole, WorldBorder, WorldEdit, WorldGuard
do I really have 73 plugins? Dang
### Actions to reproduce (if known):
idk dud it just happened randomly pls send cats to help
### Paper build number:
version=> [22:16:01 INFO]: This server is running Paper version git-Paper-1534 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[22:16:01 INFO]: Previous version: git-Paper-1524 (MC: 1.12.2)
[22:16:01 INFO]: You are 12 version(s) behind

this is my appeal for having cats sent to help, please consider sending cats

**Comment by zachbr** [comment] 2018-08-18 04:00
Duplicate of #954

**Closed as completed by zachbr** 2018-08-18 04:00 UTC
Labels: resolution: duplicate
