### ISSUE TITLE
Place a sign on snow

### ISSUE THREAD

**Issue by recycie** [PaperMC/Paper#1974] opened 2019-04-16 21:18 UTC
[04:11:51] [Server thread/FATAL]: Error executing task
java.lang.NullPointerException: null
	at net.minecraft.server.v1_13_R2.EntityPlayer.openSign(EntityPlayer.java:891) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:308) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:532) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1347) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-620]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[04:11:52] [Netty Server IO #3/DEBUG]: [io.netty.channel.nio.NioEventLoop] Selector.select() returned prematurely 3 times in a row for Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@7df34624.
[04:11:52] [Netty Server IO #0/DEBUG]: [io.netty.channel.nio.NioEventLoop] Selector.select() returned prematurely 3 times in a row for Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@d0191d9.

**Comment by recycie** [comment] 2019-04-16 21:19
Place a sign on the snow in creative mode

**Comment by BillyGalbreath** [comment] 2019-04-16 22:32
Duplicate of #1917 which #1963 fixes.

**Closed as completed** 2019-04-16 22:39 UTC
Labels: resolution: duplicate
