### ISSUE TITLE
item2chat broken going from build 445 to 498

### ISSUE THREAD

**Issue by s1h4d0w** [PaperMC/Paper#5257] opened 2021-02-26 15:54 UTC
### What behaviour is expected:
Players type `[item]` or `[inv]` to share the item they are holding or their whole inventory in chat. The `[item]` would be replaced by something like **Diamond Sword x1** that can be hovered over to show the stats and other information.

### What behaviour is observed:
Chat shows `[item]□playername`
![image](https://user-images.githubusercontent.com/5654654/109323060-56465280-7853-11eb-832a-d34632bdfbd6.png)

### Steps/models to reproduce:
Install item2chat and type [item] or [inv]

### Plugin list:
AdvancedAchievements, ArmoredElytra, AuctionHouse, AutoMessager, AutoRestart*, BetterRTP, ChatReaction, ClearLag, ConsoleSpamFix, CoreProtect, CustomHeads*, DeathCoordinates, DynamicShop, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Genie, GriefPrevention, GSit, Harbor, Herobrine, HolographicDisplays, InfernalMobs, Item2Chat, JetsSellChests, Jobs, JoinMessagePlus, JukeBox, KeepDeathDrop, LitePlaytimeRewards, LuckPerms, Multiverse-Core, MyCommand, nLogin, NoteBlockAPI, OpeNLogin, PhantomSMP, PlayerWarps, ProtocolLib, QuickShop, RestrictedCreative, ServerListPlus*, SilkSpawners, SkinsRestorer, SmoothTimber, Spartan, StackMob, SuperbVote, TradeSystem, Vault, Votifier, WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Paper version:
Paper version git-Paper-498 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Anything else:
Asked about it on discord, was told it had something to do with changes made in builds after 472. Went back to 472 and it's working again, assume it has something to do with the adventure update and `sendMessage(String)`?

**Comment by Proximyst** [comment] 2021-02-26 16:21
Duplicate of #5251

**Closed as completed by Proximyst** 2021-02-26 16:21 UTC
Labels: version: 1.16
