### ISSUE TITLE
Server crash Cannot cast TileEntityChest to MobSpawner

### ISSUE THREAD

**Issue by james090500** [PaperMC/Paper#2306] opened 2019-07-10 22:21 UTC
### Link/paste of stack trace
Latest.log - https://pastebin.com/xyW3MEmR
Crash Report - https://pastebin.com/CVCxsdFy

### Plugin list:
![image](https://user-images.githubusercontent.com/20372645/61009045-4cfc2f80-a369-11e9-8c6f-b3b5d3779e59.png)

### Actions to reproduce (if known):
Player where just using survival like normal. We have no plugins interacting with mob spawners so no idea why one is trying to cast to a chest

### Paper build number:
git-Paper-126 (MC: 1.14.2)

**Comment by Spottedleaf** [comment] 2019-07-10 22:22
duplicate of https://github.com/PaperMC/Paper/issues/2202

**Comment by james090500** [comment] 2019-07-10 22:24
> duplicate of #2202

My bad! I couldn't locate one. The more information the better i guess.

**Closed as completed** 2019-07-21 21:52 UTC
Labels: resolution: duplicate
