### ISSUE TITLE
/setworldspawn doesn't save yaw and pitch

### ISSUE THREAD

**Issue by bnt4** [PaperMC/Paper#4772] opened 2020-11-15 11:00 UTC
### What behaviour is expected:
To save the yaw and pitch (also this is not working with world.setSpawnLocation(..);

### What behaviour is observed:
It saves the spawn location, but without yaw and pitch

### Plugin list:
My world manager plugin

### Paper version:
This server is running Paper version git-Paper-279 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Anything else:
So when I want to set the worldspawn, no matter if I do it with /setworldspawn or use my system (where I set world.setSpawnLocation(..); so the normal Bukkit world), it's not working. It doesn't save yaw and pitch

**Comment by Proximyst** [comment] 2020-11-15 11:03
Duplicate of #4212.

**Closed as completed by Proximyst** 2020-11-15 11:03 UTC
Labels: resolution: duplicate, version: 1.16
