### ISSUE TITLE
"allow-unsafe-end-portal-teleportation" don't working

### ISSUE THREAD

**Issue by AluoExpiry** [PaperMC/Paper#10976] opened 2024-06-24 14:36 UTC
### Expected behavior

sand duplicator it's working

### Observed/Actual behavior

sand duplicator don't working.
But it works as expected on a vanilla multiplayer server.

### Steps/models to reproduce

build a sand duplicator or download this world:
[https%3A%2F%2Fwww.mediafire.com%2Ffile%2Fzqkh8oq7jujdou0%2FMax%2BEfficiency%2BSand%2BDuper.zip%2Ffile&v=lCYR2FN20lk](https://www.mediafire.com/file/zqkh8oq7jujdou0/Max+Efficiency+Sand+Duper.zip/file&v=lCYR2FN20lk)

### Plugin and Datapack List

BoundlessForging-1.0-SNAPSHOT
CleanPing
ColorfulChat-2.1
LagFixer
LuckPerms-Bukkit-5.4.116
PlayerDoll-1.29
tabtps-spigot-1.3.24

### Paper version

1.21 build #37
![image](https://github.com/PaperMC/Paper/assets/26159636/34ee69b8-b903-4c9c-be8c-745373236a9d)

### Other

![image](https://github.com/PaperMC/Paper/assets/26159636/490a0cff-0aac-4a83-8c44-0dcaf88ba2dc)

**Comment by AluoExpiry** [comment] 2024-07-01 16:43
I successfully built and tested a machine on the original 1.21 server. However, upon migrating the server to Paper, the machine ceased to function. I initially suspected an issue with the test map provided in the documentation, but further testing confirmed the problem persists.

**Comment by ThatGamerBlue** [comment] 2024-07-04 14:16
Given concerns about the new entity stacks being able to teleport thing, I tested an older design for a sand duper and I'm unable to reproduce this issue running Paper version 42. This attached design works dupes sand both in singleplayer and on the Paper server, running no plugins or datapacks, with the allow-unsage-end-portal-teleportation option set to true.
[12GT Sand Duper by Scorpio.zip](https://github.com/user-attachments/files/16100000/12GT.Sand.Duper.by.Scorpio.zip)

**Comment by ConanGuy** [comment] 2024-07-04 14:54
It seems to come from the Multiverse NetherPortals plugin. I have the same bug with this plugin and it fixes it by removing it. 

I don't know how to keep the plugin and fix the bug at the same time.

**Comment by lynxplay** [comment] 2024-07-06 19:48
Going to close this, as sand duping appears to be working for me and others ^

**Closed by lynxplay** 2024-07-06 19:48 UTC
Labels: type: bug, status: needs triage, version: 1.21
