### ISSUE TITLE
Villager

### ISSUE THREAD

**Issue by mythiccals** [PaperMC/Paper#3514] opened 2020-06-06 18:05 UTC
### What behaviour is expected:
___What you expected to see___

The villager should recognise the workstation and work hours and change to it
### What behaviour is observed:
___What you actually saw___
About a quarter of the trading hall were able to change to their profession, earlier this issue could be resolved by logging out and in all at the same time, reloading the chunks. I have no entity optimiser or any other addon plugins that could affect this either. 
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
https://prnt.sc/sv0b2m
### Plugin list:
___A list of your plugins___
AdminOnly, Admintools3, AdvancedBan, AluminumVanish, BuycraftX, ClearLag, CoreProtect, CosmicVaults, CrateReloaded, DeadChest, DynamicMonsterCap, dynmap, eGlow, Essentials, GriefPrevention, iClearChat, JoinMessage, LuckPerms, Minepacks, MOTD, MyPet, NewTag, OpenInv,, PlayerParticles, Shopkeepers, ShulkerPack, UltimateShops, Vault, Votifier, VotingPlugin, and WorldEdit.
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
running paper version git-Paper-322 (MC: 1.15.2) 
### Anything else:
___Anything else you think may help us resolve the problem___
Half of the trading hall was able to convert, the method we found to fix I mentioned above but today that has stopped working after a ton of attemps!?

If theres some setting I need to change then please do tell me!

 - the trading hall method definitely works on a vanilla 1.15 server, I just tried testing it.

**Comment by electronicboy** [comment] 2020-06-06 18:09
closing as a duplicate of #2959, there are many dozen issues with how villagers work all the way up the chain

**Closed as completed by electronicboy** 2020-06-06 18:09 UTC
