### ISSUE TITLE
Reloading datapacks unregisters recipes added via Bukkit#addRecipe (SPIGOT-6084)

### ISSUE THREAD

**Issue by dfsek** [PaperMC/Paper#4244] opened 2020-08-29 19:54 UTC
### What behaviour is expected:
/minecraft:reload or Bukkit#reloadData can be executed and recipes will still work afterwards

### What behaviour is observed:
After either action is performed, recipes are unregistered and can no longer be crafted.

### Steps/models to reproduce:
1. Add a recipe via a plugin, using Bukkit#addRecipe
2. execute `/minecraft:reload`
3. Attempt to craft the recipe

### Plugin list:
None

### Paper version:
git-Paper-161 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Anything else:
[Spigot Issue](https://hub.spigotmc.org/jira/browse/SPIGOT-6084)

**Comment by JanTuck** [comment] 2020-08-29 20:19
Why would you expect it to rerun your code where you added the recipe? For me this looks to be working as intended’ish.

**Comment by electronicboy** [comment] 2020-08-29 20:20
The behavior is 100% expected, what would ideally be done here is an event to allow plugins to re-register when this happens

**Comment by MiniDigger** [comment] 2020-08-31 08:49
should we refactor this ticket into a feature request then?

**Comment by electronicboy** [comment] 2020-08-31 09:33
Closing, there is actually already a generic reload event in the server, no need to add another event for this case specifically unless somebody can determine a reason which can't be factored in to existing API;

**Comment by electronicboy** [comment] 2020-08-31 09:34
Wait, it's too early, I guess there isn't one for specifically reloading recipe data, err...

**Comment by dfsek** [comment] 2020-08-31 22:22
Now that I think about it, that does indeed make sense. If you would like, I can refactor this into a feature request for a RecipeReloadEvent or something similar.

**Closed as completed** 2021-01-03 18:39 UTC
Labels: status: accepted, resolution: works as intended, version: 1.16, upstream: spigot
