### ISSUE TITLE
Multiple issues with Furnaces

### ISSUE THREAD

**Issue by Aaron2550** [PaperMC/Paper#4697] opened 2020-10-27 15:27 UTC
### What behaviour is expected:
Using the setCookSpeedMultiplier method on a Furnace/BlastFurnace/Smoker should set the actual multiplier. The campfire is missing this method completly.

### What behaviour is observed:
The furnace no longer cooks anything and just uses up fuel, thes blastfurnace and smoker do the exact same

### Steps/models to reproduce:
Use test code, where block is a BlockState of well, the furnace block:
```java
Furnace furnace = (Furnace) block;
furnace.setCookSpeedMultiplier(0.5d);
furnace.update();
```
NOTE: when setting the multiplier to 1.0, everything works fine. I have not tried any multipliers above 1.0
See issue: [https://stronghold.host/media/dHBGPYu1.png](https://stronghold.host/media/dHBGPYu1.png)

### Plugin list:
Only my test plugin

### Paper version:
```
This server is running Paper version git-Paper-247 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Checking version, please wait...
You are 1 version(s) behind
```

### Anything else:
no idea, sorry

**Comment by electronicboy** [comment] 2020-10-27 15:31
This is down to the servers implementation, the counter is an int, not a double, meaning that anything that's not == an int will be lost

**Comment by Aaron2550** [comment] 2020-10-27 15:32
Hmm, well the javadocs say its a double and so i assumed that would work... 
 [https://papermc.io/javadocs/paper/1.16/org/bukkit/block/Furnace.html#getCookSpeedMultiplier--](https://papermc.io/javadocs/paper/1.16/org/bukkit/block/Furnace.html#getCookSpeedMultiplier--)

**Comment by Aaron2550** [comment] 2020-10-27 16:03
So what are the odds of this getting fixed? Is this an issue with vanilla or Bukkit/Spigot/Paper?

**Comment by ericsu14** [comment] 2020-10-28 03:00
Hi guys! I have attempted to look into this issue today, but @electronicboy is right; the internal counter, `cookTime`, is declared as an integer in the nms codebase (this can be found in `src/main/java/net/minecraft/server/TileEntityFurnace.java`). What makes this issue tricky to fix is that `cookTime `is also declared as a public data-member. One easy fix is to change that counter variable to a double, but that may cause some unintended side effects towards any class depending on it.

What do you guys think?

**Comment by MrIvanPlays** [comment] 2020-10-30 10:04
> One easy fix is to change that counter variable to a double, but that may cause some unintended side effects towards any class depending on it.

or alternatively add a new method in bukkit api that accepts integer and deprecate the current one?

**Comment by Aaron2550** [comment] 2020-10-30 12:41
That's the easiest no doubt, but then we won't be able to make slow furnaces that easily

**Comment by BillyGalbreath** [comment] 2020-10-30 14:31
I had a fix for this, it just accidentally got closed

https://github.com/PaperMC/Paper/pull/1984

**Comment by ericsu14** [comment] 2020-10-30 18:32
> I had a fix for this, it just accidentally got closed
> 
> #1984

I am actually using your commit as a base for my fix! I almost got it working, but currently having visual glitches where the progress bar is not accurately reflecting the changes made to the furnace's cook speed multiplier.

Also found out that changing the furnace's cookTime to a double is a pretty destructive change, considering that it is passed onto several functions where it is expecting it to be an integer.

**Comment by electronicboy** [comment] 2020-10-30 18:39
From internal dev;
```
[3:17 PM] zzzCat: For the furnace thing, I would actually maybe just migrate the backing counter to a double, save it back as an int with a min of 1 just to save face for vanilla, and save our own copy of the double in our own key
```

You'd need to convert back to an int for varying calls to the client, etc, but converting the timer to a double internally seems like the better option

**Comment by Aaron2550** [comment] 2020-11-03 16:10
Is there another way to slow down furnaces without breaking the the smelting animation? Since, if i understood you right, the minimum value will be one meaning it can only be set faster but not slower.

**Comment by ericsu14** [comment] 2020-11-03 16:26
> Is there another way to slow down furnaces without breaking the the smelting animation? Since, if i understood you right, the minimum value will be one meaning it can only be set faster but not slower.

I already have a working solution to that problem in my recent pull request! I discovered that the smelting animation is scaled to whatever totalCookTime is set to. I also noticed that smelting code calls an internal function, getRecipeCookingTime(), on the end of each smelting operation to update the total cooking time with the next item to be smelted.

Thus, one way to fix this is to modify the internal getRecipeCookingTime() function and divide its final output by our cookSpeedMultiplier, which will give us the furnace cook speeds we want!

**Comment by Chew** [comment] 2020-11-14 19:33
Appears to be a duplicate of, or at least related to, #1983

**Comment by Aaron2550** [comment] 2020-11-14 21:26
Huh, I thought I searched all open issues

**Comment by Chew** [comment] 2020-11-14 22:32
All good, this one superseded that one anyway and is more descriptive. Thank you for the report though :)

**Closed as completed** 2021-03-03 20:08 UTC
Labels: type: bug, help wanted, status: accepted, good first issue, version: 1.16, upstream: bukkit
