### ISSUE TITLE
Invisible Mobs

### ISSUE THREAD

**Issue by Saffanity** [PaperMC/Paper#2339] opened 2019-07-20 19:21 UTC
I just updated from version 131 to 135 and everyone on the server has an issue with mobs be invisible. Can I please get some assistance?

**Comment by electronicboy** [comment] 2019-07-20 19:28
You forgot to fill the issue template, probably a duplicate of the closed issues related to this too, update your plugins

**Closed as completed by electronicboy** 2019-07-20 19:28 UTC

**Comment by Saffanity** [comment] 2019-07-20 19:33
I don't like the fact you just closed my ticket like that, my plugins are updated i just updated all of them today. I didn't see a template for issues.

**Comment by electronicboy** [comment] 2019-07-20 19:34
When you click "new issue" it will present you with a list of templates, without filling in the template, we have no information to assist you, given that all reported instances of this have been attributed to plugins such as tab, it's more than likely not an issue on our side

if you wanna create a new issue filling out the template properly you're more than welcome to, but I'd heavily suggest trying without plugins first
