### ISSUE TITLE
Voluntary Exile advencement isn't triggered

### ISSUE THREAD

**Issue by crizyx** [PaperMC/Paper#4677] opened 2020-10-21 12:47 UTC
### What behaviour is expected:
___When i kill a raid captain the advencement "voluntary exile" is granted.___

### What behaviour is observed:
___When i kill a raid captain the advencement "voluntary exile" isn't granted.___

### Steps/models to reproduce:
___Find a Pillager Outpost and kill the raid captain (pillager with hat banner).___

### Plugin list:
___Nothing.___

### Paper version:
```JAVA
> version
[14:42:12 INFO]: This server is running Paper version git-Paper-244 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[14:42:12 INFO]: Checking version, please wait...
[14:42:12 INFO]: Previous version: git-Paper-231 (MC: 1.16.3)
[14:42:12 INFO]: You are running the latest version
```

### Anything else:
___On spigot 1.16.3 the advencement is granted. Maybe the spawn rate of patrols can be affected because I haven't seen any of them.___

**Comment by electronicboy** [comment] 2020-10-21 12:49
Duplicate of #3729, please use the search feature

**Closed as completed by electronicboy** 2020-10-21 12:49 UTC
Labels: resolution: duplicate
