### ISSUE TITLE
Budded TNT Updating When Chunk is Unloaded and Reloaded

### ISSUE THREAD

**Issue by Vin-doe** [PaperMC/Paper#6233] opened 2021-07-20 12:11 UTC
### Expected behavior

When you have a budded TNT for example in a TNT duplicator, it should only update when some interaction with it is caused. It should not update when the chunk the budded TNT is in is unloaded and reloaded.

### Observed/Actual behavior

When I logged out and logged back in after a couple minutes to allow for the chunks to unload and reload, the budded TNT in a TNT duplicator was updated and such was set off and exploded.

### Steps/models to reproduce

- Create a budded TNT by placing a TNT with a block on top of it, then place a minecart on a detector rail beside the top block and push it in with a piston. If this description is confusing there are plenty of videos describing how to make a TNT duplicator.
- Log out of the server for 2 - 3 minutes to ensure the chunks are unloaded.
- When you log back in, the TNT will update and be set alight.

This may take a couple attempts to recreate as the unloading of chunks may be unpredictable.

### Plugin list

No plugins loaded on the server when testing.

### Paper version

Paper version #119 which as of creating this report is the latest version.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

In the server config, I have all settings to the default except for the setting: allow-piston-duplication: true

**I would like to inform you that this is a bug regarding the budding of TNT and not the duplication of primed TNT which I know is unsupported.**

**Comment by kennytv** [comment] 2021-07-20 12:13
Duplicate of https://github.com/PaperMC/Paper/issues/6168

**Closed as completed by kennytv** 2021-07-20 12:13 UTC
Labels: resolution: duplicate
