### ISSUE TITLE
POI Data Error

### ISSUE THREAD

**Issue by Strahilchu** [PaperMC/Paper#4355] opened 2020-09-22 18:21 UTC
#4170 # Link/paste of stack trace

[17:37:16 ERROR]: POI data mismatch: never registered at BlockPosition{x=1375, y=63, z=930}
[17:37:16 ERROR]: POI data mismatch: never registered at BlockPosition{x=1375, y=63, z=930}
[17:37:18 ERROR]: POI data mismatch: never registered at BlockPosition{x=1381, y=63, z=930}
[17:37:20 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:20 ERROR]: POI data mismatch: never registered at BlockPosition{x=1392, y=63, z=931}
[17:37:22 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:22 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:22 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:22 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:22 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:23 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:23 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:23 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:23 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:24 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:24 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:24 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:25 ERROR]: POI data mismatch: never registered at BlockPosition{x=1390, y=63, z=930}
[17:37:26 ERROR]: POI data mismatch: never registered at BlockPosition{x=1385, y=63, z=932}
[17:37:27 ERROR]: POI data mismatch: never registered at BlockPosition{x=1385, y=64, z=931}
[17:37:27 ERROR]: POI data mismatch: never registered at BlockPosition{x=1387, y=63, z=935}
[17:37:28 ERROR]: POI data mismatch: never registered at BlockPosition{x=1387, y=63, z=933}
[17:37:28 ERROR]: POI data mismatch: never registered at BlockPosition{x=1384, y=63, z=933}
[17:37:28 ERROR]: POI data mismatch: never registered at BlockPosition{x=1384, y=63, z=933}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1382, y=63, z=932}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1381, y=63, z=932}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1380, y=63, z=932}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1379, y=63, z=932}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1379, y=63, z=932}
[17:37:29 ERROR]: POI data mismatch: never registered at BlockPosition{x=1378, y=63, z=932}
[17:37:30 ERROR]: POI data mismatch: never registered at BlockPosition{x=1377, y=63, z=932}
[17:37:30 ERROR]: POI data mismatch: never registered at BlockPosition{x=1376, y=63, z=932}
[17:37:30 ERROR]: POI data mismatch: never registered at BlockPosition{x=1376, y=63, z=932}
[17:37:30 ERROR]: POI data mismatch: never registered at BlockPosition{x=1375, y=63, z=932}
[17:37:30 ERROR]: POI data mismatch: never registered at BlockPosition{x=1374, y=63, z=932}
[17:37:31 ERROR]: POI data mismatch: never registered at BlockPosition{x=1374, y=63, z=932}
[17:37:31 ERROR]: POI data mismatch: never registered at BlockPosition{x=1373, y=63, z=932}
[17:37:31 ERROR]: POI data mismatch: never registered at BlockPosition{x=1372, y=63, z=932}
[17:37:31 ERROR]: POI data mismatch: never registered at BlockPosition{x=1371, y=63, z=932}
[17:37:32 ERROR]: POI data mismatch: never registered at BlockPosition{x=1371, y=63, z=932}
[17:37:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=1374, y=63, z=919}
[17:37:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=1377, y=63, z=921}
[17:37:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=1377, y=63, z=922}
[17:37:52 ERROR]: POI data mismatch: never registered at BlockPosition{x=1385, y=63, z=922}
[17:37:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=1373, y=62, z=918}
[17:37:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=1370, y=63, z=920}

### Plugin list:
Autorank, BetterRTP, ChatControl, ChestShop, CommandSigns, Elevator, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, Graves, GroupManager, HolographicDisplays, Inventory, Jobs, LagAssist, MarriageMaster, mcMMO, OpenInv, PlaceItemsOnGroundRebuilt, PlugMan, PvPManager, SinglePlayerSleep, spark, Spartan, StatsSB, StopNetherTrap, TAB, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known):
Happens randomly, I teleported to those coordinates and there was nothing but water.

### Paper version:
1.16.3 #204

**Comment by Proximyst** [comment] 2020-09-27 16:34
Duplicate of #4018

**Closed as completed by Proximyst** 2020-09-27 16:34 UTC
Labels: resolution: duplicate, version: 1.16
