### ISSUE TITLE
Some player maybe crashed my server with villager ?

### ISSUE THREAD

**Issue by Stree7Man** [PaperMC/Paper#5408] opened 2021-03-24 03:51 UTC
### Stack trace

https://paste.gg/p/anonymous/c0d4ff3fbcf04a758d0c5d6530c9e743

### Plugin list

Plugins (43): AuctionHouse, AuthMe, ChestShop, Citizens, ColoredAnvils*, CoreProtect, CrateReloaded, DeluxeChat, EntityTrackerFixer, Essentials, EssentialsSpawn, HeadDatabase, HolographicDisplays, HolographicExtension, Jobs, KitPreview, LeaderHeadsRevamped, LiteBans, LuckPerms, mcMMO, Multiverse-Core, NoFlyZone, PL-Hide-Pro, PlaceholderAPI, PlayerVaults, ProtocolLib, PvPManager, Residence, ShopGUIPlus, Simple-Info*, SkinsRestorer, SpigotGuard, SuperbVote, TAB, TryMe, Vault, VillagerOptimiser, VoidGenerator, VoteParty, Votifier, W-Store, WorldEdit, WorldGuard

### Actions to reproduce (if known)

The server was crashed by some player I think with villager ,because in the chat he says this.

### Paper version

This server is running Paper version git-Paper-553 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 13 version(s) behind
Previous version: git-Paper-551 (MC: 1.16.5)

### Agreements

- [x] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Proximyst** [comment] 2021-03-24 05:08
Server is just overloaded. Possibly a super large hotbox somewhere. We can't reproduce this without any actual steps either, so closing.

> You are 13 version(s) behind
> I am running the latest version of Paper available from https://papermc.io/downloads.

Lies get you ✨ nowhere ✨.

**Closed as completed by Proximyst** 2021-03-24 05:08 UTC
Labels: version: 1.16
