### ISSUE TITLE
Changes in MaximumRepairCost for Anvil Rename cause inconsistency

### ISSUE THREAD

**Issue by Doc94** [PaperMC/Paper#6346] opened 2021-08-06 19:03 UTC
### Expected behavior

If in `AnvilInventory` i use `setMaximumRepairCost` i can use anvil over the vanilla limit when enchant or rename item.

### Observed/Actual behavior

When try to rename a item with cost 40 (for example) the GUI show cost 39 but if i print the cost in the AnvilInventory show another value and if click the result item the event is cancel but the server take the cost show in anvil GUI.

![image](https://user-images.githubusercontent.com/3602279/128559216-ff688d84-15f3-424b-b385-e2c8619f68e0.png)
![image](https://user-images.githubusercontent.com/3602279/128559228-daa3865a-d2b7-401e-a53b-b6417762552b.png)

### Steps/models to reproduce

- Enchant a item (survival for make the item change the cost nbt) in anvil
- Rename the item in anvil

Code use for check: https://gist.github.com/Doc94/92f44d9ef65d890af8af7a524e7f1be9

### Plugin list

ConterCraft (Where i change the maxcost), CoreProtect, FastAsyncWorldEdit (WorldEdit), HackedCore*, HackedServer*, LibsDisguises, LuckPerms, PlugMan, ProtocolLib

### Paper version

git-Paper-160 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a125ee)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This is a craftbukkit issue (https://hub.spigotmc.org/jira/browse/SPIGOT-6686) but i dont have response for know if this is normal because maybe dont understand how to work the anvil or a bug.

**Comment by Chew** [comment] 2021-08-06 21:41
Duplicate of #6253?

**Comment by Doc94** [comment] 2021-08-06 21:54
> Duplicate of #6253?

Not sure... in this issue not see any about the setMaximumRepairCost and in my tests this only happen when touch this.. in normal cases the anvil cancel and level are not taken.

**Closed as completed** 2021-08-27 09:51 UTC
Labels: type: bug, version: 1.17
