### ISSUE TITLE
Error executing task on Server: NullPointerException

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#2930] opened 2020-02-03 08:52 UTC
```
[FATAL] Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1363) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:811) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:496) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInTeleportAccept.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInTeleportAccept.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-87]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

1m 27s later, without stacktrace:

```
[FATAL] Error executing task on Server
java.lang.NullPointerException: null
```

Before the error occurred, there were a few players online, and some were in the Nether.
Those in the Nether were being slain by Zombie Pigmen.
10s after the error occurred, a player asked if somebody had died in the Nether, and reported that drops had appeared in the Overworld from the portal, and that he was being attacked by many Zombie Pigmen (in which world I don't know).

**Comment by HexedHero** [comment] 2020-02-03 10:02
Same issue here, had 3/4 of them after almost 2 days uptime, restart fixed.

**Comment by Spottedleaf** [comment] 2020-02-09 01:07
duplicate of https://github.com/PaperMC/Paper/issues/2803

**Closed as completed** 2020-02-09 01:09 UTC
Labels: resolution: duplicate
