### ISSUE TITLE
Furnace cook speeds are rounded to the nearest int.

### ISSUE THREAD

**Issue by KSashaDF** [PaperMC/Paper#1983] opened 2019-04-20 07:00 UTC
The Furnace.setCookSpeedMultiplier(double multiplier) method added my Paper says it accepts any double value between 0 and 200, however the given value gets rounded to the nearest integer internally.

### What behaviour is expected:
The furnace smelts items at the given decimal multiplier.

### What behaviour is observed:
The furnace smelts items at a rounded speed multiplier.

### Plugin list:
BuyCraftX, ChatControl, CoreProtect, FAWE, Worldedit, LagMonitor, LibsDisguises, LiteBans, and ProtocolLib.

### Paper build number:
Build 621

### Anything else:
The furnace cook speed multiplier NBT tag appears to get correctly set and is not the issue.

**Comment by BillyGalbreath** [comment] 2019-04-20 07:12
Because it's being truncated due to math casting to an int.

```
this.cookTime += cookSpeedMultiplier; // Paper - cook speed multiplier API
```

`cookTime` is an int. Not sure why the API set the multiplier field as a double.. kinda weird

**Comment by KSashaDF** [comment] 2019-04-20 07:14
Yes sorry, I soon realized that after I created this issue.

**Comment by BillyGalbreath** [comment] 2019-04-20 07:16
Well, you cant use non-int modifier here. Its counting in ticks, there is no such thing as a partial tick. The modifier is simply incrementing the cook time by a set number of ticks (default is 1 tick).

If anything needs to be fixed is that the API needs to use `int` instead of `double` to prevent this type of confusion in the future.

**Comment by KSashaDF** [comment] 2019-04-20 07:17
No, this is a multiplier not a direct modifier, so decimals are important here if you wish to have a slower furnace for example.

**Comment by BillyGalbreath** [comment] 2019-04-20 07:20
If you want a slower furnace use the API to set a higher cook time with `Furnace#setCookTimeTotal(int)`

Example: If you want something to go at half speed do this:

```
furnace.setCookTimeTotal(furnace.getCookTimeTotal() * 2);
```

**Comment by KSashaDF** [comment] 2019-04-20 07:22
Oh hmm, I must have an outdated API jar then, I did not know that existed. Thanks.

**Comment by KSashaDF** [comment] 2019-04-20 07:39
Nevermind, the cook time total value resets to 200 when the furnace finishes smelting an item, so having this multiplier working would be more convenient.

**Comment by BillyGalbreath** [comment] 2019-04-20 07:52
Update the total cook time in the `FurnaceSmeltEvent`.

The total cook time is set every time an item starts to burn according to that item's furnace recipe (or 200 as a default fallback)

```
    private int s() {
        FurnaceRecipe furnacerecipe = (this.hasWorld()) ? (FurnaceRecipe) this.world.getCraftingManager().b(this, this.world) : null; // CraftBukkit - SPIGOT-4302
        return furnacerecipe != null ? furnacerecipe.h() : 200;
    }
```

**Comment by Proximyst** [comment] 2020-11-14 19:36
Closing as duplicate of #4697 as that issue also outlines issues with blocks introduced after this issue was opened.

**Closed as completed by Proximyst** 2020-11-14 19:36 UTC
Labels: type: bug, resolution: superseded
