### ISSUE TITLE
Adventure - Hide and seek sign problem

### ISSUE THREAD

**Issue by slvlr** [PaperMC/Paper#5309] opened 2021-03-05 16:46 UTC
### What behaviour is expected:
Players should be able to right click the sign, and then join the hide and seek game.
When creating the sign, it should format correctly and be usable.

Correct visual of a disabled arena:
![image](https://user-images.githubusercontent.com/8680731/110146206-31f9f100-7dd2-11eb-8b01-06b85517f6b4.png)

### What behaviour is observed:
All existing signs remained the same visually, but could not be interacted with.
When breaking the sign, and recreating it, it formatted incorrectly and did not allow me to join a game.

Incorrect visual of a newly created disabled arena:
![image](https://user-images.githubusercontent.com/8680731/110146337-58b82780-7dd2-11eb-8061-4c06996dcace.png)

### Steps/models to reproduce:
Updated to Post Adventure paper version.

### Plugin list:
![image](https://user-images.githubusercontent.com/8680731/110146403-6f5e7e80-7dd2-11eb-8f63-01c0e8f58d79.png)

### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
![image](https://user-images.githubusercontent.com/8680731/110146080-0a0a8d80-7dd2-11eb-8e5d-b523a5de5e2e.png)

### Anything else:
___Anything else you think may help us resolve the problem___
![image](https://user-images.githubusercontent.com/8680731/110146103-12fb5f00-7dd2-11eb-8da4-4f0ab131a1f1.png)
https://www.spigotmc.org/resources/hideandseek.9777/

**Comment by JRoy** [comment] 2021-03-05 16:47
Could you try this build: https://drive.google.com/file/d/184-xZmgv3EWhwmPM1Rv0kuUOHZoLVMt5/view?usp=sharing

and see if that fixes your issue and doesn't cause any other unexpected behavior?

cc @kashike

**Comment by slvlr** [comment] 2021-03-05 16:50
@JRoy My PC doesn't allow downloads from GoogleDrive for some reason. Is there another URL at all please?

Is this version a dev build after build 526, or does it have less updates?

**Comment by JRoy** [comment] 2021-03-05 16:54
@slvlr here https://mega.nz/file/vwNHHAJR#77dsy1HMCTzFHmAfXJsdfVFihKy9MT43Pz7L9B_szHs

**Comment by Proximyst** [comment] 2021-03-05 17:03
Would like to add that the given JAR file (SHA512 `c402e186540e0956bdfdba0c9c2aaca472c9d78d97380a52f709ec829ba4fa28698566d887b90cc92b932bd7d0d691d5b34696a8b2e01d8cc4bc5c435baf26a1`) is an _official_ test build. Exactly what commit it's based on I have no idea, but it's very recent.

**Comment by JRoy** [comment] 2021-03-05 17:12
to add it's kash's build from #paper-test-builds on discord

**Comment by slvlr** [comment] 2021-03-05 17:37
![image](https://user-images.githubusercontent.com/8680731/110152188-50afb600-7dd9-11eb-8b88-9deebca700e5.png)

It gets stuck at waiting. Doesn't let me use the sign. 
![image](https://user-images.githubusercontent.com/8680731/110152183-4ee5f280-7dd9-11eb-8c80-6e8222f311aa.png)

if I break the sign, and then make a new one, it says that you cannot have more than 1 sign. It isn't registering that I broke the previous sign, yet this did work before updating paper.

**Comment by JRoy** [comment] 2021-03-05 17:41
This seems like an error of the plugin and not Paper but since the plugin is able to detect the sign I guess it works? Unless you're getting errors in console?

**Comment by slvlr** [comment] 2021-03-05 17:43
I am not getting any errors in console. If this is the plugin, any advice to what the dev must change?
Please keep in mind, this did work prior to updating paper, and continues to work if I back-date paper builds.

**Comment by slvlr** [comment] 2021-03-05 21:33
@JRoy Not sure if this is related or not, but death messages are supposed to show color, and you should also be able to hover over the weapon to see it's info. Neither of these features are now working after updating to build 526. 
![image](https://user-images.githubusercontent.com/8680731/110175916-6681a300-7dfa-11eb-943a-f4dff1dabb94.png)

**Comment by andrewkm** [comment] 2021-03-06 07:26
> Could you try this build: https://drive.google.com/file/d/184-xZmgv3EWhwmPM1Rv0kuUOHZoLVMt5/view?usp=sharing
> 
> and see if that fixes your issue and doesn't cause any other unexpected behavior?
> 
> cc @kashike

This build fixed all our issues.
Paper 526 (latest) has broken signs all over the place completely.
With this build all is well again. Thank you. :)

**Comment by slvlr** [comment] 2021-03-07 14:36
This build fixes a part of the problem, but not the full issue.
Creating the new join signs still does not work properly. The format is still incorrect like the images above, and it does not let people join via these signs.

I used core protect to roll back my changes in the past few days, which managed to set the signs back to the old format.
I clicked the sign and I successfully joined the game. 
I then changed my paper build to 529 to test, and then I was unable to join the signs again.

summary:
This build fixes already created join signs, but does not let you create new join signs. 

@kashike @andrewkm

**Comment by kashike** [comment] 2021-03-09 01:13
This should be fixed as of https://github.com/PaperMC/Paper/commit/27a8d99ec4f11d1facccb6d68b120b67b74b16a2 and https://github.com/PaperMC/Paper/commit/7f72c4675bf18f1dc1fd1fea2737590fa41dc7a7.

**Closed as completed by kashike** 2021-03-09 01:13 UTC
Labels: type: bug, status: accepted, status: in progress, version: 1.16

**Comment by slvlr** [comment] 2021-03-09 20:55
I was unable to verify if this was fixed due to when updating I got major issues.

Updated to build 540:

![image](https://user-images.githubusercontent.com/8680731/110536070-f2583f80-8118-11eb-90d0-8ab54033674e.png)

Logs: https://pastebin.com/e5SqiQY4


I have opened a new ticket #5331 as unsure if related. 



Edit: I can confirm the sign issue is now fixed.

**Comment by electronicboy** [comment] 2021-03-09 20:58
Try the build before the latest
