### ISSUE TITLE
Fishing bobbers not disappearing when disconnecting

### ISSUE THREAD

**Issue by ligix** [PaperMC/Paper#5288] opened 2021-03-01 15:00 UTC
### What behaviour is expected:
The fishing bobber should disappear when logging out

### What behaviour is observed:
It stays there, it allows to have a lot of them

### Steps/models to reproduce:
throw a fishing rod in some water, disconnect, reconnect, right click again and you'll have 2 bobbers. Disconnect, reconnect and right click again and again...

### Plugin list:
None

### Paper version:
"This server is running Paper version git-Paper-406 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Checking version, please wait...
You are 10 version(s) behind"

### Anything else:
Here is a screen of what happens:
![image](https://user-images.githubusercontent.com/51802433/109514896-c862a580-7aa6-11eb-9a28-9b2ca47e4213.png)

**Comment by Titaniumtown** [comment] 2021-03-01 16:13
You're on an outdated version of paper. Update and see if you can reproduce.

**Comment by aurorasmiles** [comment] 2021-03-01 16:42
Reproduceable on the latest build.

**Comment by Trigary** [comment] 2021-03-11 20:22
Unable to reproduce on 808bd9198

**Comment by Proximyst** [comment] 2021-03-12 06:53
Also unable to reproduce. Closing as invalid.

**Closed as completed by Proximyst** 2021-03-12 06:53 UTC
Labels: type: bug, resolution: cannot reproduce, status: accepted, version: 1.16
