### ISSUE TITLE
Waterlogged chests not updating Block Entity Data

### ISSUE THREAD

**Issue by sombraguerrero** [PaperMC/Paper#2705] opened 2019-11-24 06:55 UTC
I realize this could very well be, (probably is) a Buklkit issue, though in this case, I'm not sure how to appropriately log this bug to them, so I thought I'd put it here for discussion. Basically, when a chest is waterlogged:true, the following error is produced when the chest is destroyed:

[00:45:45 ERROR]: Block at -2,013, 63, 555 is Block{minecraft:water} but has net.minecraft.server.v1_14_R1.TileEntityChest@6f95e217. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

I've validated that this does not happen in Vanilla 1.14.4, but it is indeed happening in Paper 226 and presumably, it would also be happening in Spigot, so it likely is an issue with the Bukkit APIs.

**Comment by electronicboy** [comment] 2019-11-24 06:58
How was this chest placed? Can you replicate this on a fresh server without plugins? That error is basically saying that a chest TE exists where a water block is, suggests that either the world was already in an inconsistent state, or there is some deeper issue

> this does not happen in vanilla

Well, no; That will never happen as bukkit does not exist in vanilla

**Comment by sombraguerrero** [comment] 2019-11-24 07:30
Yes, it does happen on a fresh server with no plugins loaded.
The waterlogged attribute seems to set itself to true more liberally in Paper and Bukkit-based servers of similar make than Vanilla. I can place the chest in any open, underwater space where it will be automatically walterlogged:true and the error will come as soon as I destroy it. I can also place it in no water, pour water over it or source it from above, and it will set waterlogged to true and the error will be produced.

In a more realistic example, say the chest started out in a sunken ship, which of course is airtight. Then let's say I removed the ship completely from around the chest, leaving it in open water, then destroy it. This too would produce the error, and that is actually how I originally produced it.

**Comment by kickash32** [comment] 2019-12-25 00:12
Can confirm, happens in Paper-29 1.15 as well.
`[Server thread/ERROR]: Block at 341, 75, -219 is Block{minecraft:water} but has net.minecraft.server.v1_15_R1.TileEntityChest@2b3ebabc. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

**Comment by Proximyst** [comment] 2020-10-02 13:53
Duplicate of #3318.

**Closed as completed by Proximyst** 2020-10-02 13:53 UTC
