### ISSUE TITLE
world.getHighestBlock does not work

### ISSUE THREAD

**Issue by DevJoey** [PaperMC/Paper#2925] opened 2020-02-01 19:38 UTC
### What behaviour is expected:
___What you expected to see___
If i stand under a block and get worlds highest block at the location it returns air.

### What behaviour is observed:
___What you actually saw___
I dont know

### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Use a plugin to get the highest block
int x = player.getLocation().clone().getBlockX();
		int z = player.getLocation().clone().getBlockZ();
		Block block = player.getWorld().getHighestBlockAt(x, z);
		
		System.out.println(block.getType().toString());
		

### Plugin list:
___A list of your plugins___
TestPlugin.jar
### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
This server is running Paper version git-Paper-242 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by zachbr** [comment] 2020-02-01 19:40
1.14.4 is unsupported. If you can reproduce on 1.15.2 please let us know.

**Comment by yannicklamprecht** [comment] 2020-02-01 19:52
Did you add api-version to your plugin.yml?  Is the block above your location a block added in 1.13+ ?

**Comment by DevJoey** [comment] 2020-02-01 19:53
In 1.15 the same issue. it only works close after a server restart. Api version is set correctly

**Comment by DevJoey** [comment] 2020-02-01 19:53
The block above me is grass_block but it returs air

**Comment by DevJoey** [comment] 2020-02-01 19:59
It gets the highest AIR block but not the highest block.

**Comment by yannicklamprecht** [comment] 2020-02-01 20:20
I can reproduce that in 1.15.2 with Spigot. Blocks where e.g. leaf and grass is the highest block it returns AIR. For poppy and snow it works. Rechecking it against latest build, was 27 behind. Editing it afterwards. 
Edit: Can reproduce it with latest. Looks like it returns highest solid non passable block + 1 every time.

**Comment by DevJoey** [comment] 2020-02-01 20:35
Yea it gets the highest block +1

**Comment by yannicklamprecht** [comment] 2020-02-02 22:58
Will be fixed in CB upstream when pr merged.

**Comment by electronicboy** [comment] 2020-02-03 02:00
upstream mergarino https://github.com/PaperMC/Paper/commit/3dafa6a08aef38594cfc657a6cca2e011afa35cb

**Closed as completed** 2020-02-03 01:59 UTC
Labels: type: bug, upstream: bukkit
