### ISSUE TITLE
Activated animals outside activation range

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#2685] opened 2019-11-09 23:25 UTC
### What behaviour is expected:
I would expect all animals outside the activation range to be less active

### What behaviour is observed:
Baby animals, sheared (adult) sheeps and turtles are extremely active even far beyond the activation range.

### Steps/models to reproduce:
Place different animals in different state in a fenced area
Walk to a point (far) outside the activation range (spigot.yml)

### Plugin list:
irrelevant

### Paper build number:
Paper-1.14.4 build 225

### Anything else:
Spigots settings for this test:
```
    entity-activation-range:
      raiders: 48
      animals: 8
      monsters: 24
      misc: 8
      water: 8
      tick-inactive-villagers: false
```

**Comment by electronicboy** [comment] 2019-11-10 06:46
entities outside of the activation range do not just stop ticking entirely, this would be unsafe and break certain mechanics, e.g. sheered sheep need to tick in order to permit their regrowth

Entities which have active targets will also tick to prevent breaking other mechanics, turtles might need a bit of a look to see if there is a way to tame their behavior down if they're a major issue, but otherwise; this is 100% intended behavior

**Comment by chickeneer** [comment] 2020-08-30 01:40
Closing this issue.
Some further improvements were made to EAR back in April to improve the immunity mechanic described. Isn't going to make things

**Comment by chickeneer** [comment] 2020-08-30 01:41
Closing this issue.
Some further improvements were made to EAR back in April to improve the immunity mechanic described which is still intentional. Lets entities do their tasks while reducing the overall load.

**Closed as completed by chickeneer** 2020-08-30 01:41 UTC
