### ISSUE TITLE
Spigot1.17.1 works well for me. After I change to paper, an error is reported. it even crash

### ISSUE THREAD

**Issue by h316098438** [PaperMC/Paper#6380] opened 2021-08-12 04:16 UTC
### Stack trace

```
https://paste.gg/p/anonymous/85d1bb904c704a4aa46507f5f7a97eff
```

### Plugin list

 AdvancedNMotd 9.2.0
[12:07:59 INFO]:  - AureliumSkills Beta 1.2.0
[12:07:59 INFO]:  - AuthMe 5.6.0-beta2-b2453
[12:07:59 INFO]:  - BankPlus 1.7
[12:07:59 INFO]:  - Citizens 2.0.28-SNAPSHOT (build 2359)
[12:07:59 INFO]:  - CMILib 1.0.2.9
[12:07:59 INFO]:  - CoreProtect 19.5
[12:07:59 INFO]:  - CustomGo 8
[12:07:59 INFO]:  - DailyShop 3.3
[12:07:59 INFO]:  - eBackup 1.2.0
[12:07:59 INFO]:  - EconomyShopGUI 3.4.2
[12:07:59 INFO]:  - Essentials 2.19.0-dev+247-35b1a28
[12:07:59 INFO]:  - EvenMoreFish 1.3.2
[12:07:59 INFO]:  - GoldenCrates 3.11.0
[12:07:59 INFO]:  - HolographicDisplays 2.4.9
[12:07:59 INFO]:  - HotbarPets DEV - 37 (git 63b1553e)
[12:07:59 INFO]:  - InfinityExpansion 117 zh-CN
[12:07:59 INFO]:  - LaggRemover 2.0.6
[12:07:59 INFO]:  - LuckPerms 5.3.47
[12:07:59 INFO]:  - Moeka 1.0-PublicVer
[12:07:59 INFO]:  - Multiverse-Core 4.3.0-b846
[12:07:59 INFO]:  - MythicMobs 4.12.0-FREE
[12:07:59 INFO]:  - NexEngine 2.0.7.4
[12:07:59 INFO]:  - OnlineRewards 1.0.0
[12:07:59 INFO]:  - PlaceholderAPI 2.10.9
[12:07:59 INFO]:  - PluginManager 2.5
[12:07:59 INFO]:  - ProtocolLib 4.7.0
[12:07:59 INFO]:  - Quests 4.0.5-b246
[12:07:59 INFO]:  - Residence 5.0.0.0
[12:07:59 INFO]:  - Slimefun 4.9-exp-837a265
[12:07:59 INFO]:  - SManage 5.0
[12:07:59 INFO]:  - Vault 1.7.3-b131
[12:07:59 INFO]:  - WorldEdit 7.2.6-SNAPSHOT+5891-8686672

### Paper version

This server is running Paper version git-Paper-170 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 80650e8)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-08-12 04:18
Likely duplicate of #5980

**Closed as completed by electronicboy** 2021-08-12 04:18 UTC
Labels: resolution: duplicate
