### ISSUE TITLE
Players Can't Pick Up Items

### ISSUE THREAD

**Issue by B1gLev** [PaperMC/Paper#3655] opened 2020-06-28 14:07 UTC
###  Timings or Profile link:
https://timings.aikar.co/?id=788725406d6f43c5a2c4d3ad031e3f99

### Description of issue:
Sometimes it goes and sometimes it doesn’t work. I don't know if it's caused by a bug or plugins but we can't think of anything other than a jar bug.

### Plugin list:
![2020-06-28_16 06 58](https://user-images.githubusercontent.com/40140251/85949873-8e5e6400-b959-11ea-8dd8-c34d0dc66fa4.png)

**Comment by electronicboy** [comment] 2020-06-28 14:08
Duplicate of #3632

**Closed as completed by electronicboy** 2020-06-28 14:08 UTC
