### ISSUE TITLE
FurnaceBurnEvent setBurnTime Not Comsuming Fuels 

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Paper#5115] opened 2021-01-26 03:23 UTC
### What behaviour is expected:
Fuels are comsumed by the furnace.

### What behaviour is observed:
Fuels aren't consumed when there are more than 1 fuel item in the fuel slot.

### Steps/models to reproduce:

public void onFuelBurn(FurnaceBurnEvent e) {
           Furnace f = ((Furnace)e.getBlock().getState());
            f.setCookSpeedMultiplier(2);
            f.setBurnTime(900);
}

### Paper version:
Paper version git-Paper-444 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by kickash32** [comment] 2021-03-21 04:44
I wouldn't exactly say this is a bug. This event is more of a preEvent. Modifying the source furnace is going to cause unexpected behavior. I would suggest trying to set the burn time using the event and retesting.
I don't believe, setting the multiplier would have any side effects but you don't need to set it every time from what I can tell.

**Comment by Machine-Maker** [comment] 2022-03-22 21:47
Closing as cannot reproduce (and invalid since those reproduction steps do literally nothing as you are operating on a snapshot of the furnace) (and even if it was a live view, the fuel is consumed in both scenarios)

**Closed as completed by Machine-Maker** 2022-03-22 21:47 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.16
