### ISSUE TITLE
Holding a Sword in Creative Mode and Attempting to Break a block fires an event when it should not

### ISSUE THREAD

**Issue by bendgk** [PaperMC/Paper#6415] opened 2021-08-17 22:37 UTC
### Expected behavior

When holding a sword in creative mode, the player cannot break any blocks.
The `BlockBreakEvent` should not fire when in Creative Mode and left-clicking with a sword. 

### Observed/Actual behavior

Holding a sword in creative mode and attempting to break a block does nothing visually (No broken blocks), but it still fires the `BlockBreakEvent`.

### Steps/models to reproduce

1. create a `BlockBreakEvent` listener that prints when fired
2. set yourself into creative mode
3. give yourself a sword
4. try to break some blocks while holding the said sword

(notice no blocks can actually be mined, but the event fires anyways)

### Plugin list

A singular event listener.

### Paper version

This server is running Paper version git-Paper-576 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

pretty sure this exists upstream though in 1.16.5

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by HexedHero** [comment] 2021-08-17 22:41
Can you reproduce this in spigot?

**Comment by Owen1212055** [comment] 2021-08-18 00:15
Yes it fires the event, but isn’t it cancelled already? This way you can uncancel it and it will still break the block.

**Comment by drunderscore** [comment] 2021-08-18 05:29
@Owen1212055 If that is so, that sounds really inconsistent... that's like saying the `EntityDamageEvent` should fire for players in creative but already canceled.

If I wanted this functionality, I would use a `PlayerInteractEvent`.

**Comment by Machine-Maker** [comment] 2021-08-22 03:34
@drunderscore welcome to bukkit, the land of inconsistencies. Changing it to not do that would be a big behavior change.

@bendgk so there is your answer. The event is fired, but fired in a cancelled state. if you want to filter out those firings only listen to the event if its not cancelled. The `@EventHandler` annotation has a parameter for that.

Closing as "works as intended"

**Closed as completed by Machine-Maker** 2021-08-22 03:34 UTC
Labels: type: bug, resolution: works as intended, version: 1.16
