### ISSUE TITLE
Chest filling does not work

### ISSUE THREAD

**Issue by tastybento** [PaperMC/Paper#6269] opened 2021-07-25 16:37 UTC
### Expected behavior

Chests should have items in them. This was broken in Spigot and then fixed in Spigot, but the issue remains in Paper for some reason.

### Observed/Actual behavior

Chests are empty after being filled in code.

### Steps/models to reproduce

Here is a test plugin. By left clicking on any block, it will change it to a chest and try to fill it with items. 
[TestPlugin-1.11.1-SNAPSHOT-LOCAL.jar.zip](https://github.com/PaperMC/Paper/files/6874213/TestPlugin-1.11.1-SNAPSHOT-LOCAL.jar.zip)

Here's the code of the attached:
```
public class TestPlugin extends JavaPlugin implements Listener {

    private final Map<Integer, ItemStack> inventory = new HashMap<>();


    @Override
    public void onEnable() {
        getLogger().info("Test plugin loaded");
        inventory.put(3,  new ItemStack(Material.ACACIA_BOAT, 3));
        inventory.put(6,  new ItemStack(Material.GHAST_SPAWN_EGG, 1));
        inventory.put(9,  new ItemStack(Material.IRON_AXE, 5));
        inventory.put(14,  new ItemStack(Material.ICE, 2));
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onHitChest(PlayerInteractEvent e) {
        if (!e.getAction().equals(Action.LEFT_CLICK_BLOCK)) return;
        e.getClickedBlock().setType(Material.CHEST);
        setBlockState(e.getClickedBlock());
        e.getPlayer().sendMessage("Chest made and filled!");
    }

    /**
     * @param block - block
     * @param bpBlock - config
     */
    private void setBlockState(Block block) {
        // Get the block state
        BlockState bs = block.getState();
        // Chests, in general
        if (bs instanceof InventoryHolder) {
            Inventory ih = ((InventoryHolder)bs).getInventory();
            // Fill chest
            inventory.forEach(ih::setItem);
            bs.update(true, false);
        }
    }
}
```

### Plugin list

```
> plugins
[09:36:51 INFO]: Plugins (1): TestPlugin
```

### Paper version

```
> version
[09:36:54 INFO]: Checking version, please wait...
[09:36:54 INFO]: This server is running Paper version git-Paper-130 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2f1f1b7)
You are running the latest version
Previous version: git-Paper-127 (MC: 1.17.1)
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

This issue was highlighted in a comment on a recent PR.

**Comment by imDaniX** [comment] 2021-07-25 16:49
> `bs.update(true, false);`

Don't update it.

**Comment by tastybento** [comment] 2021-07-25 16:52
Huh. That does indeed fix the issue. I wonder why that happens.

**Comment by Machine-Maker** [comment] 2021-07-25 16:57
So my guess is, updating the blockstate sets the inventory back to what it was before you added stuff to the inventory.

Is that still different behavior from spigot? Like if you ran this plugin on a spigot server with the update call, would the chest have items in it?

**Comment by kccricket** [comment] 2021-07-25 20:02
Based on my experience with @tastybento's BentoBox plugin, chests the plugin creates are filled in Spigot 3203-Spigot-18c71bf-aa69d1c, but not filled in Paper 1.17.1 build 127.

**Comment by DerFrZocker** [comment] 2021-07-25 21:32
TLTR: Paper didn't apply the upstream comment correctly, your provided test code won't work on Spigot and Paper.

To hopefully bring some light to the issue.
The comment made for around 6 days on CraftBukkit / Spigot (8d244b0b7e3) contained a flaw. When a block is updated with the same type the tile entity would get removed but not re-set, this is because of Minecraft not setting a new tile entity in nms Chunk#setType(...) when the old and new block are from the same type. This causes that the block now didn't have a tile entity and therefore not an inventory. This causes the issue with the chest not being filled.

For two days a comment was made (aa69d1cfb99) to fix this. Paper promptly updated but apparently didn't do it right, looking at the decompile code of Paper-130 it is still as before.

        if (this.getNMS().isTileEntity()) {
            if (this.world instanceof net.minecraft.world.level.World) {
                ((net.minecraft.world.level.World)this.world).removeTileEntity(this.position);
            }
            else {
                this.world.setTypeAndData(this.position, Blocks.a.getBlockData(), 0);
            }
        }

As with the provided test code, it won't work either on Spigot or on Paper. This is because #getInventory() returns the live inventory not the snapshot inventory by updating the block state you override the inventory you have set the items with the old empty one.
As to why your plugin did work again on Spigot is because in your actual plugin you call the update method before setting the items not afterwards (this makes a huge difference).
It worked again on Paper after removing the updated call because the chest has a valid tile entity since you set the block now only once and not twice.

**Comment by jpenilla** [comment] 2021-07-25 21:48
@DerFrZocker Hmm, looking at `CraftBlock#setTypeAndData(BlockState, boolean)` in my local copy of the Paper source, it seems we have correctly updated?

```java
public boolean setTypeAndData(final net.minecraft.world.level.block.state.BlockState blockData, final boolean applyPhysics) {
    net.minecraft.world.level.block.state.BlockState old = this.getNMS();
    // SPIGOT-611: need to do this to prevent glitchiness. Easier to handle this here (like /setblock) than to fix weirdness in tile entity cleanup
    if (old.hasBlockEntity() && blockData.getBlock() != old.getBlock()) { // SPIGOT-3725 remove old tile entity if block changes
        // SPIGOT-4612: faster - just clear tile
        if (this.world instanceof net.minecraft.world.level.Level) {
            ((net.minecraft.world.level.Level) this.world).removeBlockEntity(position);
        } else {
            this.world.setBlock(position, Blocks.AIR.defaultBlockState(), 0);
        }
    }
    
    // ...

```

**Comment by DerFrZocker** [comment] 2021-07-25 21:57
@jpenilla maybe a desync of some sort? I'm not familiar with papers patch system, all I can say is that downloading paper build 130 from papermc, freshly running it (no cache folder) and decompiling the patched jar in the cache folder gives me the code mentioned in my other command.

**Comment by Machine-Maker** [comment] 2021-07-25 21:57
We get the same results. looking in to it.

**Comment by jpenilla** [comment] 2021-07-25 21:58
Seems like a deployment issue, I can confirm the build from the site has the code like you showed.  Thanks for bringing this to our attention.

**Comment by Machine-Maker** [comment] 2021-07-25 22:20
[Build 131](https://papermc.io/downloads) should fix that issue. Assuming it does, I'll close the issue.

**Closed as completed** 2021-07-25 22:20 UTC

**Comment by tastybento** [comment] 2021-07-26 03:05
Thanks for all the attention guys. I was not online all of today, but thanks for the follow up.
