### ISSUE TITLE
New generated worlds create many duplicate entity 1.14.1

### ISSUE THREAD

**Issue by andris155** [PaperMC/Paper#2048] opened 2019-05-16 21:10 UTC
### Link/paste of stack trace
```
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:chicken that already exists with UUID 348935e9-fc15-4a2b-890e-56c4e948b796
[23:04:37] [Server thread/ERROR]: Deleting duplicate entity EntityChicken['Chicken'/190791, uuid='348935e9-fc15-4a2b-890e-56c4e948b796', l='world114', x=4582.00, y=68.00, z=-1001.00, cx=286, cz=-63, tl=0, v=false, d=false]
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:rabbit that already exists with UUID 5e025bcd-19bb-48b1-baa2-843cdae3035c
[23:04:37] [Server thread/ERROR]: Deleting duplicate entity EntityRabbit['Rabbit'/190792, uuid='5e025bcd-19bb-48b1-baa2-843cdae3035c', l='world114', x=4469.00, y=67.00, z=-1029.00, cx=279, cz=-65, tl=0, v=false, d=false]
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:rabbit that already exists with UUID 49680c1f-2d5a-4c27-a9ba-8330f8cd8cdc
[23:04:37] [Server thread/ERROR]: Deleting duplicate entity EntityRabbit['Rabbit'/190793, uuid='49680c1f-2d5a-4c27-a9ba-8330f8cd8cdc', l='world114', x=4469.00, y=67.00, z=-1030.00, cx=279, cz=-65, tl=0, v=false, d=false]
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:spider that already exists with UUID 2b766f3c-39aa-44f9-98ad-c343a03afa7f
[23:04:37] [Server thread/ERROR]: Deleting duplicate entity EntitySpider['Spider'/190794, uuid='2b766f3c-39aa-44f9-98ad-c343a03afa7f', l='world114', x=4470.47, y=63.00, z=-1065.58, cx=279, cz=-67, tl=192, v=false, d=false]
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:zombie that already exists with UUID ecd78c9e-e16b-46ba-b37e-7e31eac54b26
[23:04:37] [Server thread/ERROR]: Deleting duplicate entity EntityZombie['Zombie'/190795, uuid='ecd78c9e-e16b-46ba-b37e-7e31eac54b26', l='world114', x=4467.17, y=63.00, z=-1086.17, cx=279, cz=-68, tl=287, v=false, d=false]
[23:04:37] [Server thread/ERROR]: Keeping entity minecraft:enderman that already exists with UUID 5b31e2c8-294c-4de2-ac1f-48064733da37
```

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:
___A list of your plugins___
Plugins (92): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus*, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RedstoneClockDetector*, RestrictedCreative, Ridables, SignEdit*, StaffChat, StaffTime, Stats, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Generate new 1.14.1 world

### Paper build number:
___This can be found by running `/version` on your server. `latest` is not a proper version number; we require the output of `/version` so we can properly track down the issue.___
16.05 22:50:20 [Server] INFO This server is running Paper version git-Paper-23 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by zachbr** [comment] 2019-05-16 21:18
Closing as duplicate of GH-2017

**Closed as completed by zachbr** 2019-05-16 21:18 UTC
Labels: resolution: duplicate
