### ISSUE TITLE
Server freezes after many squids and fishes automatically spawned

### ISSUE THREAD

**Issue by SupppRabit** [PaperMC/Paper#3890] opened 2020-07-12 10:30 UTC
### What behaviour is expected:
They should spawn based on the server config.

### What behaviour is observed:
Once launch server which is and a player logins, a huge number of fishes and squids will spawn. It makes the player's connection timed out and the server freezes.

### Steps/models to reproduce:
1. Launch a toaster server later than 1.15.2-354 and log in, the server will freeze.
2. Replace the paperclip with older version, player will be able to login and see many fishes or squids.
![2020-07-12_16 36 40](https://user-images.githubusercontent.com/55012063/87243423-82e65f00-c468-11ea-8979-4567e45e4881.png)
my drowned machine is full of fishes but not loaded yet

### Plugin list:
none

### Paper build number:
After paper1.15.2-354 , including1.16.x

### Anything else:
[2020-07-12-1.log.gz](https://github.com/PaperMC/Paper/files/4908325/2020-07-12-1.log.gz)
1.16.1-89  log

**Comment by electronicboy** [comment] 2020-07-12 10:32
Duplicate of #3523

**Closed as completed by electronicboy** 2020-07-12 10:32 UTC
