### ISSUE TITLE
Chat item display not working on newest paper

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#5251] opened 2021-02-25 16:52 UTC
### What behaviour is expected:
___What you expected to see ___
 plugin should normally work / display item name
### What behaviour is observed:
___What you actually saw___
![image](https://user-images.githubusercontent.com/75625135/109186654-731a5180-7791-11eb-92c9-9d1c6091c116.png)
not working
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
update to newest version paper e.g # 497  (you must have protocollib)
### Plugin list:
___A list of your plugins___
 Plugins (2): ChatItemDisplay,ProtocolLib
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
# 497
### Anything else:
___Anything else you think may help us resolve the problem___
When i updated paper, Chat item display plugin has stopped working

**Comment by Trigary** [comment] 2021-02-25 16:57
Do you expect us to download and look through all 70 plugins to try and reproduce this? Please provide no more information than necessary, but all the information that's necessary. That usually means the exact plugins, their configurations, and the commands/actions necessary to reproduce this issue.

**Comment by kashike** [comment] 2021-02-25 17:01
That screenshot is about as useful as a teapot made out of chocolate - not useful at all.

**Comment by electronicboy** [comment] 2021-02-25 17:01
Issue was already reported under #5216, in the future, please don't hijack others reports or create duplicate ones in the future

Will keep this open as it's likely separate to the actual issue there

**Comment by Proximyst** [comment] 2021-02-25 17:05
Likely duplicate of https://github.com/PaperMC/Paper/issues/5220

**Comment by Proximyst** [comment] 2021-02-26 17:30
Nothing we can do here, ProtocolLib issue: https://github.com/BingoRufus/ChatItemDisplay/blob/13f20d6e4ecaaf01c9480aee6b395317c1c03749/src/main/java/com/github/bingorufus/chatitemdisplay/listeners/ChatPacketListener.java#L50-L68

**Closed as completed by Proximyst** 2021-02-26 17:30 UTC
Labels: type: bug, status: accepted, plugin
