### ISSUE TITLE
Some players can't log in with 1.14.2

### ISSUE THREAD

**Issue by kaanakduman** [PaperMC/Paper#2094] opened 2019-05-28 08:01 UTC
### What behaviour is expected:
___I expect a join message to appear when a player logs in. I also expect them not to be instantly kicked.___

### What behaviour is observed:
___A player Celezian logged out just fine, but when Celezian shortly relogged, it instantly kicked him for "Internal server error". A left-the-server message was shown, but no joined-the-server message was shown. This also happened to another player shortly afterward. A log of the console during the error is https://hasteb.in/oyimixuw.md___

### Steps/models to reproduce:
___Logging in will sometimes make the bug happen, and waiting a little bit will allow you to log back in again.___

### Plugin list:
___Plugins (34): CoreProtect, LuckPerms, Wild, WorldEdit, CrazyCrates, DragonEggDrop, OpenInv, MinePacks, PlugMan, NoSpawnerChange, BuycraftX, Votifier, Multiverse-Core, WorldGuard, VotingPlugin, PhantomSMP, ModReq, RFChairs, Vault, GriefPrevention, Essentials, MyWarps, ArmorStandTools, Parties, HeadDatabase, LWC, DiscordSRV, EssentialsChat, HorseTpWithMe, ServerSigns, EssentialsSpawn, WorldGuardExtraFlags, ChestShop, BanFromShops(Custom)___

### Paper build number:
___Paper-51___

### Anything else:
___The bug began in Paper-51 and appears to occur in Spigot 1.14.2 Here is a report for Spigot https://hasteb.in/fizodama.shell . It might just be better to wait for spigot to fix it maybe___

**Comment by electronicboy** [comment] 2019-05-28 12:25
Duplicate of #2084

**Closed as completed by electronicboy** 2019-05-28 12:25 UTC
