### ISSUE TITLE
Not a map: null Exception loading structure piece with id minecraft:jigsaw

### ISSUE THREAD

**Issue by antibitcoin** [PaperMC/Paper#5972] opened 2021-06-23 21:28 UTC
### Expected behavior

no errors to show on console

### Observed/Actual behavior

[23:21:48 ERROR]: Not a map: null
[23:21:48 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-43]
[23:21:48 ERROR]: Not a map: null
[23:21:48 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-43]
[23:21:48 ERROR]: Not a map: null
[23:21:48 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.jar:git-Paper-43]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.jar:git-Paper-43]

### Steps/models to reproduce

just running the server normally throws this error from time to time, and sometimes it spam the server and crash with the following errors afterwards
02:56:53] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-"3c58c05" (MC: 1.17) ---
[02:56:53] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[02:56:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[02:56:53] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[02:56:53] [Paper Watchdog Thread/ERROR]: -34,60 in 'world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]: Load Task - none
[02:56:53] [Paper Watchdog Thread/ERROR]: Save Task - none
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[02:56:53] [Paper Watchdog Thread/ERROR]: Chunk Neighbors: 
[02:56:53] [Paper Watchdog Thread/ERROR]:   -30,68 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Holder Priority - 3
[02:56:53] [Paper Watchdog Thread/ERROR]:   Chunk Neighbors: 
[02:56:53] [Paper Watchdog Thread/ERROR]:     -23,63 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:     Chunk Neighbors: 
[02:56:53] [Paper Watchdog Thread/ERROR]:       -30,68 in world_nether (CIRCULAR)
[02:56:53] [Paper Watchdog Thread/ERROR]:       -25,66 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:       Chunk Neighbors: 
[02:56:53] [Paper Watchdog Thread/ERROR]:         -23,63 in world_nether (CIRCULAR)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -30,68 in world_nether (CIRCULAR)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -22,66 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -26,69 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:liquid_carvers
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -29,72 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -28,68 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 3
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -26,67 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:full
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 3
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -29,71 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -23,58 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -30,69 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:liquid_carvers
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -27,71 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -24,60 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:liquid_carvers
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -22,68 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -22,67 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -23,62 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -25,64 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -31,72 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -23,59 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -21,61 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -23,71 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -32,71 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -24,71 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:structure_starts
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         -25,63 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -25,67 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Ticket Status - minecraft:features
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Status - null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder Priority - 4
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Neighbors: (Can't show, too deeply nested)
[02:56:53] [Paper Watchdog Thread/ERROR]:         -21,69 in world_nether:
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Holder - non-null
[02:56:53] [Paper Watchdog Thread/ERROR]:         Chunk Status - null chunk

### Plugin list

[23:27:42 INFO]: Plugins (88): AdvancedCrates, AdvancedEnchantments, AdvancedNMotd, AltDetector, antiRedstoneClock, ArmoredElytra, ArmorStandCrashFix*, AuctionHouse, AutoBroadcast, BanItem, BannerText, BuycraftX, ChatEx*, ChatSentinel, Citizens, ClearLag, CMILib, CommandAlias, CommandPanels, CrazyEnvoy, CubCustomDrops, DeathMessages, DeluxeMenus, DeluxeTags*, DiscordSRV, dtlTraders, eBackup, EnchantmentNumbers, Essentials, EssentialsGeoIP, EvenMoreFish, ExecutableBlocks, ExecutableItems, EZColors, FarmControl, GambleBarLite*, GangsPlus, Gatekeeper*, HarmonyScoreboard, HeadDatabase, HolographicDisplays, HolographicScoreboard*, IllegalStack, Insights, InteractiveChat, ItemEditor, ItemSoulBind, Jobs, JoinEventsPro, LagAssist, LPX*, LuckPerms, mcMMO, Mines, OpenInv, PL-Hide-Pro, PlaceholderAPI, PlayerParticles, PlayerVaults, PluginConstructorAPI, ProdigyMentionSpigot*, ProtocolLib, pvpstats, Quests, SaveRodOfficial*, SCore, ShopGUIPlus, Shopkeepers, SilkSpawners, SimpleGiveall, SimpleRename, SlotMachine, SpecializedCrates, StoreStats, TAB, TCPShield, Themis, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoteParty, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

1.17 build #43

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

please help?

**Comment by electronicboy** [comment] 2021-06-23 21:29
Duplicate of #5910

**Closed as completed by electronicboy** 2021-06-23 21:29 UTC
Labels: type: bug, resolution: duplicate, version: 1.17
