### ISSUE TITLE
Server crash when trading

### ISSUE THREAD

**Issue by Mundo-Minecraft** [PaperMC/Paper#4258] opened 2020-08-31 18:18 UTC
When trading crystal the server crashes in about 10-15 seconds.
Log: https://pastebin.com/Jx5wimJ1. 
Paper version [Server thread/INFO]: This server is running Paper version git-Paper-172 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

The error is so strange that I have made a video :) https://youtu.be/eJENRjtimxU I know that the error indicates that I did not report it to paper, but as seen in the video when paper is traded it stops working.

thanks and greetings

**Comment by Proximyst** [comment] 2020-08-31 18:22
Duplicate of #2312.

**Closed as completed by Proximyst** 2020-08-31 18:22 UTC
Labels: resolution: duplicate, version: 1.16
