### ISSUE TITLE
Light Problem with WorldEdit or FAWE

### ISSUE THREAD

**Issue by StevenAVC** [PaperMC/Paper#4278] opened 2020-09-03 00:26 UTC
### What behaviour is expected:
My expectation is to see the constructions with the arrangement of lights loaded in all the chunks

### What behaviour is observed:
When I place a build with WorldEdit or FAWE the construction comes out with shadows because it does not load the light from each block that illuminates the build

### Steps/models to reproduce:
I load my schematic with // schematic load (schematic name) and then put it with // paste -a

When the construction is placed, it comes out with shadows

### Plugin list:
FAWE 1.16-341 and Essentials 2.18.1

### Paper version:
Paper version git-Paper-178

### Anything else:
I reported the light bug with the FAWE developers and they told me to remove all plugins and use / paper fixlight but the problem has not been fixed. The FAWE developers told me to create a ticket reporting the error to Paper.

**Comment by me4502** [comment] 2020-09-03 11:01
Are you sure this is reproducible using only WorldEdit itself rather than FAWE? FAWE is known to create lighting issues that don't seem to want to go away even with `/paper fixlight`.

**Comment by SecretlyJealous** [comment] 2020-09-04 18:10
It's because of: https://github.com/PaperMC/Paper/issues/3685

**Comment by Chew** [comment] 2020-09-04 18:33
Yep, looks like a duplicate of #3685 to me, we'll track it there

**Closed as completed by Chew** 2020-09-04 18:33 UTC
Labels: resolution: duplicate
