### ISSUE TITLE
1.16 Redstone Lamp Bug

### ISSUE THREAD

**Issue by BYOl912** [PaperMC/Paper#4904] opened 2020-12-18 04:30 UTC
### What behaviour is expected:
No adjacent redstone lamps are switched off

### What behaviour is observed:
Trying to lit up 2 or more adjacent redstone lamps with debug stick causes the first redstone lamp to switch off

### Steps/models to reproduce:
Simply try to lit up 2 adjacent redstone lamp with debug stick and it would occur

### Plugin list:
none

### Paper version:
[12:25:33 INFO]: This server is running Paper version git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[12:25:33 INFO]: Checking version, please wait...
[12:25:35 INFO]: Previous version: git-Paper-300 (MC: 1.16.4)

### Anything else:
It's a paper specific bug AFAIK. I've tried replicating the above steps on vanilla.jar and spigot-1.16.4.jar and both work fine.

**Comment by electronicboy** [comment] 2020-12-18 04:32
Duplicate of #2134

**Closed as completed by electronicboy** 2020-12-18 04:32 UTC
Labels: version: 1.16
