### ISSUE TITLE
Summon motion tag not honored

### ISSUE THREAD

**Issue by timvango** [PaperMC/Paper#4339] opened 2020-09-18 20:19 UTC
After upgrading from 1.15.2 to 1.16.3, fireworks summoned with command blocks do not behave as expected anymore.
The used commands are something like this:
`/summon firework_rocket ~ ~4 ~12 {LifeTime:0,Motion:[0.00,9.90,0.00],FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Explosions:[{Type:4,Flicker:0,Trail:1,Colors:[I;16736834],FadeColors:[I;16736327]}]}}}}`

In previous versions, the motion tag in combination with LifeTime:0 cause a burst in the given direction. When increasing the LifeTime to something like 50, it demonstrates what it did before.
This is still working as expected in Vanilla and Spigot 1.16.3 (git-Spigot-2740d5a-da9bb3e). It also happens on Paper without any plugins.

I am using git-Paper-198 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

This is what Paper does:
![2020-09-18_21 20 29](https://user-images.githubusercontent.com/2168623/93641278-4d2b9c80-f9fc-11ea-90a5-9e2d8583448b.png)

This is what happens with the same command in Vanilla en Spigot (expected behaviour):
![2020-09-18_21 19 37](https://user-images.githubusercontent.com/2168623/93641341-66cce400-f9fc-11ea-9ab7-65ddc57e1acb.png)

**Comment by timvango** [comment] 2020-09-18 20:37
Update: It appears that the entire Motion tag in summon commands is not honored.
Other commands, like:
`/summon minecraft:snowball ~ ~5 ~ {Motion:[0.0,1.65,0.0],Time:1,DropItem:0}`
don't work anymore either.
The entity spawns in the correct place, but it just drops down from that point.
No motion/velocity is set to the entity whatsoever.

**Comment by electronicboy** [comment] 2020-09-18 20:41
Duplicate of #4292

**Closed as completed by electronicboy** 2020-09-18 20:41 UTC
