### ISSUE TITLE
Placing torch on leaves block decreases item count

### ISSUE THREAD

**Issue by ryanbester** [PaperMC/Paper#3288] opened 2020-05-04 15:52 UTC
### What behaviour is expected:
The number of torches in the inventory should not decrease when trying to place a torch on a leaves blocks.

### What behaviour is observed:
The number of torches decreases, no torch is placed and no torch is dropped. The torch count is corrected when the stack of torches is clicked in the Inventory menu.

### Steps/models to reproduce:
Put stack of torches in hand. Place a torch on a leaves block and the number will decrease. This will update when the stack of torches is clicked in the inventory screen.

### Plugin list:
- Essentials
- NotchAppleCrafter
- PermissionsEx
- TabList
- WelcomeMessage
- WorldEdit
- WorldGuard

### Paper build number:
git-Paper-234

### Anything else:
I've tried disabling WorldGuard and the issues persists.

**Comment by kickash32** [comment] 2020-05-11 02:44
Confirmed with no plugins, attempted to place on side of leaf block and it incorrectly decreased count. Count was updated when torch was placed on a valid block.

**Comment by nbastin** [comment] 2020-05-11 13:41
Can confirm this in Paper-280.  Does not happen in vanilla. 

That being said, I don't think this is a recent change as I seem to recall it happening months ago as well.

**Comment by kickash32** [comment] 2020-05-15 04:40
I don't know what changed, but I cannot reproduce this anymore? possibly fixed by something else?

**Comment by Chew** [comment] 2020-05-23 05:22
> Confirmed with no plugins, attempted to place on side of leaf block and it incorrectly decreased count. Count was updated when torch was placed on a valid block.

Same here. The stack doesn't actually decrease, it just appears to. Interacting with the torch in your inventory or, yes, placing it will sync server and client.

The bug here appears to be the fact it's trying to place it on the leaf at all. Vanilla behavior, when you right click, nothing happens. No animation, nothing. Unless there's a block touching the air block the torch is trying to fill excluding the one above.

**Comment by Chew** [comment] 2020-08-25 19:23
I've just tested this and it doesn't appear to happen on 1.16.2 I tried to follow my own repro steps but I completely confused myself. However I did try every way to reproduce this and couldn't. If you still can, let us know! Have a good day.

**Closed as completed by Chew** 2020-08-25 19:23 UTC
