### ISSUE TITLE
Cannot cancel "You logged in from another location" kick event

### ISSUE THREAD

**Issue by kabanod1m** [PaperMC/Paper#5303] opened 2021-03-04 12:26 UTC
### What behaviour is expected:
When player tries to join with the same account "from another location" (using another computer or even another game window), he cannot join the server, and the client that is already connected to the server remains not kicked.

### What behaviour is observed:
Client that is already on the server gets kicked, another client connects successfully — just like on a clean server.

### Steps/models to reproduce:
Listen to PlayerKickEvent and use this: (worked as of 1.16.5-467 build)
if (event.getReason().equals("You logged in from another location")) { event.setCancelled(true); }

### Plugin list:
No plugins installed beside the one that runs my code above

### Paper version:
[15:24:21 INFO]: This server is running Paper version git-Paper-520 (MC: 1.16.5)
 (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by kennytv** [comment] 2021-03-04 12:37
Cancel the AsyncPlayerPreLogin event of the newly joining player instance, either you shouldn't cancel this necessary kick or the kick reason is checked wrongly (since it's a translatable component)

**Comment by aikar** [comment] 2021-03-04 16:14
while what you are trying to do is sketch and shouldn't be done per kenny's message, there does seem to be potential for regression that the kick reason may of changed if it changed specifically in a build like this.

**Comment by chickeneer** [comment] 2021-03-04 16:25
This sounds related to the Adventure update. That the kick reason is no longer accessible due to being a translateable message.

**Comment by kashike** [comment] 2021-03-09 01:12
This should be fixed as of https://github.com/PaperMC/Paper/commit/27a8d99ec4f11d1facccb6d68b120b67b74b16a2 and https://github.com/PaperMC/Paper/commit/7f72c4675bf18f1dc1fd1fea2737590fa41dc7a7.

**Closed as completed by kashike** 2021-03-09 01:12 UTC
Labels: type: bug, version: 1.16
