### ISSUE TITLE
1.13 crash 

### ISSUE THREAD

**Issue by jason920612** [PaperMC/Paper#1333] opened 2018-08-14 13:44 UTC
serverversion: git-Paper-131 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Plugin list:
AntiCrash, BossShop, ColorMOTD, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, GuiShopManager, iConomy, LaggRemover, LockettePro, MobHeads, MoneyDrop, Multiverse-Core, MysqlEconomyBank, PlaceholderAPI, PlayerPoints, PlotSquared, ProtocolLib, PvPManager, QuickShop, RandomTeleportPro, React, Residence, TimeIsMoney, TitleManager, Vault, VipZero, WorldCommandBlock, WorldEdit

[crashreport](https://pastebin.com/UPXe894W)

**Comment by aikar** [comment] 2018-08-14 14:56
ugh, this is vanilla level, and really best for mojang to fix, as this could be an issue across the board.

If you remove or expand your world border, should help here.

**Comment by aikar** [comment] 2018-08-14 14:59
Oh, I see whats happening. it's not as systemic as I thought, we can likely fix this.

**Comment by aikar** [comment] 2018-08-14 15:03
needs world bounds check for SpawnerCreature line 312~, then the same thing for 327

**Comment by egg82** [comment] 2018-09-18 00:59
Since that function is entirely about spawning X amount (dictated randomly with a weight from the provided BiomeBase's e() function) of Creatures in a specific chunk, you would either need to generate the chunk to place creatures on or skip spawning creatures in that chunk entirely.

The signature of the function is as follows:
`public static void a(GeneratorAccess generatoraccess, BiomeBase biomebase, int i, int j, Random random)`
i and j are ChunkX and ChunkY respectively, and Random is the seed Random.

One of the first things the function does is bit-shift i and j to the left 4 places, which turns the ChunkX and ChunkY into BlockX and BlockY. After that it loops a random-ish number of times to spawn creatures in the BlockX and BlockY space, adding a random X and Y up to 16, which of course is exactly the size of a single chunk. It then spawns a creature at that location following some other logic that's not relevant.

The issue is that entire chunk it's trying to spawn on is outside of the border and thus not generated, which throws the error. The odd thing is that function seems to only be called in places that a chunk is currently being generated, meaning somewhere along the line the generation is being canceled but the server is going ahead and trying to populate it anyway. It's also possible a plugin is calling this function on chunks outside of the border.

The solution, then, is to either generate the chunk and populate it even though it's outside of the border, or skip population. I chose the latter here, as it made more sense following the logic previously. A simple check to see if the provided ChunkX, ChunkY was inside the generatoraccess's WorldBorder and return if not.

**Comment by 0-x-2-2** [comment] 2018-09-18 01:09
This was fixed in 1.13.1 afaik

**Comment by aikar** [comment] 2018-09-18 01:44
no longer valid in 1.13.1

**Closed as completed by aikar** 2018-09-18 01:44 UTC
Labels: type: bug, status: accepted, upstream: vanilla
