### ISSUE TITLE
Blocks Disappearing On Placement

### ISSUE THREAD

**Issue by orange0513** [PaperMC/Paper#3961] opened 2020-07-20 16:18 UTC
### What behaviour is expected:
All Blocks to be placed

### What behaviour is observed:
all the blocks after afew blocks disappear server side and require a relog to see - works perfect with normal spigot

### Steps/models to reproduce:
https://gyazo.com/8da170c95dc2eabd862a68c713185c8a

### Plugin list:
https://gyazo.com/62b1dc7538d2c5ab61fe998e24ee60c7

### Paper build number:
https://gyazo.com/922f2d71b3089a0189a13ad330e2d0ba

### Anything else:
Everything is above

**Comment by Proximyst** [comment] 2020-07-20 16:20
Try without a modded client and without plugins.

**Comment by kennytv** [comment] 2020-07-20 16:45
I'll just take a guess as to the cause; iirc it's an ugly default value. setting `play-in-use-item-spam-threshold` to something lower might do the trick

**Comment by chickeneer** [comment] 2020-09-05 19:43
Closing this issue till more information is provided from the reporter.
This issue will be reopened with more information. Thanks!

**Closed as completed by chickeneer** 2020-09-05 19:43 UTC
Labels: type: bug, resolution: awaiting response, version: 1.16
