### ISSUE TITLE
Certain interact events do not execute when standing on redstone ore

### ISSUE THREAD

**Issue by Owen1212055** [PaperMC/Paper#5507] opened 2021-04-17 18:41 UTC
### Expected behavior

- I expect those events to execute

### Observed/Actual behavior

The following block click types are not executed when standing on Redstone ore.
    RIGHT_CLICK_BLOCK,
    LEFT_CLICK_AIR,
    RIGHT_CLICK_AIR,

### Steps/models to reproduce

- Stand on redstone ore and observe that the PlayerInteractEvent does not fire. The only thing firing it is the physical events, but left clicking works fine.

### Plugin list

Test Plugin 

### Paper version

This server is running Paper version git-Paper-c310f0a61 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 29 version(s) behind

Latest update does nothing.

Can confirm this has been an issue since 07/20/2019

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by chickeneer** [comment] 2021-04-17 20:27
I was not able to reproduce this issue. I was able to trigger both the LEFT_CLICK_BLOCK and RIGHT_CLICK_BLOCK actions while standing on redstone ore. The physical event does continue triggering, but I saw no evidence of any left/right clicks not firing correctly.
Could you give any more details on your reproduction steps?
I am closing, but we will definitely re-open if information is given which helps us reproduce this issue. (as mentioned I did test it...)

**Closed as completed by chickeneer** 2021-04-17 20:27 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.16

**Comment by Owen1212055** [comment] 2021-04-17 20:35
My bad, my testing was flawed. Thank you for double-checking for me!
