### ISSUE TITLE
Should always be able to create a chunk! - Exception

### ISSUE THREAD

**Issue by ronnyjauch** [PaperMC/Paper#2430] opened 2019-08-08 20:06 UTC
Crashlog:
```

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 08.08.19 22:00
Description: Exception initializing level

java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388)
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210)
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187)
	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:819)
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:729)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388)
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210)
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187)
	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:819)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 5038309139612248756
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-216,64,248), Chunk: (at 8,4,8 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:729)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 934882720 bytes (891 MB) / 1643118592 bytes (1567 MB) up to 7618953216 bytes (7266 MB)
	JVM Flags: 0 total; 
	CraftBukkit Information: 
   Running: Paper version git-Paper-75dd53c6 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkLoader-7: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkLoader-3: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], WAITING PaperChunkLoader-4: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkGen-world: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Log4j2-TF-1-AsyncLogger[AsyncContext@5c647e05]-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38), com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56), com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159), com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_13_R2.DedicatedServer$1.run(DedicatedServer.java:66)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_13_R2.CraftCrashReport.call(CraftCrashReport.java:32), net.minecraft.server.v1_13_R2.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_13_R2.CrashReport.h(CrashReport.java:66), net.minecraft.server.v1_13_R2.CrashReport.<init>(CrashReport.java:34), net.minecraft.server.v1_13_R2.CrashReport.a(CrashReport.java:260), net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:736), net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367), net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316), net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING PaperChunkLoader-5: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Paper Async Task Handler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [java.io.FileInputStream.read0(Native Method), java.io.FileInputStream.read(Unknown Source), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:65), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:786), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:558), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140), net.minecraft.server.v1_13_R2.DedicatedServer$2.run(DedicatedServer.java:83)], RUNNABLE Attach Listener: [], WAITING PaperChunkLoader-2: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkLoader-8: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Paper Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:145)], TIMED_WAITING Craft Scheduler Thread - 3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkLoader-6: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PaperChunkLoader-1: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:213), com.destroystokyo.paper.util.PriorityQueuedExecutor$$Lambda$1638/1530682158.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
   
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Data Packs: vanilla, file/bukkit (incompatible)
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

Console log:

```
[22:00:41] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[22:00:41] [Server thread/INFO]: Random Lighting Updates: false
[22:00:41] [Server thread/ERROR]: Couldn't load chunk (world:-14,15)
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at net.minecraft.server.v1_13_R2.RegionFile.<init>(RegionFile.java:79) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.RegionFileCache.a(RegionFileCache.java:36) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.RegionFileCache.read(RegionFileCache.java:252) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:170) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:116) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:244) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.loadChunk(PaperAsyncChunkProvider.java:387) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.run(PaperAsyncChunkProvider.java:579) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.lambda$createPendingTask$1(PriorityQueuedExecutor.java:133) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.requestChunk(PaperAsyncChunkProvider.java:197) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.loadOrGenerateChunk(PaperAsyncChunkProvider.java:154) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:150) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:111) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.getChunkAt(PaperAsyncChunkProvider.java:136) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:385) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:819) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:729) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[22:00:41] [PaperChunkGen-world/ERROR]: Couldn't generate chunk (world:-14,15)
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_221]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CompletableFuture.supplyAsync(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SchedulerBatch.java:39) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.add(SchedulerBatch.java:34) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.generateChunk(PaperAsyncChunkProvider.java:407) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor$PendingTask.run(PriorityQueuedExecutor.java:273) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at com.destroystokyo.paper.util.PriorityQueuedExecutor.processQueues(PriorityQueuedExecutor.java:196) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at net.minecraft.server.v1_13_R2.RegionFile.<init>(RegionFile.java:79) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.RegionFileCache.a(RegionFileCache.java:36) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.RegionFileCache.read(RegionFileCache.java:252) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:170) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:116) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.b(ChunkRegionLoader.java:269) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.lambda$a$3(ChunkTaskScheduler.java:76) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:93) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:13) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.Scheduler.b(SourceFile:80) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	... 11 more
[22:00:41] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Exception initializing level
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:744) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:819) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:729) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	... 4 more
[22:00:41] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:388) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:819) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:729) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:367) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-75dd53c6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

### Plugin list:
___No Plugins installed___

### Actions to reproduce (if known):
Pull master branch, do `./paper patch` and `./paper jar` copy paperclip.jar to different folder, start server. 

### Paper build number:
 This server is running Paper version git-Paper-75dd53c6 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by TheDGOfficial** [comment] 2019-08-08 20:34
`Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;`

Upgrade to Java 9+ (possibly Java 11 LTS) or try on 1.14.4, this maybe fixed in commit aa022fdaca8e4059ff89cb43a5be172f17937e65

**Comment by electronicboy** [comment] 2019-08-08 20:36
That commit could do with being backported;

In the meantime, either make that change manually or compile on java 8

**Comment by ronnyjauch** [comment] 2019-08-08 20:38
@TheDGOfficial i will give that a try

**Closed as completed** 2019-08-08 21:08 UTC
