### ISSUE TITLE
Villagers not scared of Zombies

### ISSUE THREAD

**Issue by toothpaste-main** [PaperMC/Paper#2245] opened 2019-06-27 01:53 UTC
Villagers won't become scared by seeing a zombie in Paper 1.14.3, but they will in Spigot. Presents problem when making IGF's.

**Comment by zachbr** [comment] 2019-06-27 02:58
This is probably a duplicate of GH-2232, but you didn’t fill out the template so there’s not enough here to use anyway

**Closed as completed by zachbr** 2019-06-27 02:58 UTC
