### ISSUE TITLE
Server crash everyday

### ISSUE THREAD

**Issue by antibitcoin** [PaperMC/Paper#6268] opened 2021-07-25 03:47 UTC
### Stack trace

```
https://mcpaste.io/a3bfb3513709bfc5
```

### Plugin list

Plugins:
    AdvancedCrates:
        Version: 2.3.1
        Enabled: true
    AdvancedEnchantments:
        Version: 8.5.2
        Enabled: true
    AltDetector:
        Version: 1.1
        Enabled: true
    ArmorStandCrashFix:
        Version: 1.0.4
        Enabled: true
    ArmoredElytra:
        Version: 2.4.14
        Enabled: true
    AuctionHouse:
        Version: 3.0-b1
        Enabled: true
    AutoBroadcast:
        Version: 1.2.0
        Enabled: true
    BanItem:
        Version: 3.2
        Enabled: true
    BannerText:
        Version: 1.16.4-0
        Enabled: true
    BookUtils:
        Version: 1.3
        Enabled: true
    BungeeGuard:
        Version: 1.2-SNAPSHOT
        Enabled: true
    BuycraftX:
        Version: 12.0.7
        Enabled: true
    CMILib:
        Version: 1.0.3.0
        Enabled: true
    ChatEx:
        Version: 2.7.1
        Enabled: true
    Citizens:
        Version: 2.0.28-SNAPSHOT (build 2357)
        Enabled: true
    ClearLag:
        Version: 3.2.2
        Enabled: true
    ClientStats:
        Version: 2.11.2
        Enabled: true
    CommandAlias:
        Version: 1.6.6-RELEASE
        Enabled: true
    CommandPanels:
        Version: 3.16.2.4
        Enabled: true
    ConsoleSpamFix:
        Version: 1.8.6
        Enabled: true
    CrazyEnvoy:
        Version: 1.3.10-RELEASE
        Enabled: true
    DeathMessages:
        Version: 1.3.8
        Enabled: true
    DeluxeCoinflip:
        Version: 2.2.0
        Enabled: true
    DeluxeMenus:
        Version: 1.13.4-DEV-115
        Enabled: true
    DeluxeTags:
        Version: 1.8.2-DEV-null
        Enabled: true
    DiscordSRV:
        Version: 1.23.0
        Enabled: true
    DrMap:
        Version: 1.0.3
        Enabled: true
    DragonEggDrop:
        Version: 1.9.2
        Enabled: true
    EZColors:
        Version: 2.1.2
        Enabled: true
    EnchantmentNumbers:
        Version: 2.1
        Enabled: true
    Essentials:
        Version: 2.19.0-dev+221-1556b91
        Enabled: true
    EvenMoreFish:
        Version: 1.3.2
        Enabled: true
    ExecutableItems:
        Version: 3.4.3.4
        Enabled: true
    FarmLimiter:
        Version: 1.5.1
        Enabled: true
    FeatherBoard:
        Version: 5.0.3b
        Enabled: true
    GMusic:
        Version: [2.6.1.0]
        Enabled: true
    GSit:
        Version: [6.0.1.0]
        Enabled: true
    GadgetsMenu:
        Version: 5.0.4
        Enabled: true
    GambleBarLite:
        Version: 1.3.2
        Enabled: true
    GangsPlus:
        Version: 2.18.1
        Enabled: true
    Gatekeeper:
        Version: 1.2.0
        Enabled: true
    Harbor:
        Version: 1.6.3
        Enabled: true
    HeadDatabase:
        Version: 4.14.1
        Enabled: true
    HeadDisplays:
        Version: 1.6.1
        Enabled: true
    HolographicDisplays:
        Version: 2.4.8
        Enabled: true
    HolographicPlaceholders:
        Version: 2.1.2 Stable
        Enabled: true
    HolographicScoreboard:
        Version: 1.5.2
        Enabled: true
    IllegalStack:
        Version: 2.4.2
        Enabled: true
    Insights:
        Version: 6.5.5
        Enabled: true
    InteractiveChat:
        Version: 4.0.2.2
        Enabled: true
    InteractiveChatDiscordSrvAddon:
        Version: 4.0.1.7
        Enabled: true
    InventoryRollbackPlus:
        Version: 1.6.1
        Enabled: true
    ItemEditor:
        Version: 0.1.11
        Enabled: true
    ItemSoulBind:
        Version: 1.4.1
        Enabled: true
    Jobs:
        Version: 5.0.0.6
        Enabled: true
    JoinEventsPro:
        Version: 4.2
        Enabled: true
    LPX:
        Version: 2.6-MORTAL
        Enabled: true
    LevelledMobs:
        Version: 3.0.7 b465
        Enabled: true
    LuckPerms:
        Version: 5.3.47
        Enabled: true
    MVdWPlaceholderAPI:
        Version: 3.1.1
        Enabled: true
    Mines:
        Version: 6.3.3
        Enabled: true
    NoMobLag:
        Version: 2.3.3
        Enabled: true
    NotTooExpensive:
        Version: 1.3.0
        Enabled: true
    OTroll:
        Version: 1.2
        Enabled: true
    OpenInv:
        Version: 4.1.8
        Enabled: true
    PL-Hide-Pro:
        Version: 1.5.2
        Enabled: true
    PlaceholderAPI:
        Version: 2.10.10
        Enabled: true
    PlayerParticles:
        Version: 7.21
        Enabled: true
    PlayerVaults:
        Version: 4.2.3
        Enabled: true
    Playtimes:
        Version: 1.4.4
        Enabled: true
    PlugMan:
        Version: 2.2.5
        Enabled: true
    PluginConstructorAPI:
        Version: 1.0.52
        Enabled: true
    ProdigyMentionSpigot:
        Version: 1.3
        Enabled: true
    ProtocolLib:
        Version: 4.7.0
        Enabled: true
    Quests:
        Version: 3.5.2
        Enabled: true
    Regionerator:
        Version: 2.3.0
        Enabled: true
    SCore:
        Version: 1.2.8
        Enabled: true
    SaveRodOfficial:
        Version: 2.7.1
        Enabled: true
    ShopGUIPlus:
        Version: 1.62.2
        Enabled: true
    Shopkeepers:
        Version: 2.13.3
        Enabled: true
    SilkSpawners:
        Version: 7.1.0
        Enabled: true
    SimpleGiveall:
        Version: 1.0.3
        Enabled: true
    SimpleRename:
        Version: 13.9
        Enabled: true
    SkQuery:
        Version: 4.1.5
        Enabled: true
    Skript:
        Version: 2.6-beta2
        Enabled: true
    SlotMachine:
        Version: 6.4.1
        Enabled: true
    SpecializedCrates:
        Version: 2.22.7
        Enabled: true
    StoreStats:
        Version: 2.18.0
        Enabled: true
    SurvivalInvisiframes:
        Version: 2.1.0
        Enabled: true
    TAB:
        Version: 2.9.2
        Enabled: true
    Themis:
        Version: 0.9.0
        Enabled: true
    UltimateAutoRestart:
        Version: Build 44c
        Enabled: true
    Vault:
        Version: 1.7.3-b131
        Enabled: true
    ViewDistanceTweaks:
        Version: 1.3.4
        Enabled: true
    VirtualBooks:
        Version: 2.3
        Enabled: true
    VoteParty:
        Version: 2.26
        Enabled: true
    Votifier:
        Version: 2.7.3
        Enabled: true
    VotingPlugin:
        Version: 6.5.2
        Enabled: true
    Vouchers:
        Version: 1.8.20-RELEASE
        Enabled: true
    WorldBorder:
        Version: 2.1.2
        Enabled: true
    WorldEdit:
        Version: 7.2.6-SNAPSHOT+5853-978bf5b
        Enabled: true
    WorldGuard:
        Version: 7.0.6-SNAPSHOT+2134-abc360c
        Enabled: true
    WorldGuardExtraFlags:
        Version: 4.1.4
        Enabled: true
    antiRedstoneClock:
        Version: 1.4.0
        Enabled: true
    eBackup:
        Version: 1.2.0
        Enabled: true
    mcMMO:
        Version: 2.1.200
        Enabled: true
    pvpstats:
        Version: 1.11.19
        Enabled: true

### Actions to reproduce (if known)

Happens randomly at random times, but 1 and up to 4 times every day.

### Paper version

Server: git-Paper-127 (MC: 1.17.1)
API: 1.17.1-R0.1-SNAPSHOT

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-07-25 03:48
Probably duplicate of #5980 - your log is mangled to all heck

**Closed as completed by electronicboy** 2021-07-25 03:48 UTC
