### ISSUE TITLE
Server crashing whenever I join it

### ISSUE THREAD

**Issue by Carrot26** [PaperMC/Paper#11097] opened 2024-07-17 11:53 UTC
### Stack trace

https://pastes.dev/yoCLLWYSMh

Whenever I (Myself, ZeCarrotGamer) Join, the server shuts down. Doesn't happen for ANYONE else. I am in the Deep Dark at the time. This was relevant the last time I tried resolving the issue

### Plugin and Datapack List

No Datapacks
No Plugins

![image](https://github.com/user-attachments/assets/2de63222-a205-4e67-8ebe-a43d25e7557b)
![image](https://github.com/user-attachments/assets/ff57248f-7f9c-4c0f-9e1c-3af44d42ed98)

No Mods

### Actions to reproduce (if known)

Only happening on my server. I start my server like a normal day and log on. Go to an ancient city and all of a sudden get disconnected and welcome myself to the server crashing

### Paper version

[21:23:29 INFO]: Checking version, please wait...
[21:23:30 INFO]: This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-497 (MC: 1.20.4)

**Comment by CodeByCam** [comment] 2024-07-17 20:49
G'day @Carrot26, 
This is a duplicate of https://github.com/PaperMC/Paper/issues/10022, and [a fix was applied](https://github.com/PaperMC/Paper/pull/10794) for 1.20.6+. 

Granted, you were running an older build when you generated your world so the [plugin](https://github.com/lynxplay/block-entity-bin) linked in the aforementioned issue won't work for you yet, but the wonderful @lynxplay was very kind and said he'd bump it to work on 1.20.6 when he gets a chance. So keep an eye out for that, run the plugin and it should resolve your issue.

**Closed by CodeByCam** 2024-07-17 20:49 UTC
Labels: status: needs triage, version: 1.20.6
