### ISSUE TITLE
Dragon egg thru stronghold portal

### ISSUE THREAD

**Issue by GrimEpp** [PaperMC/Paper#5281] opened 2021-02-28 21:53 UTC
### What behaviour is expected:
If you drop an enderegg through a portal it should come out the other side.

### What behaviour is observed:
The dragon egg is nowhere to be seen

### Steps/models to reproduce:
Take a ender portal drop an egg and it's gone

### Plugin list:
None

### Paper version:
This server is running Paper version git-Paper-503 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[22:32:21 INFO]: Previous version: git-Paper-464 (MC: 1.16.5)

### Anything else:
This is not a problem on singleplayer Minecraft. (THIS IS A BUG ON SPIGOT) used latest buildtools on 22:50 UTC+1 I found this out trying to dupe the dragon egg, but it just forever disappeared.

On singleplayer:
https://gyazo.com/c08cd8176ad49264b427de8179d0a774

Paperspigot:
https://gyazo.com/bd58a5e75c495cd160d4123a7fcbe966

Lastet spigot via Buildtools

https://gyazo.com/3cbcdf3c51f8283c327418cf401d52a5

**Comment by HexedHero** [comment] 2021-02-28 21:55
**`THIS IS A BUG ON SPIGOT`**

Reports to paper, hmm.

**Comment by JRoy** [comment] 2021-02-28 21:57
Just because its a Spigot bug doesn't mean Paper can't fix it.

@GrimEpp: Does this happen on the vanilla server?

**Comment by Trigary** [comment] 2021-02-28 22:11
Duplicate of #3344. See [my comment](https://github.com/PaperMC/Paper/issues/3344#issuecomment-774570199) on that issue for an explanation of why this happens.

**Closed as completed** 2021-02-28 22:12 UTC
Labels: resolution: duplicate, version: 1.16

**Comment by HexedHero** [comment] 2021-02-28 22:30
> Just because its a Spigot bug doesn't mean Paper can't fix it.
> 
> @GrimEpp: Does this happen on the vanilla server?

Still should be reported to Spigot regardless either as well or before here imo.
Should always fix issues upstream as much as possible.
