### ISSUE TITLE
Block issues

### ISSUE THREAD

**Issue by Ironman1M** [PaperMC/Paper#4598] opened 2020-10-02 13:47 UTC
**Hello, today after installing a map onto my server I have this issue in the console totally spamming it.**

`[15:46:14] [Server thread/ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but has net.minecraft.server.v1_16_R2.TileEntityBrewingStand@324582a0. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[15:46:14] [Server thread/ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but has net.minecraft.server.v1_16_R2.TileEntityBrewingStand@7ac58aef. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[15:46:14] [Server thread/ERROR]: Block at -281, 77, -256 is Block{minecraft:barrier} but has net.minecraft.server.v1_16_R2.TileEntityBrewingStand@317fe069. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

**Is there any way to change the default messages by opening server.jar in winrar ? I was trying to find the messages file but I can't find it. Or how to fix it? I tried using FastAsyncWorldEdit and //set air but that didn't help too.**

**Comment by Proximyst** [comment] 2020-10-02 13:51
Duplicate of #2680.

**Closed as completed by Proximyst** 2020-10-02 13:51 UTC
Labels: resolution: duplicate
