### ISSUE TITLE
Server crash possibly related to lighting queue

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#4641] opened 2020-10-11 01:00 UTC
### Paper version:
This server is running Paper version git-Paper-"1916ab2b" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

I recently updated to 1.16 but have started getting these crashes which don't seem to provide much info, the only thing that seems to stick out is:

```
[23:40:11] [Paper Watchdog Thread/ERROR]: ------------------------------
[23:40:11] [Paper Watchdog Thread/ERROR]: Current Thread: plotworld - Light
[23:40:11] [Paper Watchdog Thread/ERROR]: 	PID: 154 | Suspended: false | Native: false | State: RUNNABLE
[23:40:11] [Paper Watchdog Thread/ERROR]: 	Stack:
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineGraph.b(SourceFile:175)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineSky.a(LightEngineSky.java:133)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineGraph.b(SourceFile:221)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineLayer.a(LightEngineLayer.java:189)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngine.a(SourceFile:61)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineThreaded.b(LightEngineThreaded.java:331)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineThreaded.lambda$queueUpdate$20(LightEngineThreaded.java:316)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.LightEngineThreaded$$Lambda$5648/0x000000080220d840.run(Unknown Source)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.ThreadedMailbox.e(ThreadedMailbox.java:90)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.ThreadedMailbox.a(ThreadedMailbox.java:137)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R2.ThreadedMailbox.run(ThreadedMailbox.java:102)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		java.base@14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		java.base@14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:40:11] [Paper Watchdog Thread/ERROR]: 		java.base@14/java.lang.Thread.run(Thread.java:832)
[23:40:11] [Paper Watchdog Thread/ERROR]: ------------------------------
```

Here is the entire log: https://paste.gg/p/anonymous/31e18f1c726944cdbe712d9f42f548de
My Paper config: https://paste.gg/p/anonymous/9953440045934c1193c6dcf52573e3fb

The log gives a chunk location of -133, 84 which I've converted for blocks as -2128,0,1344 to -2113,15,1359 but I am very confused because there doesn't seem to be anything abnormal in this location, here's a screenshot:
https://i.imgur.com/YfUxEFs.jpg

@aikar I'm hoping that you can shed some more information on what is going on here since I'm puzzled

**Comment by aikar** [comment] 2020-10-11 17:34
it just looks like either the queue was overloaded, or ran out of memory and it slowed processing down.

Going to close as duplicate of https://github.com/PaperMC/Paper/issues/4288 as thats closest going to get to this.

nothing was blocked in your logs, just didnt complete the work fast enough

though I did just make some tweaks last night that might help?

**Closed as completed by aikar** 2020-10-11 17:34 UTC
