### ISSUE TITLE
[bug]same items cannot stack in server

### ISSUE THREAD

**Issue by hkkongou** [PaperMC/Paper#4910] opened 2020-12-19 06:41 UTC
paper 1.16.4 #333

Yes
### What behaviour is expected:
same item generated by same plugin can stack.

### What behaviour is observed:
items generated by plugin will not stack, plugin: mythicmobs 4.10, item that have same nbt , lore, name, generated by plugin cannot stack with each other. It can stack only if the player relogin game.

### **IMPORTANT**
**This link contain report of mythicmobs users that have this problem, all of them point out that paper or fork of paper in 1.16 have such problem and still not been fixed, they also point out that spigot don't have such problem**
https://www.mythicmobs.net/index.php?threads/bug-items-dont-stack-after-reconect-on-server.12656/

### Steps/models to reproduce:
mm item get <something>

### Paper version:
[14:39:47 INFO]: This server is running Paper version git-Paper-333 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[14:39:47 INFO]: Checking version, please wait...
[14:39:48 INFO]: Previous version: git-Tuinity-"576e2cc" (MC: 1.16.3)
[14:39:48 INFO]: You are running the latest version

**Comment by electronicboy** [comment] 2020-12-19 06:42
Duplicate of #4888

**Closed as completed by electronicboy** 2020-12-19 06:42 UTC
Labels: version: 1.16
