### ISSUE TITLE
shulker boxes dupe

### ISSUE THREAD

**Issue by guccihub** [PaperMC/Paper#488] opened 2016-11-20 16:24 UTC
git-Paper-924

**Comment by RoyCurtis** [comment] 2016-11-20 21:51
Thanks for sharing; I want to help test this.

Can you please post, if possible:
- What plugins are used on that server (can you share `/plugins` or a URL?)
- What method you are using to move items back and forth? (SHIFT-click?)

**Comment by RoyCurtis** [comment] 2016-11-20 22:25
I was able to reproduce this myself. ~~I believe this is a PaperSpigot issue than a Spigot issue.~~ It appears to be a race condition and a vanilla 1.11 issue.

# Reproduction

1. Grab a friend in Survival mode with a pickaxe
2. Place an empty shulker box of any color on the ground
3. `/give` yourself a nether star or obtain one
4. Open the shulker box, drag the nether star and then rapidly left click into the box (as if rapidly inserting and removing the star)
5. Whilst doing so, said friend should break the box
6. When box is broken, place on ground and check contents

If the nether star is inside and either you or friend have a star or it is on the ground, the reproduction has succeeded. If not, repeat from step 2. It may take up to three tries.

# Testing

* Live `git-Paper-924` with 28 plugins - **reproducible**
* Live `git-Paper-924` with 0 plugins - **reproducible**
* Live `git-Paper-924` with 0 plugins and default `paper.yml` - **reproducible**
* Live `CraftBukkit version git-Spigot-16c940b-ac99d7d` with 0 plugins - **reproducible**
* Live 1.11 vanilla - **reproducible**

# Notes

Special thanks to players SRpumpkin034, The_Doctor017, Scrogs63, Opusnut and StitchHasAGlitch for helping me test this.

**Comment by RoyCurtis** [comment] 2016-11-20 22:50
~~FWIW, I seem to have fixed this by mass-replacing all `false` values to `true` in `paper.yml`. So _maybe_ a matter of finding which setting (and therefore, which patch) is causing this?~~

**Comment by RoyCurtis** [comment] 2016-11-21 00:55
Really sorry; after further testing, this is not a PaperSpigot issue after all. ~~Might be Spigot, might be vanilla.~~ It's just that the reproduction is _really_ unreliable and can take up to 20 tries.

EDIT: Yep, it's a vanilla bug!

**Comment by RoyCurtis** [comment] 2016-11-21 01:19
Reported at https://bugs.mojang.com/browse/MC-110498

**Comment by bmintz** [comment] 2016-11-21 02:37
@RoyCurtis aww… now they're gonna fix it…

**Comment by Shevchik** [comment] 2016-11-24 18:55
That's actually a really old dupe. Similar to this one https://hub.spigotmc.org/jira/browse/SPIGOT-178 (That one was fixed by not allowing to operate on zero amont itemstacks, but that doesn't really fixed the root of this issue).

It caused by the fact that you can take items from container of already destroyed block. In latest version your click packet should be handled on the same tick as block destroy happened, but it is still possible.
To fix this inventory click handling should first check if container is reachable.

**Comment by guccihub** [comment] 2016-11-28 10:24
Any temp work around ideas? Besides disabling shulker boxes.

**Comment by guccihub** [comment] 2016-12-02 11:09
Having trouble reproducing on paper #956, can anyone else confirm if it's solved?

**Comment by aikar** [comment] 2017-01-02 20:15
There def still is an issue, as I encountered it. Hopefully Ill figure it out or Mojang will.

**Comment by Shevchik** [comment] 2017-01-02 20:37
Try this plugin and see if it fixes the issue.
https://www.dropbox.com/s/exdwyk6pcfdfzkb/ActionValidators.jar?dl=0

**Comment by aikar** [comment] 2017-01-02 21:04
Plugin Source? What does it do?

**Comment by Shevchik** [comment] 2017-01-02 21:22
Prevents clicking in inventories of already broken blocks.
Closes inventory when player issues command.
Does not allow breaking blocks and interacting when inventory is open.

Will upload source a bit later.

**Comment by aikar** [comment] 2017-01-02 21:34
I actually found out my issue was specific to my server, but I did find an issue in the servers code which i'm about to push to paper

**Closed as completed** 2017-01-02 21:50 UTC
Labels: upstream: vanilla, version: 1.11
